import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,readFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Access} from './access.mjs'
import {Budget} from './budget.mjs'
const req=(cookie,origin='https://studio.example.com')=>({headers:{origin,cookie},socket:{remoteAddress:'127.0.0.1'}})
test('login, cookie segura, rol y cierre de sesión',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-auth-'));t.after(()=>rm(dir,{recursive:true,force:true}));const a=await new Access(dir,{origin:'https://studio.example.com'}).init();const secret=(await readFile(join(dir,'initial-access.txt'),'utf8')).split('\n')[1].split(': ')[1];assert.equal(a.user(req()),null);await assert.rejects(a.login(req(undefined,'https://evil.test'),{username:'gabriel',password:secret}),e=>e.status===403);await assert.rejects(a.login(req(),{username:'gabriel',password:'wrong'}),e=>e.status===401);const r=await a.login(req(),{username:'gabriel',password:secret});assert.match(r.cookie,/Secure/);assert.match(r.cookie,/HttpOnly/);assert.equal(a.require(req(r.cookie)).role,'admin');await a.logout(req(r.cookie));assert.equal(a.user(req(r.cookie)),null);assert.ok(!(await readFile(join(dir,'users.json'),'utf8')).includes(secret))})
test('contraseña propia requiere la anterior y lector no obtiene permisos de escritura',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-role-'));t.after(()=>rm(dir,{recursive:true,force:true}));const a=await new Access(dir,{origin:'https://studio.example.com'}).init();await a.change({username:'gabriel',role:'admin'},{username:'lector',role:'viewer',password:'example-password-123'});const r=await a.login(req(),{username:'lector',password:'example-password-123'});assert.throws(()=>a.require(req(r.cookie),['admin','editor']),e=>e.status===403);await assert.rejects(a.change({username:'lector',role:'viewer'},{username:'lector',password:'another-password-123',current_password:'wrong'}),e=>e.status===403)})
test('reservas concurrentes respetan techo diario y por trabajo',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-budget-'));t.after(()=>rm(dir,{recursive:true,force:true}));const b=new Budget(dir,{daily:1});const out=await Promise.allSettled([b.reserve('1',.6,'voice','j',1),b.reserve('2',.6,'voice','j',1)]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal((await b.summary()).reserved_today,.6)})

 test('sessions survive restart, renew with activity and logout remains revoked after restart',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-persistent-auth-'));t.after(()=>rm(dir,{recursive:true,force:true}));let now=Date.now();t.mock.method(Date,'now',()=>now);const options={origin:'https://studio.example.com'};const a=await new Access(dir,options).init();const password=(await readFile(join(dir,'initial-access.txt'),'utf8')).split('\n')[1].split(': ')[1];const login=await a.login(req(),{username:'gabriel',password});const cookie=login.cookie;assert.match(cookie,/Max-Age=2592000/);assert.ok(!(await readFile(join(dir,'sessions.json'),'utf8')).includes(cookie.split(';')[0].split('=')[1]));const b=await new Access(dir,options).init();assert.equal(b.user(req(cookie)).username,'gabriel');now+=29*86400000;assert.match(await b.refresh(req(cookie)),/Max-Age=2592000/);now+=2*86400000;const c=await new Access(dir,options).init();assert.equal(c.user(req(cookie)).role,'admin');await c.logout(req(cookie));const d=await new Access(dir,options).init();assert.equal(d.user(req(cookie)),null)});
 test('password change revokes persisted sessions and inactivity expires them',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-expiry-'));t.after(()=>rm(dir,{recursive:true,force:true}));const options={origin:'https://studio.example.com'},a=await new Access(dir,options).init();await a.change({username:'gabriel',role:'admin'},{username:'editor',password:'old-password-long-123',role:'editor'});const r=await a.login(req(),{username:'editor',password:'old-password-long-123'});await a.change({username:'gabriel',role:'admin'},{username:'editor',password:'new-password-long-123',role:'editor'});assert.equal((await new Access(dir,options).init()).user(req(r.cookie)),null);const login=await a.login(req(),{username:'editor',password:'new-password-long-123'});const future=Date.now()+31*86400000;t.mock.method(Date,'now',()=>future);assert.equal(a.user(req(login.cookie)),null)});
