import {readFile,writeFile,mkdir,appendFile,rename} from 'node:fs/promises'
import {join} from 'node:path'
import {randomBytes,scrypt as derive,timingSafeEqual,createHash,randomUUID} from 'node:crypto'
import {promisify} from 'node:util'
const SESSION_MS=30*86400000,MAX_SESSION_MS=90*86400000;
const tokenFrom=req=>String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('studio_session='))?.slice(15);
const scrypt=promisify(derive),hash=x=>createHash('sha256').update(x).digest('hex')
const fail=(status,message)=>Object.assign(Error(message),{status})
export class Access {
 constructor(state,{origin,enabled=true}={}){this.state=state;this.origin=origin;this.enabled=enabled;this.sessions=new Map();this.attempts=new Map();this.serial=Promise.resolve();this.sessionWrites=Promise.resolve()}
 async init(){await mkdir(this.state,{recursive:true,mode:0o700});try{this.users=JSON.parse(await readFile(join(this.state,'users.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;const password=randomBytes(24).toString('base64url');this.users=[await this.record(process.env.STUDIO_ADMIN_USER||'gabriel',password,'admin')];await this.save();await writeFile(join(this.state,'initial-access.txt'),`Usuario: ${this.users[0].username}\nContraseña inicial: ${password}\nCámbiala desde Cuenta al entrar. Este archivo no se sirve por HTTP.\n`,{mode:0o600,flag:'wx'})}try{const rows=JSON.parse(await readFile(join(this.state,'sessions.json'),'utf8'));this.sessions=new Map(rows.filter(([id,s])=>/^[a-f0-9]{64}$/.test(id)&&s.expires>Date.now()&&s.absolute_expires>Date.now()&&this.users.some(u=>u.username===s.username&&s.credential===hash(u.hash))))}catch(e){if(e.code!=='ENOENT')throw e}return this}
 async persistSessions(){const action=async()=>{const tmp=join(this.state,'sessions.'+randomUUID()+'.tmp');await writeFile(tmp,JSON.stringify([...this.sessions]),{mode:0o600});await rename(tmp,join(this.state,'sessions.json'))};const p=this.sessionWrites.then(action);this.sessionWrites=p.catch(()=>{});return p}
 async refresh(req){const token=tokenFrom(req),s=token&&this.sessions.get(hash(token));if(!s||!this.user(req))return null;const now=Date.now();if(now-(s.touched||0)<3600000)return null;s.touched=now;s.expires=Math.min(now+SESSION_MS,s.absolute_expires);await this.persistSessions();return this.cookie(token,false,Math.floor((s.expires-now)/1000))}
 async record(username,password,role){if(!/^[a-z0-9][a-z0-9@._-]{2,79}$/i.test(username)||typeof password!=='string'||password.length<14||password.length>200||!['admin','editor','viewer'].includes(role))throw fail(422,'Usuario inválido, contraseña menor de 14 caracteres o rol desconocido');const salt=randomBytes(16).toString('hex');return {username,role,salt,hash:(await scrypt(password,salt,64)).toString('hex')}}
 async save(){const tmp=join(this.state,'users.'+randomUUID()+'.tmp');await writeFile(tmp,JSON.stringify(this.users),{mode:0o600});await rename(tmp,join(this.state,'users.json'))}
 audit(actor,event,detail={}){return appendFile(join(this.state,'audit.jsonl'),JSON.stringify({at:new Date().toISOString(),actor,event,...detail})+'\n',{mode:0o600})}
 cookie(id,expired=false,maxAge=SESSION_MS/1000){return `studio_session=${expired?'':id}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${expired?0:maxAge}${this.origin.startsWith('https:')?'; Secure':''}`}
 sameOrigin(req){if(req.headers.origin!==this.origin)throw fail(403,'Origen no autorizado')}
 user(req){if(!this.enabled)return {username:'local',role:'admin'};const id=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('studio_session='))?.slice(15);if(!id)return null;const session=this.sessions.get(hash(id));if(!session)return null;if(session.expires<=Date.now()||session.absolute_expires<=Date.now()){this.sessions.delete(hash(id));return null}const u=this.users.find(x=>x.username===session.username);return u&&session.credential===hash(u.hash)?{username:u.username,role:u.role}:null}
 require(req,roles=['admin','editor','viewer']){const u=this.user(req);if(!u)throw fail(401,'Inicia sesión');if(!roles.includes(u.role))throw fail(403,'Tu cuenta no tiene este permiso');return u}
 async login(req,{username,password}){
 this.sameOrigin(req);if(typeof username!=='string'||typeof password!=='string'||password.length>200)throw fail(401,'Credenciales incorrectas')
 const ip=req.socket.remoteAddress||'local',k=ip+':'+username.toLowerCase(),now=Date.now();let a=this.attempts.get(k);if(!a||a.until<now)a={n:0,until:now+15*60000};if(a.n>=5)throw fail(429,'Demasiados intentos; espera 15 minutos');a.n++;if(this.attempts.size>2000)this.attempts.clear();this.attempts.set(k,a)
 const u=this.users.find(x=>x.username===username),value=await scrypt(password,u?.salt||'00000000000000000000000000000000',64)
 if(!u||!timingSafeEqual(value,Buffer.from(u.hash,'hex'))){await this.audit(username.slice(0,80),'login_failed');throw fail(401,'Credenciales incorrectas')}
 this.attempts.delete(k);for(const [id,s]of this.sessions)if(s.expires<now)this.sessions.delete(id)
 const token=randomBytes(32).toString('base64url');this.sessions.set(hash(token),{username:u.username,credential:hash(u.hash),expires:now+SESSION_MS,absolute_expires:now+MAX_SESSION_MS,touched:now});await this.persistSessions();await this.audit(u.username,'login');return {cookie:this.cookie(token),user:{username:u.username,role:u.role}}
 }
 async logout(req){const token=String(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('studio_session='))?.slice(15);if(token)this.sessions.delete(hash(token));await this.persistSessions();return this.cookie('',true)}
 async change(actor,{username,password,role,current_password}){const action=async()=>{const old=this.users.find(u=>u.username===username);if(actor.role!=='admin'||username===actor.username){if(username!==actor.username||!old||typeof current_password!=='string'||!timingSafeEqual(await scrypt(current_password,old.salt,64),Buffer.from(old.hash,'hex')))throw fail(403,'Confirma tu contraseña actual');role=old.role}if(old?.role==='admin'&&role!=='admin'&&this.users.filter(u=>u.role==='admin').length===1)throw fail(422,'Debe quedar al menos un administrador');const user=await this.record(username,password,role);this.users=this.users.filter(u=>u.username!==username).concat(user);await this.save();for(const [id,s]of this.sessions)if(s.username===username)this.sessions.delete(id);await this.persistSessions();await this.audit(actor.username,'account_updated',{username,role});return {ok:true}};const p=this.serial.then(action);this.serial=p.catch(()=>{});return p}
}
export const loginPage=`<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Entrar · GCODE Studio</title><link rel="stylesheet" href="/ui.css"><body class="login-page"><form><div class="eyebrow">COMANDPOS STUDIO</div><h1>Tu próxima idea empieza aquí.</h1><p>Entra a tu espacio creativo.</p><label>Usuario<input name="username" autocomplete="username" required></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><button>Entrar</button><p id="error" role="status"></p></form><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=document.querySelector('button');button.disabled=true;try{const r=await fetch('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});const d=await r.json();if(!r.ok)throw Error(d.error);const next=new URLSearchParams(location.search).get('next');location.href=/^\\/(?:centro|editor|feed-editor|marketing|create|account)\\.html(?:[?#]|$)/.test(next||'')?next:'/centro.html'}catch(e){document.querySelector('#error').textContent=e.message}finally{button.disabled=false}}</script></html>`
