import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,readFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Access} from './access.mjs'
import {Budget} from './budget.mjs'
const req=(cookie,origin='https://studio.example.com')=>({headers:{origin,cookie},socket:{remoteAddress:'127.0.0.1'}})
test('login, cookie segura, rol y cierre de sesión',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-auth-'));t.after(()=>rm(dir,{recursive:true,force:true}));const a=await new Access(dir,{origin:'https://studio.example.com'}).init();const secret=(await readFile(join(dir,'initial-access.txt'),'utf8')).split('\n')[1].split(': ')[1];assert.equal(a.user(req()),null);await assert.rejects(a.login(req(undefined,'https://evil.test'),{username:'gabriel',password:secret}),e=>e.status===403);await assert.rejects(a.login(req(),{username:'gabriel',password:'wrong'}),e=>e.status===401);const r=await a.login(req(),{username:'gabriel',password:secret});assert.match(r.cookie,/Secure/);assert.match(r.cookie,/HttpOnly/);assert.equal(a.require(req(r.cookie)).role,'admin');a.logout(req(r.cookie));assert.equal(a.user(req(r.cookie)),null);assert.ok(!(await readFile(join(dir,'users.json'),'utf8')).includes(secret))})
test('contraseña propia requiere la anterior y lector no obtiene permisos de escritura',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-role-'));t.after(()=>rm(dir,{recursive:true,force:true}));const a=await new Access(dir,{origin:'https://studio.example.com'}).init();await a.change({username:'gabriel',role:'admin'},{username:'lector',role:'viewer',password:'example-password-123'});const r=await a.login(req(),{username:'lector',password:'example-password-123'});assert.throws(()=>a.require(req(r.cookie),['admin','editor']),e=>e.status===403);await assert.rejects(a.change({username:'lector',role:'viewer'},{username:'lector',password:'another-password-123',current_password:'wrong'}),e=>e.status===403)})
test('reservas concurrentes respetan techo diario y por trabajo',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-budget-'));t.after(()=>rm(dir,{recursive:true,force:true}));const b=new Budget(dir,{daily:1});const out=await Promise.allSettled([b.reserve('1',.6,'voice','j',1),b.reserve('2',.6,'voice','j',1)]);assert.equal(out.filter(x=>x.status==='fulfilled').length,1);assert.equal((await b.summary()).reserved_today,.6)})
