import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Marketing} from './marketing.mjs'
import {assertJob,assertGenerated} from './contracts.mjs'
import {editorialIssues} from './editorial.mjs'
import {proposals,deriveCampaign} from './planning.mjs'
import {sceneKey,cachedScene} from './scene-cache.mjs'
import {Budget} from './budget.mjs'
const job={id:'job-test',brand_id:'comandpos',kind:'video',status:'succeeded',options:{voice:true},artifact:{sha256:'a'.repeat(64),duration:10,quality:{warnings:[]}},review:{status:'approved'}},store={get:()=>structuredClone(job)}
async function setup(t){const root=await mkdtemp(join(tmpdir(),'studio-plan-'));t.after(()=>rm(root,{recursive:true,force:true}));const m=await new Marketing(root).init();const c=await m.saveCampaign({brand_id:'comandpos',name:'Contenido',objective:'Explicar pedidos y modificadores',status:'active'},'owner');const p=await m.savePiece({campaign_id:c.id,title:'Pedidos claros',caption:'Consulta los pedidos.',kind:'video',channel:'facebook',job_id:job.id,scheduled_at:new Date(Date.now()-1000).toISOString()},'owner',store);return {root,m,c,p}}
async function approve(m,p){const v=m.releasePreview(p.id,store);return m.approveRelease({piece_id:p.id,hash:v.hash},'owner',store)}
test('caption, channel and account are bound to a reviewed immutable release',async t=>{const {m,p}=await setup(t);await assert.rejects(m.schedule({piece_id:p.id},'owner',store),/publicación completa/);const r=await approve(m,p);assert.match(r.bundle.caption,/Narración generada con IA/);await m.savePiece({...p,caption:'Texto distinto'},'editor',store);await assert.rejects(m.schedule({piece_id:p.id},'owner',store),/publicación completa/);assert.equal(m.snapshot().releases[0].status,'revoked');await approve(m,p);const d=await m.schedule({piece_id:p.id},'owner',store);assert.equal(d.caption,'Texto distinto\n\nNarración generada con IA.');assert.equal(m.validateDelivery(d.id,store).release.hash,d.release_hash)})
test('stale preview, changed brand and unresolved comments prevent delivery',async t=>{const {m,p}=await setup(t);const preview=m.releasePreview(p.id,store);await m.savePiece({...p,caption:'Otro texto'},'editor',store);await assert.rejects(m.approveRelease({piece_id:p.id,hash:preview.hash},'owner',store),/cambió/);const comment=await m.addComment({job_id:job.id,text:'Corregir frase'},'editor',store);await assert.rejects(approve(m,p),/comentarios/);await m.resolveComment({id:comment.id,resolved:true},'editor');await approve(m,p);const d=await m.schedule({piece_id:p.id},'owner',store);await m.saveBrand({...m.brand('comandpos'),accent:'#112233'},'owner');assert.throws(()=>m.validateDelivery(d.id,store),/publicación completa/);const claim=await m.claim({channel:'facebook'},'n8n',store);assert.equal(claim.status,'blocked')})
test('expired claims become uncertain, never automatically requeued',async t=>{const {m,p}=await setup(t);await approve(m,p);await m.schedule({piece_id:p.id},'owner',store);const d=await m.claim({channel:'facebook'},'n8n',store);m.data.deliveries[0].claimed_at=new Date(Date.now()-46*60000).toISOString();assert.equal(await m.claim({channel:'facebook'},'n8n',store),null);assert.equal(m.data.deliveries[0].status,'uncertain');await m.result({id:d.id,claim_token:d.claim_token,status:'published',post_id:'receipt',url:'https://facebook.com/receipt'},'n8n');assert.equal(m.data.deliveries[0].status,'published')})
test('imported publications are explicitly attributed and deduplicated',async t=>{const {m}=await setup(t);const input={source:'legacy',brand_id:'comandpos',channel:'instagram',post_id:'old',url:'https://instagram.com/p/old'};const a=await m.importPublication(input,'owner',store),b=await m.importPublication(input,'owner',store);assert.equal(a.id,b.id);assert.equal(a.published_at,null);assert.equal(a.source,'legacy');assert.equal(m.snapshot().deliveries.length,1)})
test('job contracts reject unknown options, ambiguous sources and invalid ratios before spending',()=>{for(const input of [{brand_id:'comandpos',kind:'video',script:{},template_id:'x'},{brand_id:'comandpos',kind:'video',script:{},publish:true},{brand_id:'comandpos',kind:'video',script:{},aspect:'banana'}])assert.throws(()=>assertJob(input));assert.doesNotThrow(()=>assertJob({brand_id:'comandpos',kind:'video',script:{},aspect:'portrait'}));assert.throws(()=>assertGenerated({type:'object',additionalProperties:false,required:['text'],properties:{text:{type:'string'}}},{other:'invalid'}))})
test('editorial guard checks actual content, not warnings explaining limitations',()=>{assert.equal(editorialIssues({caption:'Registra los pedidos.',warnings:['No prometer demo gratis']}).length,0);for(const caption of ['Opera sin retrasos.','Garantiza tus resultados.','Demo gratis','Aumenta 25% las ventas','Un caso real'])assert.ok(editorialIssues({caption}).length)})
test('campaign proposals use objectives, recent publications and same-brand resources',async t=>{const {m,c}=await setup(t),data=m.snapshot();data.assets=[{id:'one',brand_id:'comandpos',type:'image',name:'Pedidos modificadores',tags:'pedidos'},{id:'wrong',brand_id:'gcode',type:'image',name:'Pedidos modificadores',tags:'pedidos'}];const first=proposals(data,m.brand('comandpos'),[],c);assert.match(first[0].idea,/Explicar pedidos/);assert.ok(first.every(p=>p.resources.every(r=>r.id!=='wrong')));data.deliveries.push({brand_id:'comandpos',status:'published',caption:first[0].topic,published_at:new Date().toISOString()});const next=proposals(data,m.brand('comandpos'),[],{...c,objective:''});assert.notEqual(next[0].topic,first[0].topic);const variants=deriveCampaign(data,c,first[0]);assert.equal(new Set(variants.map(v=>v.kind)).size,4);assert.equal(new Set(variants.map(v=>v.concept_id)).size,1);assert.ok(variants.every(v=>v.scheduled_at===null&&!v.job_id))})
test('scene cache isolates changed scene and rejects incomplete checkpoints',async t=>{const {root}=await setup(t);const base={scene:{id:'x',titulo:'A',dur:2},source:'source',renderer:'renderer',aspect:'vertical',fps:30,preview:false};const a=sceneKey(base);assert.equal(a,sceneKey({...base,scene:{...base.scene,id:'different-id'}}));assert.notEqual(a,sceneKey({...base,scene:{...base.scene,titulo:'B'}}));assert.notEqual(a,sceneKey({...base,renderer:'new-renderer'}));const dir=join(root,'cache');await mkdir(dir);await writeFile(join(dir,a+'.mp4'),'partial');assert.equal(await cachedScene(dir,a,60),null);await writeFile(join(dir,a+'.json'),JSON.stringify({frames:60}));assert.ok(await cachedScene(dir,a,60));assert.equal(await cachedScene(dir,a,90),null)})
test('costs distinguish reservation from invoice and preserve linkage',async t=>{const {root}=await setup(t),b=new Budget(join(root,'budget'));await b.reserve('idea:x',.1,'guion');await b.attach('idea:x','job-x');await b.reconcile('idea:x',.012,'invoice-reference','owner');const s=await b.summary();assert.equal(s.reserved_today,.1);assert.equal(s.confirmed_usd,.012);assert.equal(s.entries[0].job,'job-x');assert.equal(s.unconfirmed_entries,0)})
test('scoped API clients cannot approve or use publication operations with producer credentials',async()=>{const {authorizeApi}=await import('./api-scopes.mjs');const {createHash}=await import('node:crypto');const token='publisher-secret',clients={legacy_scopes:['read','produce'],clients:[{sha256:createHash('sha256').update(token).digest('hex'),scopes:['read','publish','metrics']}]};assert.equal(authorizeApi('Bearer producer','/api/v1/jobs','POST','producer',clients),true);assert.equal(authorizeApi('Bearer producer','/api/v1/deliveries/claim','POST','producer',clients),false);assert.equal(authorizeApi('Bearer '+token,'/api/v1/deliveries/claim','POST','producer',clients),true);assert.equal(authorizeApi('Bearer '+token,'/api/v1/ideas','POST','producer',clients),false);assert.equal(authorizeApi('Bearer invalid','/api/v1/jobs','GET','producer',clients),false)})
test('unverifiable legacy history never fabricates a public link and can later be confirmed',async t=>{const {m}=await setup(t);const input={source:'legacy',verification:'unavailable',brand_id:'comandpos',channel:'instagram',post_id:'missing',published_at:'2026-09-01T12:00:00Z'};const r=await m.importPublication(input,'owner',store);assert.equal(r.status,'legacy_unverified');assert.equal(r.url,null);const confirmed=await m.importPublication({...input,verification:'confirmed',url:'https://instagram.com/p/known'},'owner',store);assert.equal(confirmed.id,r.id);assert.equal(confirmed.status,'published')})
test('expired resource rights block approval even when the video is technically approved',async t=>{const {m,p}=await setup(t);m.data.assets.push({id:'asset',brand_id:'comandpos',hash:'hash',expires_at:'2026-01-01'});assert.throws(()=>m.releasePreview(p.id,{get:()=>({...job,resource_ids:['asset']})}),/permiso venció/)})
