const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,marketing,user,pending=false,action;
async function api(path,body){const r=await fetch('/api/ads'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'No se pudo completar');return data}
function notice(message,error=false){$('ads-status').textContent=message;$('ads-status').className=error?'error':''}
async function run(fn){if(pending)return;pending=true;document.querySelectorAll('button').forEach(b=>{b.dataset.previousDisabled=String(b.disabled);b.disabled=true});try{await fn();await load();return true}catch(e){notice(e.message,true);$('action-error').textContent=e.message;return false}finally{pending=false;document.querySelectorAll('button[data-previous-disabled]').forEach(b=>{b.disabled=b.dataset.previousDisabled==='true';delete b.dataset.previousDisabled})}}
function options(rows){return rows.map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('')}
const admin=()=>user?.role==='admin',button=(label,action,id,disabled=false)=>`<button data-action="${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${label}</button>`;
function render(){
 $('ads-mode').textContent=state.writes_enabled?'La creación requiere dos aprobaciones y produce objetos pausados. Activar exige confirmar explícitamente el presupuesto.':'Puedes preparar anuncios y consultar resultados. Para crear campañas, primero debemos verificar el acceso publicitario de tu cuenta.';
 $('connection-create').hidden=!admin();$('connection-brand').innerHTML=options(marketing.brands.map(b=>[b.id,b.name]));
 const connections=state.connections;$('connection-list').innerHTML=connections.length?connections.map(c=>`<article class="ads-card"><h3>${esc(c.metadata?.name||c.account_id)}</h3><p>${esc(c.platform)} · ${esc(c.account_id)}<br>Marca: ${esc(c.brand_id)}</p><p>${c.status==='verified'?'Lectura comprobada':'Acceso sin verificar'}${c.metadata?` · ${esc(c.metadata.currency)}<br>${esc(c.metadata.timezone)}<small>Comprobado: ${esc(new Date(c.metadata.verified_at).toLocaleString())}</small>`:''}</p>${button('Verificar acceso','verify',c.id,!admin())}</article>`).join(''):'<p class="ads-empty">Todavía no hay cuentas publicitarias verificadas. Registra tu cuenta de Meta para comenzar con consultas de lectura.</p>';
 const selectedAccount=$('sync-connection').value;$('sync-connection').innerHTML=options(connections.filter(c=>c.status==='verified').map(c=>[c.id,c.account_id+' · '+c.platform]));if(connections.some(c=>c.id===selectedAccount))$('sync-connection').value=selectedAccount;
 $('draft-list').innerHTML=state.drafts.length?state.drafts.map(d=>{const url='/api/centro/jobs/'+encodeURIComponent(d.snapshot.job_id)+'/artifacts/'+(d.snapshot.kind==='video'?'video':'image-1');return `<article class="ads-card"><h3>${esc(d.config.name)}</h3>${d.snapshot.kind==='video'?`<video class="ads-preview" controls preload="metadata" src="${url}"></video>`:`<img class="ads-preview" src="${url}" alt="Creatividad del anuncio">`}<p>${esc(d.config.copy)}</p><small>Versión ${d.revision} · ${esc(d.hash.slice(0,12))}<br>${esc(d.config.destination)}<br>Total: ${esc(d.config.budget_minor)} unidades menores ${esc(d.config.currency)}<br>${esc(d.config.start_time)} → ${esc(d.config.end_time)}</small><p>Editorial: ${d.editorial?'aprobada':'pendiente'} · Gasto: ${d.authorization?'autorizado':'pendiente'}</p>${button('Editar','edit',d.id,!['admin','editor'].includes(user.role))}${button('Revisar editorial','approve',d.id,!admin())}${button('Autorizar presupuesto','authorize',d.id,!admin()||!d.editorial)}${button('Crear en pausa','execute',d.id,!admin()||!d.authorization||!state.writes_enabled)}</article>`}).join(''):'<p class="ads-empty">Selecciona una pieza existente. Su revisión editorial y autorización de inversión se conservarán por separado.</p>';
 $('operation-list').innerHTML=state.operations.length?state.operations.map(o=>`<article class="ads-card"><h3>${esc(state.drafts.find(d=>d.id===o.draft_id)?.config.name||o.id)}</h3><p>Estado: <strong>${esc(o.status)}</strong>${o.phase?' · '+esc(o.phase):''}</p>${o.error?`<p class="ads-warning">${esc(o.error)}</p>`:''}<small>${Object.entries(o.ids).map(([k,v])=>esc(k)+': '+esc(v)).join('<br>')}</small>${button('Reanudar creación','execute',o.draft_id,!admin()||!state.writes_enabled||!['ready','failed'].includes(o.status))}${button('Conciliar ID remoto','reconcile',o.id,!admin()||!['uncertain','failed'].includes(o.status))}${button('Activar con presupuesto','activate',o.id,!admin()||!state.writes_enabled||o.status!=='paused')}${button('Pausar campaña','pause',o.id,!admin()||!state.writes_enabled||!o.ids.campaign)}</article>`).join(''):'<p class="ads-empty">No se ha solicitado ninguna creación publicitaria.</p>';
 $('sync-list').innerHTML=state.syncs.slice(-4).reverse().map(s=>`<p>Consulta ${esc(new Date(s.at).toLocaleString())} · ${esc(s.since)} a ${esc(s.until)} · ${s.complete?'cobertura completa de la consulta':'cobertura parcial'} · ${s.inventory.ads.rows.length} anuncios en inventario.</p>`).join('');
 const filter=new FormData($('sync-form')),rows=state.metrics.filter(m=>(!filter.get('connection_id')||m.connection_id===filter.get('connection_id'))&&(!filter.get('since')||m.since>=filter.get('since'))&&(!filter.get('until')||m.until<=filter.get('until')));
 $('metric-rows').innerHTML=rows.slice(-500).reverse().map(m=>`<tr><td>${esc(m.account_id)}<br>${esc(m.ad_id)}<small>${m.draft_id?'Vinculado a Studio':'Sin vínculo verificado con pieza'}</small></td><td>${esc(m.since)}<br>${esc(m.timezone)}</td><td>${esc(m.values.spend??'No disponible')} ${esc(m.currency)}</td><td>${esc(m.values.impressions??'No disponible')}</td><td>${esc(m.values.clicks??'No disponible')}</td><td>${esc(m.attribution)}<br>${Array.isArray(m.attribution_config)?m.attribution_config.map(a=>esc(a.window_days)+' días · '+esc(a.event_type)).join('<br>'):'Ventana no informada'}<br>${esc(m.coverage)} · ${m.maturity==='provisional'?'día provisional':'día cerrado'}</td></tr>`).join('')||'<tr><td colspan="6">Sin métricas para este filtro. Consultar resultados no crea ni activa anuncios.</td></tr>';
 $('sync-form').querySelector('button[type=submit]').disabled=!admin()||!connections.some(c=>c.status==='verified');$('new-draft').disabled=!['admin','editor'].includes(user.role)||!connections.some(c=>c.platform==='meta'&&c.status==='verified');
}
async function load(){const old=$('sync-connection').value;[state,marketing,user]=await Promise.all([api(''),fetch('/api/marketing').then(r=>r.json()),fetch('/auth/me').then(r=>r.json())]);render();if(state.connections.some(c=>c.id===old))$('sync-connection').value=old}
function draftConnections(){return state.connections.filter(c=>c.platform==='meta'&&c.status==='verified')}
function pieces(){const c=state.connections.find(c=>c.id===$('draft-connection').value);$('draft-piece').innerHTML=options(marketing.pieces.filter(p=>p.brand_id===c?.brand_id&&p.job_id&&['video','imagen'].includes(p.kind)).map(p=>[p.id,p.title]));$('draft-form').elements.currency.value=c?.metadata?.currency||''}
function openDraft(id){const f=$('draft-form');f.reset();f.elements.id.value='';$('draft-connection').innerHTML=options(draftConnections().map(c=>[c.id,c.account_id]));const d=state.drafts.find(d=>d.id===id);if(d)$('draft-connection').value=d.connection_id;pieces();if(d){f.elements.id.value=d.id;f.elements.piece_id.value=d.piece_id;for(const [key,value] of Object.entries(d.config)){if(!f.elements[key])continue;if(['start_time','end_time'].includes(key)){const dt=new Date(value);f.elements[key].value=new Date(+dt-dt.getTimezoneOffset()*60000).toISOString().slice(0,16)}else f.elements[key].value=Array.isArray(value)?value.join(','):value}}$('draft-dialog').showModal()}
function openAction(type,id){action={type,id};$('action-error').textContent='';const d=state.drafts.find(d=>d.id===id),op=state.operations.find(o=>o.id===id),target=d||state.drafts.find(d=>d.id===op?.draft_id);$('action-title').textContent=({approve:'Revisión editorial para publicidad',authorize:'Autorizar presupuesto total',execute:'Crear campaña pausada',reconcile:'Verificar objeto remoto',activate:'Activar publicidad con gasto',pause:'Pausar campaña remota'})[type];
 let html=`<p>${esc(target?.config.name||'')}</p>`;
 if(type==='approve')html+='<label class="check"><input type="checkbox" name="paid_rights" required>Confirmo derechos de uso publicitario de imágenes, música, voces y marcas.</label><label class="check"><input type="checkbox" name="no_special_category" required>Este anuncio no pertenece a categorías especiales (vivienda, empleo, servicios financieros, política u otras restringidas).</label><label>Fuente o nota de la revisión<textarea name="note" required maxlength="1000"></textarea></label>';
 if(['authorize','execute','activate'].includes(type))html+=`<p>Total autorizado: <strong>${esc(target.config.budget_minor)} unidades menores ${esc(target.config.currency)}</strong><br>Destino: ${esc(target.config.destination)}<br>Cuenta: ${esc(state.connections.find(c=>c.id===target.connection_id)?.account_id)}<br>Vigencia: ${esc(target.config.start_time)} → ${esc(target.config.end_time)}</p>`;
 if(type==='authorize')html+='<p>Esta aprobación es distinta de aprobar el contenido. La activación requiere otra acción explícita.</p>';
 if(type==='execute')html+='<p>Se enviarán los recursos a Meta y se crearán objetos pausados. No se activará la campaña.</p>';
 if(type==='reconcile')html+='<p>Solo confirma un objeto existente si corresponde exactamente a la operación. No repitas la creación desde otro sistema.</p><label>ID remoto<input name="remote_id" pattern="[0-9]+" required></label>';
 if(type==='activate')html+=`<p class="ads-warning">Esta acción autoriza entrega publicitaria e inversión real. Escribe ACTIVAR ${esc(target.config.budget_minor)} ${esc(target.config.currency)}.</p><label>Confirmación<input name="confirmation" required autocomplete="off"></label>`;
 if(type==='pause')html+='<p>Se solicitará pausa y se comprobará la respuesta. Puede existir gasto ya realizado o en procesamiento.</p>';
 $('action-content').innerHTML=html;$('action-dialog').showModal();
}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.ads-panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const {action:type,id}=b.dataset;if(type==='verify')run(async()=>{await api('/verify',{connection_id:id});notice('Acceso de lectura comprobado.')});else if(type==='edit')openDraft(id);else openAction(type,id)});
$('connection-form').onsubmit=e=>{e.preventDefault();run(async()=>{const d=Object.fromEntries(new FormData(e.target));d.auto_sync=d.auto_sync==='on';d.allowed_users=d.allowed_users.split(',').map(x=>x.trim()).filter(Boolean);await api('/connections',d);e.target.reset();notice('Conexión guardada. Verifica el acceso antes de continuar.')})};
$('sync-form').onsubmit=e=>{e.preventDefault();run(async()=>{await api('/sync',Object.fromEntries(new FormData(e.target)));notice('Consulta de resultados completada.')})};
$('sync-form').onchange=()=>{const selected=$('sync-connection').value;render();$('sync-connection').value=selected};
$('new-draft').onclick=()=>openDraft();$('close-draft').onclick=()=>{if(confirm('¿Cerrar el formulario? Se perderán los cambios sin guardar.'))$('draft-dialog').close()};$('draft-dialog').addEventListener('cancel',e=>{if(!confirm('¿Descartar cambios sin guardar?'))e.preventDefault()});$('close-action').onclick=()=>$('action-dialog').close();$('draft-connection').onchange=pieces;
$('draft-piece').onchange=()=>{const p=marketing.pieces.find(p=>p.id===$('draft-piece').value);if(p){$('draft-form').elements.name.value=p.title;$('draft-form').elements.copy.value=p.caption||''}};
$('draft-form').onsubmit=e=>{e.preventDefault();run(async()=>{const f=Object.fromEntries(new FormData(e.target)),config={};for(const k of ['name','copy','destination','page_id','instagram_actor_id','currency','budget_minor'])if(f[k])config[k]=f[k];for(const k of ['age_min','age_max'])config[k]=Number(f[k]);for(const k of ['countries','platforms'])config[k]=f[k].split(',').map(x=>x.trim());for(const k of ['start_time','end_time'])config[k]=new Date(f[k]).toISOString();await api('/drafts',{id:f.id||undefined,connection_id:f.connection_id,piece_id:f.piece_id,config});$('draft-dialog').close();notice('Borrador guardado. Aún no se creó ningún anuncio.')})};
$('action-form').onsubmit=e=>{e.preventDefault();run(async()=>{const {type,id}=action,d=state.drafts.find(d=>d.id===id),form=Object.fromEntries(new FormData(e.target));let payload={id,hash:d?.hash,confirmed:true};if(type==='approve')Object.assign(payload,{paid_rights:form.paid_rights==='on',no_special_category:form.no_special_category==='on',note:form.note});if(type==='authorize')Object.assign(payload,{budget_minor:d.config.budget_minor,currency:d.config.currency});if(['activate','pause','reconcile'].includes(type)){const op=state.operations.find(o=>o.id===id);payload={operation_id:id,hash:op.hash,...form}}await api('/'+type,payload);$('action-dialog').close();notice('Acción confirmada. Revisa el estado actualizado.')})};
const end=new Date(Date.now()-86400000),start=new Date(Date.now()-7*86400000);$('sync-form').elements.since.value=start.toISOString().slice(0,10);$('sync-form').elements.until.value=end.toISOString().slice(0,10);
load().then(()=>notice('Publicidad lista. Las métricas orgánicas se mantienen en Marketing.')).catch(e=>notice(e.message,true));
