import {test} from 'node:test';
import assert from 'node:assert/strict';
import {sum,ratio,days,monthRange,chunks,previousRange,report,csv,latestRows} from './ads-analytics.mjs';
const row=(date,id='1',values={spend:'0.10',impressions:'10',clicks:'1'})=>({key:id+date,connection_id:'c',currency:'USD',timezone:'America/Santo_Domingo',ad_id:id,campaign_id:'10',adset_id:'20',since:date,until:date,values,coverage:'complete',fetched_at:'2026-10-01T00:00:00Z',attribution:'unified',api_version:'v24.0'});
const fixture=()=>({connections:[{id:'c',account_id:'act_1',metadata:{currency:'USD',timezone:'America/Santo_Domingo'}}],metrics:[row('2026-09-01'),row('2026-09-02','1',{spend:'0.20',impressions:'90',clicks:'1'})],syncs:[{connection_id:'c',since:'2026-09-01',until:'2026-09-03',complete:true,at:'2026-10-01T00:00:00Z',inventory:{campaigns:{rows:[{id:'10',name:'ComandPOS',objective:'OUTCOME_TRAFFIC'}]},adsets:{rows:[{id:'20',name:'Restaurantes'}]},ads:{rows:[{id:'1',name:'Video',effective_status:'ACTIVE'}]}}}]});
const query={connection_id:'c',since:'2026-09-01',until:'2026-09-03'};
test('money sums are exact including large values; ratios use weighted totals and zero denominator unavailable',()=>{assert.equal(sum(['0.10','0.20']),'0.30');assert.equal(sum(['9007199254740993.01','0.09']),'9007199254740993.10');assert.equal(ratio('2','100',100),'2.0000');assert.equal(ratio('1','0'),null);assert.equal(ratio(null,'10'),null);const r=report(fixture(),query);assert.equal(r.totals.ctr,'2.0000');assert.equal(r.totals.cpc,'0.1500');assert.equal(r.totals.cpm,'3.0000')});
test('calendar supports leap months, year rollovers, equal-length comparisons and max 31-day import windows',()=>{assert.deepEqual(monthRange('2024-02'),{since:'2024-02-01',until:'2024-02-29'});assert.deepEqual(previousRange('2026-01-01','2026-01-31',true),{since:'2025-12-01',until:'2025-12-31'});const parts=chunks('2026-01-01','2026-03-31');assert.equal(parts.length,3);assert.equal(parts.at(-1).until,'2026-03-31');assert.equal(parts.flatMap(p=>days(p.since,p.until)).length,90);assert.ok(parts.every(p=>days(p.since,p.until).length<=31));assert.equal(days('2026-01-01','2027-12-31').length,0)});
test('unknown dates are null, complete empty dates zero, partial later sync invalidates coverage',()=>{const s=fixture(),r=report(s,{...query,until:'2026-09-04'});assert.equal(r.complete,false);assert.equal(r.trend[2].spend,'0');assert.equal(r.trend[3].spend,null);s.syncs.push({connection_id:'c',since:query.since,until:query.until,complete:false,at:'2026-10-02'});assert.equal(report(s,query).coveredDays,0)});
test('missing click fields suppress derived CTR and CPC, never manufacture zero',()=>{const s=fixture();s.metrics[0].values.clicks=null;const r=report(s,query);assert.equal(r.totals.clicks,'1');assert.equal(r.totals.missing.clicks,true);assert.equal(r.totals.ctr,null);assert.equal(r.totals.cpc,null)});
test('account currency timezone isolation, latest attribution version only, do not sum reach',()=>{const s=fixture();s.metrics.push({...row('2026-09-01'),connection_id:'other'},{...row('2026-09-01'),currency:'DOP'},{...row('2026-09-01'),timezone:'UTC'},{...row('2026-09-01'),fetched_at:'2026-10-02',attribution:'changed',values:{spend:'0.40',impressions:'20',clicks:'2',reach:'200'}});const r=report(s,query);assert.equal(r.totals.spend,'0.60');assert.equal(r.rows.length,2);assert.equal(r.totals.reach,undefined);assert.equal(r.attributionGroups,2)});
test('campaign/status/objective filters and entity grouping use latest inventory, search only table',()=>{const s=fixture();assert.equal(report(s,{...query,status:'PAUSED'}).rows.length,0);assert.equal(report(s,{...query,status:'ACTIVE',objective:'OUTCOME_TRAFFIC',campaign:'10'}).rows.length,2);const r=report(s,{...query,group:'ad'});assert.equal(r.entities[0].name,'Video');assert.equal(r.entities[0].campaign,'ComandPOS');assert.equal(report(s,{...query,search:'missing'}).entities.length,0);assert.equal(report(s,{...query,search:'missing'}).totals.spend,'0.30')});
test('CSV preserves precise decimals, quotes and formula protection',()=>{const c=csv([{id:'1',name:'=CMD("bad")',campaign:'@danger',spend:'0.30',impressions:'100',clicks:'2'}],{currency:'USD',account:'act_1',since:'2026-09-01',until:'2026-09-03'});assert.ok(c.includes('"0.30"'));assert.ok(c.includes('"\'=CMD(""bad"")"'));assert.ok(c.includes('"\'@danger"'))});
test('empty imported period is zero, unimported period is unknown',()=>{const s=fixture();s.metrics=[];assert.equal(report(s,query).totals.spend,'0');assert.equal(report(s,{...query,since:'2026-08-01',until:'2026-08-31'}).totals.spend,null)});

test('entirely missing metric is not zero even when dates were queried',()=>{const s=fixture();s.metrics.forEach(r=>r.values.clicks=null);assert.equal(report(s,query).totals.clicks,null);assert.equal(report(s,query).totals.ctr,null);assert.equal(days('2026-02-31','2026-03-05').length,0)});
