import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
import {AdsStore,metricTotals} from './ads/store.mjs'
import {hash,configuration,stamp,sumDecimals} from './ads/contracts.mjs'
import {Transport,AdsProviderError} from './ads/transport.mjs'
import {MetaAds} from './ads/meta.mjs'
import {TikTokAds} from './ads/tiktok.mjs'
import {adsRoute} from './ads/routes.mjs'
import {authorizeApi,requiredScope,adsPrincipal} from './api-scopes.mjs'
const admin={username:'owner',role:'admin'},editor={username:'editor',role:'editor'},viewer={username:'viewer',role:'viewer'};
const baseConfig=()=>({name:'Prueba',destination:'https://example.com/demo',copy:'Texto revisado',page_id:'333',countries:['DO'],platforms:['facebook'],age_min:18,age_max:65,budget_minor:'12000',currency:'USD',start_time:new Date(Date.now()+86400000).toISOString(),end_time:new Date(Date.now()+4*86400000).toISOString()});
async function fixture(t,{allowWrites=true}={}){
 const root=await mkdtemp(join(tmpdir(),'ads-test-'));t.after(()=>rm(root,{recursive:true,force:true}));let capture={piece_id:'piece',job_id:'job',brand_id:'comandpos',kind:'imagen',files:[{sha256:'a'.repeat(64)}],resources:[],caption:'texto'};
 const calls=[],objects={},provider={verify:async()=>({id:'act_123',currency:'USD',timezone:'America/Santo_Domingo',verified_at:stamp(),api_version:'v24.0'}),
  create:async(phase,d,ids)=>{calls.push(phase);const id=String(100+calls.length),c=d.config;objects[id]={id,account_id:'123',status:'PAUSED'};
   if(phase==='campaign')Object.assign(objects[id],{objective:c.objective,name:c.name+' · '+d.hash.slice(0,10),special_ad_categories:[]});
   if(phase==='adset')Object.assign(objects[id],{campaign_id:ids.campaign,lifetime_budget:c.budget_minor,start_time:c.start_time,end_time:c.end_time,billing_event:c.billing_event,optimization_goal:c.optimization_goal,targeting:{geo_locations:{countries:c.countries},age_min:c.age_min,age_max:c.age_max,publisher_platforms:c.platforms}});
   if(phase==='creative')objects[id].object_story_spec={page_id:c.page_id,link_data:{image_hash:ids.media,link:c.destination,message:c.copy,call_to_action:{type:'LEARN_MORE',value:{link:c.destination}}}};
   if(phase==='ad')Object.assign(objects[id],{adset_id:ids.adset,creative:{id:ids.creative}});return {id};},
  inspect:async id=>structuredClone(objects[id]),setStatus:async(id,status)=>{calls.push('status:'+status);objects[id].status=status;return {success:true}},
  insights:async()=>({rows:[{account_id:'123',account_currency:'USD',ad_id:'999',date_start:'2026-09-28',date_stop:'2026-09-28',spend:'0.10',impressions:'12',clicks:'1'}],complete:true}),inventory:async()=>({ads:{rows:[],complete:true},campaigns:{rows:[],complete:true},adsets:{rows:[],complete:true}})};
 const options={capture:async()=>structuredClone(capture),brands:()=>[{id:'comandpos'}],provider:()=>provider,allowWrites};
 const store=await new AdsStore(root,options).init();const c=await store.saveConnection({platform:'meta',account_id:'act_123',brand_id:'comandpos',credential_ref:'META_TEST_TOKEN',allowed_users:['editor','viewer']},admin);await store.verify(c.id,admin);
 return {root,store,c,provider,calls,objects,options,setCapture:value=>capture=value,async draft(){return store.saveDraft({connection_id:c.id,piece_id:'piece',config:baseConfig()},admin)},async approved(){const d=await this.draft();await store.approve({id:d.id,hash:d.hash,paid_rights:true,no_special_category:true,note:'Derechos comprobados'},admin);await store.authorize({id:d.id,hash:d.hash,confirmed:true,budget_minor:d.config.budget_minor,currency:'USD'},admin);return store.draft(d.id,admin)}};
}
const execute=(f,d)=>f.store.execute({id:d.id,hash:d.hash,confirmed:true},admin);
test('Ads scopes do not inherit legacy read/publish; integrations need explicit account allowlist',async t=>{
 const token='private-fixture-token',clients={clients:[{id:'reader',sha256:createHash('sha256').update(token).digest('hex'),scopes:['ads.read'],ad_connections:['one']}]};
 assert.equal(requiredScope('/api/v1/ads','GET'),'ads.read');assert.equal(requiredScope('/api/v1/ads/activate','POST'),'ads.activate');assert.equal(authorizeApi('Bearer legacy','/api/v1/ads','GET','legacy',null),false);assert.equal(authorizeApi('Bearer '+token,'/api/v1/ads/activate','POST','legacy',clients),false);assert.equal(adsPrincipal('Bearer '+token,clients).role,'integration');
 const f=await fixture(t);assert.equal(f.store.snapshot(adsPrincipal('Bearer '+token,clients)).connections.length,0);await assert.rejects(f.store.verify(f.c.id,adsPrincipal('Bearer '+token,clients)),/permiso/);
});
test('connection and draft access are enforced in service, not just UI',async t=>{const f=await fixture(t);assert.equal(f.store.snapshot(viewer).connections.length,1);assert.equal(f.store.snapshot({...viewer,username:'stranger'}).connections.length,0);await assert.rejects(f.store.saveConnection({platform:'meta'},editor),/permiso/);await assert.rejects(f.draft().then(d=>f.store.authorize({id:d.id},editor)),/permiso/);assert.ok(!JSON.stringify(f.store.snapshot(admin)).includes('META_TEST_TOKEN'));await assert.rejects(f.store.verify('another',admin),/autorizada/)});
test('currency, exact amounts and supported configuration validated before persistence',async t=>{const f=await fixture(t);for(const override of [{currency:'DOP'},{budget_minor:100.25},{budget_minor:'1.2'},{page_id:'act_333'},{destination:'http://example.com'},{objective:'OUTCOME_SALES'},{age_min:12}])await assert.rejects(f.store.saveDraft({connection_id:f.c.id,piece_id:'piece',config:{...baseConfig(),...override}},admin));assert.equal(f.store.data.drafts.length,0);assert.equal(sumDecimals(['0.10','0.20']),'0.30');assert.equal(sumDecimals(['9007199254740993','1']),'9007199254740994')});
test('piece identity and rights gate the exact approval; cross brand denied',async t=>{const f=await fixture(t),d=await f.draft();await assert.rejects(f.store.approve({id:d.id,hash:d.hash,note:'ok'},admin),/derechos/);await assert.rejects(f.store.authorize({id:d.id,hash:d.hash,confirmed:true,budget_minor:'12000',currency:'USD'},admin),/editorial/);f.setCapture({...d.snapshot,brand_id:'other'});await assert.rejects(f.store.saveDraft({connection_id:f.c.id,piece_id:'piece',config:baseConfig()},admin),/marca/)});
test('editing config preserves history and revokes both approvals; stale hash rejected',async t=>{const f=await fixture(t),d=structuredClone(await f.approved());const edited=await f.store.saveDraft({id:d.id,connection_id:f.c.id,piece_id:'piece',config:{...baseConfig(),destination:'https://example.com/new'}},editor);assert.equal(edited.editorial,null);assert.equal(edited.authorization,null);assert.equal(edited.history[0].hash,d.hash);await assert.rejects(f.store.authorize({id:d.id,hash:d.hash,confirmed:true,budget_minor:'12000',currency:'USD'},admin),/editorial/);assert.equal(f.calls.length,0)});
test('changing piece or connection after approval prevents remote calls',async t=>{const f=await fixture(t),d=await f.approved();f.setCapture({...d.snapshot,files:[{sha256:'b'.repeat(64)}]});await assert.rejects(execute(f,d),/pieza cambió/);assert.equal(f.calls.length,0)});
test('read-only server refuses every creation even after approval',async t=>{const f=await fixture(t,{allowWrites:false}),d=await f.approved();await assert.rejects(execute(f,d),/deshabilitadas/);assert.equal(f.calls.length,0)});
test('ten concurrent submissions produce one paused hierarchy; survive reload',async t=>{const f=await fixture(t),d=await f.approved();const result=await Promise.all(Array.from({length:10},()=>execute(f,d)));assert.equal(new Set(result.map(r=>r.id)).size,1);assert.deepEqual(f.calls,['media','campaign','adset','creative','ad']);assert.equal(result[0].status,'paused');assert.ok(Object.values(f.objects).every(o=>o.status==='PAUSED'));const restored=await new AdsStore(f.root,f.options).init();assert.equal(restored.data.operations[0].status,'paused');await execute(f,d);assert.equal(f.calls.length,5)});
test('timeout after provider creates object stops duplicates and reconciles exact ID',async t=>{const f=await fixture(t),d=await f.approved(),original=f.provider.create;let lost;f.provider.create=async(...args)=>{const r=await original(...args);if(args[0]==='adset'){lost=r.id;throw new AdsProviderError(0,null,true)}return r};await assert.rejects(execute(f,d));const op=f.store.data.operations[0];assert.equal(op.status,'uncertain');await assert.rejects(execute(f,d),/incierta/);assert.equal(f.calls.filter(x=>x==='adset').length,1);await assert.rejects(f.store.reconcile({operation_id:op.id,remote_id:op.ids.campaign},admin));await f.store.reconcile({operation_id:op.id,remote_id:lost},admin);f.provider.create=original;const done=await execute(f,d);assert.equal(done.status,'paused');assert.equal(f.calls.filter(x=>x==='adset').length,1)});
test('restart turns in-flight operation into uncertain, never auto-requeues',async t=>{const f=await fixture(t),d=await f.approved();f.store.data.operations.push({id:'interrupted',draft_id:d.id,hash:d.hash,connection_id:f.c.id,type:'create',ids:{},phase:'media',status:'working'});await f.store.save();const restored=await new AdsStore(f.root,f.options).init();assert.equal(restored.data.operations[0].status,'uncertain');await assert.rejects(restored.execute({id:d.id,hash:d.hash,confirmed:true},admin),/incierta/);assert.equal(f.calls.length,0)});
test('activation requires exact text, fresh authorization and unchanged remote payload',async t=>{const f=await fixture(t),d=await f.approved(),op=await execute(f,d);await assert.rejects(f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'yes'},admin),/Confirma/);f.objects[op.ids.adset].lifetime_budget='99999';await assert.rejects(f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'ACTIVAR 12000 USD'},admin),/diferente/);assert.equal(f.calls.filter(x=>x.startsWith('status')).length,0);f.objects[op.ids.adset].lifetime_budget='12000';await f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'ACTIVAR 12000 USD'},admin);assert.equal(f.store.data.operations[0].status,'active');await f.store.pause({operation_id:op.id},admin);assert.equal(f.store.data.operations[0].status,'stopped')});
test('partial activation becomes uncertain and can be safely paused',async t=>{const f=await fixture(t),d=await f.approved(),op=await execute(f,d),original=f.provider.setStatus;let count=0;f.provider.setStatus=async(...args)=>{if(++count===2)throw new AdsProviderError(0,null,true);return original(...args)};await assert.rejects(f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'ACTIVAR 12000 USD'},admin),/parcial/);assert.equal(f.store.data.operations[0].status,'uncertain');f.provider.setStatus=original;await f.store.pause({operation_id:op.id},admin);assert.equal(f.objects[op.ids.campaign].status,'PAUSED')});
test('daily reports upsert, preserve revisions, missing metrics and coverage',async t=>{const f=await fixture(t),input={connection_id:f.c.id,since:'2026-09-28',until:'2026-09-28'};await f.store.sync(input,admin);await f.store.sync(input,admin);assert.equal(f.store.data.metrics.length,1);assert.equal(f.store.data.metrics[0].values.reach,null);const original=f.provider.insights;f.provider.insights=async()=>{const r=await original();r.rows[0].spend='0.20';r.complete=false;return r};await f.store.sync(input,admin);assert.equal(f.store.data.metrics[0].revisions.length,1);assert.equal(f.store.data.metrics[0].coverage,'partial');assert.equal(f.store.data.syncs.at(-1).complete,false);assert.equal(f.store.data.metrics[0].draft_id,null)});
test('foreign account or currency report rejected atomically',async t=>{const f=await fixture(t),original=f.provider.insights;f.provider.insights=async()=>{const r=await original();r.rows.push({...r.rows[0],account_currency:'DOP'});return r};await assert.rejects(f.store.sync({connection_id:f.c.id,since:'2026-09-28',until:'2026-09-28'},admin),/Moneda/);assert.equal(f.store.data.metrics.length,0);assert.equal(f.store.data.syncs.length,0)});
test('metric totals separate currencies and attribution, retain exact decimals',()=>{const row={currency:'USD',timezone:'UTC',attribution:'unified',api_version:'v24.0',coverage:'complete',values:{spend:'0.10',impressions:'2',clicks:null}};const totals=metricTotals([row,{...row,values:{...row.values,spend:'0.20'}},{...row,currency:'DOP'},{...row,attribution:'other'}]);assert.equal(totals.length,3);assert.equal(totals[0].spend,'0.30');assert.equal(totals[0].clicks,null);assert.equal(totals[0].incomplete,true)});
test('provider read retries are bounded, secret errors redacted; writes never retried',async()=>{const secret='private-test-secret',seen=[];const t=new Transport({token:secret,sleep:async()=>{},fetchImpl:async(url,opt)=>{seen.push({url:String(url),method:opt.method});return new Response(JSON.stringify({error:{code:4,message:secret}}),{status:429})}});await assert.rejects(t.call('act_123'),e=>!e.message.includes(secret));assert.equal(seen.length,3);assert.ok(seen.every(r=>!r.url.includes(secret)));await assert.rejects(t.call('act_123',{},'POST'),/solo lectura/);assert.equal(seen.length,3);t.writable=true;await assert.rejects(t.call('act_123/campaigns',{},'POST'));assert.equal(seen.length,4)});
test('pagination does not follow provider URLs or leak access_token',async()=>{let calls=0;const t=new Transport({token:'private-test-secret',fetchImpl:async(url)=>{assert.equal(url.hostname,'graph.facebook.com');assert.equal(url.searchParams.has('access_token'),false);return Response.json(++calls===1?{data:[{id:'1'}],paging:{next:'https://evil.example/?access_token=secret',cursors:{after:'cursor'}}}:{data:[{id:'2'}]})}});const out=await t.pages('act_123/campaigns');assert.equal(out.rows.length,2);assert.equal(out.complete,true);assert.equal(calls,2)});
test('official SDK object reads use injected GET-only transport, no telemetry, cursor safe',async()=>{let calls=0;const before=process.listenerCount('uncaughtException');const p=new MetaAds({token:'private-test-secret',account_id:'act_123',fetchImpl:async(url,opt)=>{assert.equal(opt.method,'GET');assert.equal(url.host,'graph.facebook.com');assert.equal(url.searchParams.has('access_token'),false);return Response.json(++calls===1?{data:[{id:'1',name:'one'}],paging:{next:'https://evil.example',cursors:{after:'abc'}}}:{data:[{id:'2',name:'two'}]})}});assert.equal(process.listenerCount('uncaughtException'),before);const r=await p.campaigns();assert.deepEqual(r.rows.map(x=>x.id),['1','2']);assert.equal(r.complete,true);assert.equal(calls,2)});
test('TikTok ads report uses official GET endpoint and credential header, no publication API',async()=>{const p=new TikTokAds({account_id:'123',token:'private-test-secret',fetchImpl:async(url,options)=>{assert.equal(options.method,'GET');assert.equal(url.pathname,'/open_api/v1.3/report/integrated/get/');assert.equal(options.headers['Access-Token'],'private-test-secret');return Response.json({code:0,data:{list:[{dimensions:{ad_id:'1',stat_time_day:'2026-09-28'},metrics:{spend:'1.20'}}],page_info:{total_page:1}}})}});const r=await p.insights('2026-09-28','2026-09-28');assert.equal(r.complete,true);assert.equal(r.rows[0].ad_id,'1')});
test('route dispatch cannot bypass write restrictions or service permissions',async t=>{const f=await fixture(t,{allowWrites:false});await assert.rejects(adsRoute(f.store,{path:'/connections',method:'POST',input:{},actor:viewer}),/permiso/);await assert.rejects(adsRoute(f.store,{path:'/activate',method:'POST',input:{},actor:admin}),/deshabilitadas/);await assert.rejects(adsRoute(f.store,{path:'/unknown',method:'POST',input:{},actor:admin}),/no encontrada/)});
test('n8n sync is bounded to read actions and complete days in account timezone',async()=>{const {syncAds}=await import('./deploy/ads-sync.cjs'),seen=[];const result=await syncAds({base:'https://studio.example/api/v1/ads',token:'test-only-token',now:new Date('2026-10-02T01:00:00Z'),fetchImpl:async(url,options)=>{seen.push({url,body:options.body?JSON.parse(options.body):null});if(url.endsWith('/sync'))return Response.json({id:'sync',complete:true});return Response.json({connections:[{id:'c',metadata:{timezone:'America/Santo_Domingo'}}]})}});assert.equal(result.writes,false);assert.equal(seen.at(-1).body.until,'2026-09-30');assert.equal(seen.at(-1).body.since,'2026-09-24');assert.ok(seen.every(x=>!/(execute|activate|authorize|drafts)/.test(x.url)))});
test('n8n no configured accounts is idle, does not invoke provider',async()=>{const {syncAds}=await import('./deploy/ads-sync.cjs');let calls=0;const r=await syncAds({base:'https://studio.example/api/v1/ads',token:'test',fetchImpl:async()=>{calls++;return Response.json({connections:[]})}});assert.equal(calls,1);assert.equal(r.status,'idle')});
test('remote targeting change is rejected before activation',async t=>{const f=await fixture(t),d=await f.approved(),op=await execute(f,d);f.objects[op.ids.adset].targeting.interests=[{id:'9'}];await assert.rejects(f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'ACTIVAR 12000 USD'},admin),/diferente/);assert.equal(f.calls.filter(x=>x.startsWith('status')).length,0)});
test('account identity cannot be changed in place after drafts use it',async t=>{const f=await fixture(t);await f.approved();await assert.rejects(f.store.saveConnection({id:f.c.id,platform:'meta',account_id:'act_456',brand_id:'comandpos',credential_ref:'OTHER_TOKEN'},admin),/inmutable/)});
test('scheduler may read opted-in connections only and cannot inherit writer scopes',async t=>{const f=await fixture(t),principal={username:'n8n-ads',role:'integration',scopes:['ads.read','ads.sync'],ad_connections:[],automated_ads_sync:true};assert.equal(f.store.snapshot(principal).connections.length,0);f.store.data.connections[0].auto_sync=true;assert.equal(f.store.snapshot(principal).connections.length,1);assert.equal(f.store.snapshot({...principal,scopes:[...principal.scopes,'ads.activate']}).connections.length,0);await assert.rejects(f.store.authorize({},principal),/permiso/)});
test('activation cannot pair an old operation with a different draft version',async t=>{const f=await fixture(t),d=await f.approved(),op=await execute(f,d);f.store.data.operations[0].hash='0'.repeat(64);await assert.rejects(f.store.activate({operation_id:op.id,hash:d.hash,confirmation:'ACTIVAR 12000 USD'},admin),/otra versión/);assert.equal(f.calls.filter(x=>x.startsWith('status')).length,0)});
test('confirmed provider validation failure is recoverable without resending successful phases',async t=>{const f=await fixture(t),d=await f.approved(),original=f.provider.create;f.provider.create=async(...args)=>{if(args[0]==='adset')throw new AdsProviderError(400,100,false);return original(...args)};await assert.rejects(execute(f,d));assert.equal(f.store.data.operations[0].status,'failed');f.provider.create=original;assert.equal((await execute(f,d)).status,'paused');assert.equal(f.calls.filter(x=>x==='campaign').length,1)});
test('complete reimport retires obsolete rows and attribution versions without losing ledger; partial preserves prior rows',async t=>{const f=await fixture(t),q={connection_id:f.c.id,since:'2026-09-28',until:'2026-09-28'};await f.store.sync(q,admin);f.provider.insights=async()=>({rows:[],complete:false});await f.store.sync(q,admin);assert.equal(f.store.data.metrics.length,1);f.provider.insights=async()=>({rows:[],complete:true});await f.store.sync(q,admin);assert.equal(f.store.data.metrics.length,0);assert.equal(f.store.data.syncs.at(-1).superseded_metrics.length,1);assert.equal(f.store.data.syncs.at(-1).superseded_metrics[0].values.spend,'0.10')});
