import {qualityDecision} from './content-policy.mjs';
import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
export const dayInRD=now=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santo_Domingo'}).format(new Date(now));
const stamp=(day,time)=>new Date(day+'T'+time+':00-04:00').toISOString();
export function calendar(day,{holidays=[]}={}){
 if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||new Date(day+'T12:00:00Z').toISOString().slice(0,10)!==day)throw Error('Fecha inválida');
 const weekday=new Date(day+'T12:00:00Z').getUTCDay(),video={key:'video',kind:'video',production_at:stamp(day,weekday===1?'06:00':'09:00'),targets:[{channel:'facebook',at:stamp(day,'19:30')},{channel:'tiktok',at:stamp(day,'19:30')}]},out=[video];
 let feed={1:['video','08:00'],2:['imagen','15:00'],3:['imagen','08:00'],4:['imagen','19:00'],5:['carrusel','12:00'],6:['imagen','10:00']}[weekday];if(feed&&holidays.some(h=>h.date===day))feed=['imagen',feed[1]];
 if(feed){if(feed[0]==='video')video.targets.unshift({channel:'instagram',at:stamp(day,feed[1])});else out.push({key:'feed',kind:feed[0],production_at:stamp(day,'06:00'),targets:['instagram','facebook','tiktok'].map(channel=>({channel,at:stamp(day,feed[1])}))})}
 for(const hour of [13,18])out.push({key:'story-'+hour,hour,kind:'historia_social',production_at:stamp(day,hour===13?'09:00':'14:00'),targets:['instagram','facebook'].map(channel=>({channel,at:stamp(day,hour+':00')}))});
 return out.map(s=>({...s,date:day,id:day+':'+s.key,request_key:s.key==='video'?'studio-daily:'+day+':comandpos':'studio-calendar:'+day+':'+s.key,deadline:s.targets.map(t=>t.at).sort().at(-1)}));
}
const userError=e=>!e?null:/Revisión de voz pendiente|pronunciación del nombre/.test(e)?'Revisa la frase de voz en esta página; después recupera el trabajo con recursos guardados.':/Falta audio|Falta voz guardada/.test(e)?'Falta una voz en caché. Abre el proyecto y autoriza la generación solo si necesitas completarla.':String(e).startsWith('Render falló')?'La producción se detuvo. Abre el trabajo para consultar el detalle.':String(e).slice(0,400);
export class Automation{
 constructor(root,{marketing,store,produce,editorial=null,clock=()=>new Date()}={}){Object.assign(this,{root,marketing,store,produce,editorial,clock});this.dir=join(root,'.studio-state/automation');this.serial=Promise.resolve();this.running=null}
 async init(){await mkdir(this.dir,{recursive:true});try{this.data=JSON.parse(await readFile(join(this.dir,'state.json')))}catch(e){if(e.code!=='ENOENT')throw e;this.data={config:{enabled:false,brand_id:'comandpos',campaign_id:null,start_date:dayInRD(this.clock()),timezone:'America/Santo_Domingo'},slots:[]}}for(const s of this.data.slots)if(s.status==='requesting')s.status='interrupted';return this}
 async save(){const temp=join(this.dir,randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(this.data),{mode:0o600});await rename(temp,join(this.dir,'state.json'))}
 exclusive(fn){const p=this.serial.then(fn);this.serial=p.catch(()=>{});return p}
 configure(d,actor){return this.exclusive(async()=>{if(d.publication_mode!=null&&!['manual','automatic'].includes(d.publication_mode))throw Error('Modo de publicación inválido');if(typeof d.enabled!=='boolean')throw Error('Indica si activas el calendario');const c=this.marketing.data.campaigns.find(c=>c.id===d.campaign_id&&c.brand_id==='comandpos');if(!c)throw Error('Selecciona una campaña de ComandPOS');calendar(d.start_date||this.data.config.start_date);if(this.data.slots.length&&this.data.config.campaign_id!==c.id)throw Error('El calendario con historial conserva su campaña');if(d.activate_campaign===true)await this.marketing.saveCampaign({...c,status:'active'},actor);const mode=d.publication_mode||this.data.config.publication_mode||'manual';const authorization=mode==='automatic'?(this.data.config.publication_mode==='automatic'?this.data.config.publication_authorization:{actor,at:new Date(this.clock()).toISOString(),version:1}):null;this.data.config={...this.data.config,publication_mode:mode,publication_authorization:authorization,enabled:d.enabled,campaign_id:c.id,start_date:d.start_date||this.data.config.start_date,updated_by:actor,updated_at:new Date(this.clock()).toISOString()};await this.save();return this.snapshot()})}
 snapshot(){const today=dayInRD(this.clock());return {...structuredClone(this.data),running:!!this.running,plans:Array.from({length:7},(_,i)=>calendar(new Date(Date.parse(today+'T12:00:00Z')+i*86400000).toISOString().slice(0,10),{holidays:this.data.holiday_days||[]})).flat(),slots:this.data.slots.map(s=>{const j=s.job_id?this.store.get(s.job_id):null;return {...structuredClone(s),error:userError(s.error),job:j?{id:j.id,status:j.status,error:userError(j.error),review:j.review,name:j.name}:null,pieces:this.marketing.data.pieces.filter(p=>p.automation_slot===s.id).map(p=>({id:p.id,channel:p.channel,scheduled_at:p.scheduled_at,job_id:p.job_id,deliveries:this.marketing.data.deliveries.filter(d=>d.piece_id===p.id).map(({status,url})=>({status,url}))}))}})}}
 kick({generate=true}={}){if(this.running)return {started:false,running:true};this.running=this.exclusive(()=>this.cycle(generate)).catch(async e=>{this.data.last_error=e.message;await this.save()}).finally(()=>{this.running=null});return {started:true,running:true}}
 async cycle(generate){const now=new Date(this.clock()),today=dayInRD(now),cfg=this.data.config;this.data.last_tick=now.toISOString();delete this.data.last_error;
 if(!cfg.enabled){await this.save();return}const campaign=this.marketing.data.campaigns.find(c=>c.id===cfg.campaign_id);if(campaign?.status!=='active'){this.data.last_error='La campaña está pausada o no está activa';await this.save();return}
 if(this.editorial){const h=await this.editorial.holidays(today.slice(0,4));this.data.holiday_days=h.days;this.data.holiday_warning=h.warning||null}
 if(today>=cfg.start_date)for(const plan of calendar(today,{holidays:this.data.holiday_days||[]})){if(plan.production_at>now.toISOString())continue;if(plan.key==='feed'&&this.data.slots.some(s=>s.date===today&&s.key==='video'&&s.targets.some(t=>t.channel==='instagram')))continue;let s=this.data.slots.find(s=>s.id===plan.id);if(!s){s={...plan,status:'pending'};this.data.slots.push(s);await this.save()}
 if(!s.job_id){const creativeId=createHash('sha256').update(s.request_key).digest('hex');const found=this.store.list().filter(j=>j.creative_id===creativeId&&j.brand_id===cfg.brand_id&&j.campaign_id===cfg.campaign_id&&j.kind===s.kind).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];if(found){s.job_id=found.id;s.status='adopted';await this.save()}}
 if(s.job_id){try{await this.prepare(s)}catch(e){s.status='needs_attention';s.prepare_error=e.message;await this.save()}continue}
 if(s.deadline<=now.toISOString()){s.status='missed';s.error='Pasó la ventana; no se genera ni publica contenido atrasado automáticamente';await this.save();continue}
 if(!generate||!['pending','interrupted','waiting_resources'].includes(s.status))continue;
 s.status='requesting';await this.save();try{if(this.editorial&&!s.editorial){s.editorial=await this.editorial.plan(s,this.data.slots,this.marketing.data);if(s.editorial.holiday&&s.key==='feed')s.kind='imagen';await this.save()}const result=await this.produce({...(s.editorial?{editorial:s.editorial}:{}),brand_id:cfg.brand_id,campaign_id:cfg.campaign_id,auto:true,kind:s.kind,style:'auto',allow_paid:true,allow_paid_voice:true,produce:true,aspect:'vertical'},s.request_key,'automation');s.job_id=result.job.id;s.status='producing';delete s.error;await this.save();await this.prepare(s)}catch(e){s.status=e.code==='WAITING_RESOURCE'?'waiting_resources':'needs_attention';s.error=e.message;if(e.resource_id)s.resource_id=e.resource_id;await this.save()}
 }
 // Reconcile all prepared days. Approval and scheduling are independent of generation.
 for(const s of this.data.slots){if(!s.job_id)continue;let j=this.store.get(s.job_id);if(s.prepare_error){s.status='needs_attention';s.error=s.prepare_error;continue}s.status=j.status==='succeeded'?'awaiting_approval':['failed','interrupted','cancelled'].includes(j.status)?'needs_attention':'producing';s.error=j.error||null;for(const p of this.marketing.data.pieces.filter(p=>p.automation_slot===s.id)){const delivery=this.marketing.data.deliveries.find(d=>d.piece_id===p.id&&!['cancelled','failed'].includes(d.status));if(delivery)continue;if(cfg.publication_mode==='automatic'&&this.marketing.data.deliveries.some(d=>d.piece_id===p.id))continue;if(!p.scheduled_at||p.scheduled_at<=now.toISOString()){s.notice='Hay destinos vencidos: revisa y elige una nueva fecha; no se publican tarde automáticamente';continue}if(cfg.publication_mode==='automatic'&&j.status==='succeeded'){try{await this.authorizeAutomatic(s,p,j);j=this.store.get(s.job_id)}catch(e){s.error=e.message;continue}}if(j.status!=='succeeded'||j.review.status!=='approved')continue;try{this.marketing.approvedRelease(p.id,this.store)}catch{continue}try{await this.marketing.schedule({piece_id:p.id},'automation-approved',this.store)}catch(e){s.error=e.message}}const pieces=this.marketing.data.pieces.filter(p=>p.automation_slot===s.id),deliveries=pieces.map(p=>this.marketing.data.deliveries.find(d=>d.piece_id===p.id&&!['cancelled','failed'].includes(d.status)));if(pieces.length&&deliveries.every(d=>d?.status==='published'))s.status='published';else if(deliveries.some(d=>['uncertain','blocked','missed'].includes(d?.status)))s.status='delivery_attention';else if(pieces.length&&deliveries.every(d=>['scheduled','claimed','published'].includes(d?.status)))s.status='scheduled';else if(j.status==='succeeded'&&pieces.some(p=>p.scheduled_at<=now.toISOString()&&!this.marketing.data.deliveries.some(d=>d.piece_id===p.id&&!['cancelled','failed'].includes(d.status))))s.status='missed_approval';}
 for(const s of this.data.slots)if(cfg.publication_mode==='automatic'&&s.error&&s.status==='awaiting_approval')s.status='needs_attention';
 await this.save();
 }
 async authorizeAutomatic(slot,piece,job){
 const cfg=this.data.config;if(cfg.publication_mode!=='automatic'||!cfg.publication_authorization)throw Error('Falta autorización de publicación automática');
 if(!['video','feed','story-13','story-18'].includes(slot.key)||piece.automation_slot!==slot.id||piece.job_id!==slot.job_id||piece.brand_id!==cfg.brand_id||piece.campaign_id!==cfg.campaign_id||job.campaign_id!==cfg.campaign_id||job.brand_id!==cfg.brand_id||job.kind!==slot.kind)throw Error('Pieza fuera del calendario autorizado');
 const target=slot.targets.find(t=>t.channel===piece.channel);if(!target||piece.scheduled_at!==target.at||piece.caption!==(job.caption||job.artifact?.caption||'')||piece.account_key!==this.marketing.data.accounts.find(a=>a.channel===piece.channel)?.key)throw Error('La pieza fue modificada: revisar antes de publicar');
 if(job.review?.status==='rejected'||job.options?.preview||!qualityDecision(job).allowed||this.marketing.data.comments.some(c=>c.job_id===job.id&&!c.resolved))throw Error('La pieza tiene un rechazo, vista previa o control pendiente');
 const actor='automation-policy-v1';if(job.review?.status!=='approved')await this.store.review(job.id,'approved',actor,'Publicación automática autorizada por el propietario; controles de producción superados. No es revisión humana.');
 const preview=this.marketing.releasePreview(piece.id,this.store);return this.marketing.approveRelease({piece_id:piece.id,hash:preview.hash,acknowledge_warnings:true,note:'Autorización por política del calendario. Advertencias registradas; no representan verificación humana de afirmaciones.'},actor,this.store);
 }
 async prepare(s){await this.marketing.prepareAutomaticPieces(s,this.data.config,this.store);s.prepared=true;delete s.prepare_error;await this.save()}
 async approvePublication(input,actor){const release=await this.marketing.approveRelease(input,actor,this.store),p=this.marketing.data.pieces.find(p=>p.id===input.piece_id);if(!this.data.config.enabled||!p?.automation_slot||p.campaign_id!==this.data.config.campaign_id)return release;try{if(!p.scheduled_at||p.scheduled_at<=new Date(this.clock()).toISOString())throw Error('Fecha vencida: elige una nueva fecha y revisa de nuevo');const delivery=await this.marketing.schedule({piece_id:p.id},actor,this.store);return {...release,delivery}}catch(e){return {...release,scheduling_error:e.message}}}
 resume(id){return this.exclusive(async()=>{const s=this.data.slots.find(s=>s.id===id);if(!s||s.job_id||!['needs_attention','interrupted'].includes(s.status))throw Error('Esta solicitud no requiere reconsulta');if(s.date!==dayInRD(this.clock())||s.deadline<=new Date(this.clock()).toISOString())throw Error('La fecha venció; prepara otra pieza y revisa su nueva fecha');s.status='interrupted';await this.save();return this.kick({generate:true})})}
 recover(id,{allowPaid=false}={}){return this.exclusive(async()=>{const s=this.data.slots.find(s=>s.id===id);if(!s?.job_id)throw Error('No hay un trabajo que recuperar');const j=this.store.get(s.job_id);if(!['failed','interrupted','cancelled'].includes(j.status))throw Error('El trabajo no necesita recuperación');if(this.marketing.data.pieces.some(p=>p.automation_slot===id&&this.marketing.data.deliveries.some(d=>d.piece_id===p.id&&!['cancelled','failed'].includes(d.status))))throw Error('Hay una entrega existente: revisa su estado antes de recuperar');const result=await this.store.retry(j.id,(allowPaid?'automation-complete:':'automation-cache:')+j.id,{cacheOnly:!allowPaid,allowPaid});s.job_id=result.job.id;s.status='producing';delete s.error;await this.save();await this.prepare(s);return result})}
}
