import {mkdir,readFile,readdir,writeFile,rename} from 'node:fs/promises';import {join} from 'node:path';import {createHash,randomUUID} from 'node:crypto';
export function batchProgress(children){const counts={ready:0,failed:0,active:0,pending:0,approved:0};for(const c of children){const status=c.job?.status||c.status;if(status==='succeeded'){counts.ready++;if(c.job.review?.status==='approved')counts.approved++}else if(['failed','interrupted','cancelled','needs_review'].includes(status))counts.failed++;else if(['running','queued','generating'].includes(status))counts.active++;else counts.pending++}const state=counts.failed?'needs_attention':counts.active||counts.pending?'producing':counts.approved===children.length?'approved':'ready_for_review';return {state,counts,label:({needs_attention:'Requiere atención',producing:'En producción',approved:'Archivos aprobados',ready_for_review:'Listo para revisar'})[state]}}
export const batchQuote={currency:'USD',maximum:2.4,script_reserves:.4,video_maximum:2,note:'Techo de reservas; el coste real requiere conciliación. Cuatro piezas, una con voz.'};
export class Batches{
 constructor(root,{produce,budget,store,linkJob=async()=>{}}){this.dir=join(root,'.studio-state','batches');Object.assign(this,{produce,budget,store,linkJob});this.items=new Map();this.active=new Set();this.running=new Map();this.serial=Promise.resolve()}
 async init(){await mkdir(this.dir,{recursive:true});for(const f of await readdir(this.dir)){if(!/^[a-f0-9]{64}\.json$/.test(f))continue;const b=JSON.parse(await readFile(join(this.dir,f),'utf8'));if(['queued','running'].includes(b.status)){b.status='interrupted';await this.save(b)}this.items.set(b.id,b)}return this}
 async save(b){const p=join(this.dir,b.id+'.json'),tmp=p+'.'+randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(b),{mode:0o600});await rename(tmp,p)}
 list(){return [...this.items.values()].map(b=>{const children=b.children.map(c=>({...c,job:c.job_id?this.store.get(c.job_id):null}));return {...structuredClone(b),children,progress:batchProgress(children)}})}
 start(input,key,actor){const work=this.serial.then(async()=>{if(input.allow_paid!==true||input.max_budget_usd!==batchQuote.maximum)throw Error('Confirma el techo del lote de US$2.40');if(!/^[\w:-]{1,140}$/.test(key||''))throw Error('Clave de lote inválida');if(!Array.isArray(input.pieces)||input.pieces.length!==4)throw Error('El lote necesita cuatro briefs');const id=createHash('sha256').update(key).digest('hex'),fingerprint=createHash('sha256').update(JSON.stringify({allow_paid:input.allow_paid,max_budget_usd:input.max_budget_usd,pieces:input.pieces.map(({id,brief,kind,brand_id,campaign_id,concept_id})=>({id,brief,kind,brand_id,campaign_id,concept_id}))})).digest('hex'),old=this.items.get(id);if(old){if(old.fingerprint!==fingerprint)throw Error('Clave de lote usada con otro contenido');return structuredClone(old)}const same=[...this.items.values()].find(b=>b.fingerprint===fingerprint);if(same)return structuredClone(same);await this.budget.group(id,batchQuote.maximum);const b={id,fingerprint,actor,at:new Date().toISOString(),status:'queued',quote:batchQuote,children:input.pieces.map(p=>({piece_id:p.id,kind:p.kind,input:{brand_id:p.brand_id,campaign_id:p.campaign_id,concept_id:p.concept_id,piece_id:p.id,kind:p.kind,idea:p.brief,style:'tutorial',produce:true,allow_paid:true,allow_paid_voice:true,budget_group:id,aspect:'vertical'},status:'pending'}))};this.items.set(id,b);await this.save(b);this.launch(id).catch(()=>{});return structuredClone(b)});this.serial=work.catch(()=>{});return work}
 launch(id){if(this.running.has(id))return this.running.get(id);const promise=this.run(id).finally(()=>this.running.delete(id));this.running.set(id,promise);return promise}
 async run(id){if(this.active.has(id))return;const b=this.items.get(id);if(!b||b.cancel_requested)return;this.active.add(id);b.status='running';try{await this.save(b);for(const [i,c]of b.children.entries()){if(b.cancel_requested)break;if(c.job_id)continue;c.status='generating';await this.save(b);try{const result=await this.produce(c.input,'batch:'+id+':'+i,b.actor);c.job_id=result.job.id;c.status='queued';if(b.cancel_requested&&['running','queued'].includes(this.store.get(c.job_id).status))await this.store.cancel(c.job_id,b.actor);delete c.error}catch(e){c.status='needs_review';c.error=e.message;b.status='needs_review';await this.save(b);return}await this.save(b)}b.status=b.cancel_requested?'cancelled':'submitted';await this.save(b)}finally{this.active.delete(id)}}
 async resume(id){await this.running.get(id);const b=this.items.get(id);if(!b||!['interrupted','needs_review'].includes(b.status))throw Error('Lote no reanudable');this.launch(id).catch(()=>{});return structuredClone(b)}
 async retryChild(id,pieceId,actor){const work=this.serial.then(async()=>{const b=this.items.get(id),c=b?.children.find(c=>c.piece_id===pieceId);if(!c?.job_id)throw Error('Trabajo del lote no encontrado');const old=c.job_id,current=this.store.get(old);if(!['failed','interrupted','cancelled'].includes(current.status))return structuredClone(b);const result=await this.store.retry(old,'batch-retry:'+id+':'+old);await this.linkJob(pieceId,result.job.id,actor);c.job_id=result.job.id;c.status='queued';c.previous_jobs=[...(c.previous_jobs||[]),old];b.status='submitted';await this.save(b);return structuredClone(b)});this.serial=work.catch(()=>{});return work}
 async cancel(id,actor){const b=this.items.get(id);if(!b)throw Error('Lote no encontrado');b.cancel_requested=true;b.status='cancelled';b.cancelled_by=actor;await this.save(b);for(const c of b.children)if(c.job_id&&['queued','running'].includes(this.store.get(c.job_id).status))await this.store.cancel(c.job_id,actor);return structuredClone(b)}
}
