import {validateEditorial,prepareEditorial,executeEditorialStory} from './editorial-render.mjs'
import {resolveDesign,validateTemplate} from './design.mjs'
import './fontconfig.mjs'
import sharp from 'sharp'
import {readFile,writeFile,copyFile} from 'node:fs/promises'
import {join} from 'node:path'
import {createHash} from 'node:crypto'
const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validateBrandFeed(s,kind){validateEditorial(s);validateTemplate(s);if(!/^[a-z0-9][a-z0-9-]{0,79}$/.test(s.nombre||'')||s.tipo!==kind||!['imagen','carrusel','historia_social'].includes(kind)||!/^([a-z0-9-]{2,40})$/.test(s.brand_id||''))throw Error('Pieza de marca inválida');for(const [k,max]of[['titular',80],['subtitulo',150],['caption',2200],['cta',60]])if(typeof s[k]!=='string'||!s[k].trim()||s[k].length>max)throw Error('Revisa '+k);if(s.resource_id&&!/^[a-f0-9-]{36}$/.test(s.resource_id))throw Error('Foto inválida');if(!Array.isArray(s.slides)||(kind==='carrusel'?(s.slides.length<2||s.slides.length>8):s.slides.length!==0))throw Error('El carrusel requiere entre dos y ocho páginas');for(const p of s.slides)if(typeof p.titulo!=='string'||!p.titulo.trim()||p.titulo.length>80||typeof p.texto!=='string'||p.texto.length>180)throw Error('Página inválida');if(new Set(s.slides.filter(p=>p.id).map(p=>p.id)).size!==s.slides.filter(p=>p.id).length)throw Error('IDs de página repetidos');for(const p of s.slides){if(p.id&&!/^[a-zA-Z0-9-]{1,80}$/.test(p.id))throw Error('ID de página inválido');if(p.resource_id&&!/^[a-f0-9-]{36}$/.test(p.resource_id))throw Error('Foto de página inválida')}return structuredClone(s)}
export async function prepareBrandFeed(s,dir,root){await prepareEditorial(s,dir,root);const data=JSON.parse(await readFile(join(root,'.studio-state/marketing/state.json'),'utf8'));const brand=data.brands.find(b=>b.id===s.brand_id);if(!brand)throw Error('Marca no encontrada');await writeFile(join(dir,'brand-profile.json'),JSON.stringify(brand));for(const [i,p]of(s.slides||[]).entries())if(p.resource_id){const a=data.assets.find(a=>a.id===p.resource_id&&a.brand_id===s.brand_id&&a.type==='image');if(!a||a.expires_at&&Date.parse(a.expires_at)<=Date.now())throw Error('Foto de página no disponible');await copyFile(join(root,'.studio-state/marketing/assets',a.filename),join(dir,'brand-photo-'+i))}if(brand.logo_resource_id){const logo=data.assets.find(a=>a.id===brand.logo_resource_id&&a.brand_id===brand.id&&a.type==='image');if(!logo)throw Error('Logo no disponible');await copyFile(join(root,'.studio-state/marketing/assets',logo.filename),join(dir,'brand-logo'))}if(s.resource_id){const a=data.assets.find(a=>a.id===s.resource_id&&a.brand_id===s.brand_id&&a.type==='image');if(!a)throw Error('Foto no disponible para esta marca');await copyFile(join(root,'.studio-state/marketing/assets',a.filename),join(dir,'brand-photo'))}}
function lines(text,max){const out=[];for(const w of text.split(/\s+/)){if(out.length&&(out.at(-1)+' '+w).length<=max)out[out.length-1]+=' '+w;else out.push(w)}return out}
export async function executeBrandFeed(job,dir){const raw=JSON.parse(await readFile(join(dir,'script.json'),'utf8'));if(raw.editorial?.story)return executeEditorialStory(validateBrandFeed(raw,job.kind),dir);const s=validateBrandFeed(JSON.parse(await readFile(join(dir,'script.json'),'utf8')),job.kind),b=JSON.parse(await readFile(join(dir,'brand-profile.json'),'utf8')),h=s.tipo==='historia_social'?1920:1350,design=resolveDesign(b,1080,h,s.template?.params),font=design.font,images=[],pages=s.tipo==='carrusel'?s.slides:[{titulo:s.titular,texto:s.subtitulo}];let photo='',logo='';if(b.logo_resource_id){const bytes=await sharp(await readFile(join(dir,'brand-logo'))).resize(350,90,{fit:'inside'}).png().toBuffer();logo=`<rect x="60" y="105" width="800" height="65" fill="${escape(b.primary)}"/><image href="data:image/png;base64,${bytes.toString('base64')}" x="80" y="110" width="350" height="60" preserveAspectRatio="xMinYMid meet"/>`}if(s.resource_id){const bytes=await sharp(await readFile(join(dir,'brand-photo'))).resize(920,420,{fit:'cover'}).jpeg({quality:94}).toBuffer();photo=`<image href="data:image/jpeg;base64,${bytes.toString('base64')}" x="80" y="580" width="920" height="420"/>`}
const defaultPhoto=photo;for(const [i,p]of pages.entries()){photo=defaultPhoto;if(p.resource_id){const bytes=await sharp(await readFile(join(dir,'brand-photo-'+i))).resize(920,420,{fit:'cover'}).jpeg({quality:94}).toBuffer();photo=`<image href="data:image/jpeg;base64,${bytes.toString('base64')}" x="80" y="580" width="920" height="420"/>`}const title=lines(p.titulo,22),body=lines(p.texto,43);if(title.length>4||body.length>5)throw Error('Acorta el texto para que se lea completo');for(const [text,size]of [...title.map(l=>[l,66]),...body.map(l=>[l,photo?29:36]),[s.cta,30],[b.name,30],[b.contact||b.website||'',22]]){if(!text)continue;const m=await sharp({text:{text:escape(text),font:font+' Bold '+size,rgba:true}}).metadata();if(m.width>920)throw Error('Texto demasiado ancho: '+text.slice(0,45))}const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${h}"><rect width="1080" height="${h}" fill="${escape(b.primary)}"/><rect x="80" y="90" width="80" height="8" fill="${escape(b.accent)}"/><text x="80" y="155" fill="white" font-family="${font}" font-size="30" font-weight="700">${escape(b.name)}</text>${logo}${title.map((l,n)=>`<text x="80" y="${270+n*76}" fill="white" font-family="${font}" font-size="66" font-weight="900">${escape(l)}</text>`).join('')}${photo}${body.map((l,n)=>`<text x="80" y="${photo?1045+n*38:650+n*48}" fill="white" font-family="${font}" font-size="${photo?29:36}">${escape(l)}</text>`).join('')}<rect x="80" y="${h-200}" width="920" height="5" fill="${escape(b.accent)}"/><text x="80" y="${h-135}" fill="white" font-family="${font}" font-size="30" font-weight="700">${escape(s.cta)}</text><text x="80" y="${h-85}" fill="white" font-family="${font}" font-size="22">${escape(b.contact||b.website)}</text><text x="1000" y="${h-85}" text-anchor="end" fill="white" font-family="${font}" font-size="22">${i+1}/${pages.length}</text></svg>`;
// Reserve readable body and footer space when a photo is present.
if(photo&&h===1350&&body.length>3)throw Error('Con foto, usa un subtítulo de hasta tres líneas o el formato Historia');
const styled=design.family==='paper'?svg.replaceAll('fill="white"','fill="'+escape(b.primary)+'"').replace('<rect width="1080" height="'+h+'" fill="'+escape(b.primary)+'"','<rect width="1080" height="'+h+'" fill="#f7f1e5"'):svg;
const marginTop=design.modern?design.top:0,scale=design.modern?(h-design.top-design.bottom)/h:1;const themed=design.modern?styled.replace(/(<svg[^>]*>)/,'$1<rect width="1080" height="'+h+'" fill="'+escape(b.primary)+'"/><g transform="translate('+(1080-1080*scale)/2+','+marginTop+') scale('+scale+')">').replace('</svg>','</g></svg>'):styled;const bytes=await sharp(Buffer.from(themed)).jpeg({quality:94}).toBuffer(),filename='pagina-'+(i+1)+'.jpg';await writeFile(join(dir,'artifacts',filename),bytes);images.push({index:i+1,filename,width:1080,height:h,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')})}
await writeFile(join(dir,'artifacts/manifest.json'),JSON.stringify({guion:s,brand:b,images,caption:s.caption,review:'pending'}));return {manifest_filename:'manifest.json',images,width:1080,height:h,caption:s.caption,content_type:'image/jpeg'}}
