import {readFile,writeFile,mkdir,open,unlink,rename} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID} from 'node:crypto'
export class Budget{
 constructor(state,{daily=Number(process.env.STUDIO_DAILY_BUDGET||5)}={}){this.state=state;this.daily=daily}
 async transact(fn){await mkdir(this.state,{recursive:true});const lock=join(this.state,'budget.lock');let h;for(let i=0;i<100;i++){try{h=await open(lock,'wx');break}catch(e){if(e.code!=='EEXIST')throw e;await new Promise(r=>setTimeout(r,50))}}if(!h)throw Error('Presupuesto ocupado; revisar el bloqueo antes de reintentar');try{let data;try{data=JSON.parse(await readFile(join(this.state,'budget.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;data={entries:[]}}const result=await fn(data);const temp=join(this.state,'budget.'+randomUUID()+'.tmp');await writeFile(temp,JSON.stringify(data),{mode:0o600});await rename(temp,join(this.state,'budget.json'));return result}finally{await h.close();await unlink(lock)}}
 async reserve(id,amount,category,job=null,maxJob=2){if(!Number.isFinite(amount)||amount<=0)throw Error('Reserva de presupuesto inválida');return this.transact(data=>{const prior=data.entries.find(e=>e.id===id);if(prior)return prior;const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'}),daily=data.entries.filter(e=>e.day===day).reduce((n,e)=>n+e.reserved,0),perJob=job?data.entries.filter(e=>e.job===job).reduce((n,e)=>n+e.reserved,0):0;if(daily+amount>this.daily+.000001||perJob+amount>maxJob+.000001)throw Error('Límite de presupuesto reservado alcanzado');const e={id,day,at:new Date().toISOString(),category,job,reserved:amount,state:'reserved'};data.entries.push(e);return e})}
 async usage(id,usage){return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(e){e.state='completed';e.usage=usage}return e})}
 async attach(id,job){return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(e&&!e.job)e.job=job;return e||null})}
 async reconcile(id,cost,receipt,actor){if(!Number.isFinite(cost)||cost<0||typeof receipt!=='string'||!receipt.trim())throw Error('Falta coste confirmado y referencia de factura');return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(!e)throw Error('Reserva no encontrada');e.actual_usd=cost;e.receipt=receipt.slice(0,300);e.confirmed_by=actor;e.confirmed_at=new Date().toISOString();return e})}
 async summary(){return this.transact(d=>{const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'});return {day,daily_limit:this.daily,reserved_today:d.entries.filter(e=>e.day===day).reduce((n,e)=>n+e.reserved,0),note:'Reservas conservadoras de gasto; la factura del proveedor confirma el coste real.',confirmed_usd:d.entries.reduce((n,e)=>n+(e.actual_usd||0),0),unconfirmed_entries:d.entries.filter(e=>e.actual_usd==null).length,entries:d.entries.slice(-250)}})}
}
