import {withFileLock} from './file-lock.mjs'
import {readFile,writeFile,mkdir,open,unlink,rename} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID} from 'node:crypto'
export class Budget{
 constructor(state,{daily=Number(process.env.STUDIO_DAILY_BUDGET||5)}={}){this.state=state;this.daily=daily}
 async transact(fn){await mkdir(this.state,{recursive:true});return withFileLock(join(this.state,'budget.lock'),async()=>{let data;try{data=JSON.parse(await readFile(join(this.state,'budget.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;data={entries:[]}}const result=await fn(data);const temp=join(this.state,'budget.'+randomUUID()+'.tmp');try{await writeFile(temp,JSON.stringify(data),{mode:0o600});await rename(temp,join(this.state,'budget.json'))}finally{await unlink(temp).catch(e=>{if(e.code!=='ENOENT')throw e})}return result})}
 async group(id,limit){if(!Number.isFinite(limit)||limit<=0||limit>5)throw Error('Techo inválido');return this.transact(d=>{d.groups||={};if(d.groups[id]&&d.groups[id].limit!==limit)throw Error('El techo del lote no se modifica');return d.groups[id]||=( {limit,at:new Date().toISOString()} )})}
 async bindOperation(job,lineage=[],limit=2){return this.transact(d=>{d.operations||={};d.job_operations||={};const members=[...new Set([...lineage,job])];const known=[...new Set(members.map(id=>d.job_operations[id]).filter(Boolean))];if(known.length>1)throw Error('Los intentos pertenecen a operaciones diferentes');const root=known[0]||members[0];if(!d.operations[root]){if(!Number.isFinite(limit)||limit<=0||limit>5)throw Error('Techo de operación inválido');d.operations[root]={limit,at:new Date().toISOString()}}for(const id of members)d.job_operations[id]=root;return {id:root,...d.operations[root]}})}
 async reserve(id,amount,category,job=null,maxJob=2,group=null){if(!Number.isFinite(amount)||amount<=0)throw Error('Reserva de presupuesto inválida');return this.transact(data=>{const prior=data.entries.find(e=>e.id===id);if(prior)return prior;const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'}),daily=data.entries.filter(e=>e.day===day).reduce((n,e)=>n+e.reserved,0),perJob=job?data.entries.filter(e=>e.job===job).reduce((n,e)=>n+e.reserved,0):0;const operation=job&&data.job_operations?.[job];if(operation&&data.entries.filter(e=>data.job_operations?.[e.job]===operation).reduce((n,e)=>n+e.reserved,0)+amount>data.operations[operation].limit+.000001)throw Error('Techo de presupuesto de la operación alcanzado');if(group){const g=data.groups?.[group];if(!g||data.entries.filter(e=>e.group===group).reduce((n,e)=>n+e.reserved,0)+amount>g.limit+.000001)throw Error('Techo de presupuesto del lote alcanzado')}if(daily+amount>this.daily+.000001||perJob+amount>maxJob+.000001)throw Error('Límite de presupuesto reservado alcanzado');const e={id,day,at:new Date().toISOString(),category,job,group,reserved:amount,state:'reserved'};data.entries.push(e);return e})}
 async usage(id,usage){return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(e){e.state='completed';e.usage=usage}return e})}
 async attach(id,job){return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(e&&!e.job)e.job=job;return e||null})}
 async reconcile(id,cost,receipt,actor){if(!Number.isFinite(cost)||cost<0||typeof receipt!=='string'||!receipt.trim())throw Error('Falta coste confirmado y referencia de factura');return this.transact(d=>{const e=d.entries.find(e=>e.id===id);if(!e)throw Error('Reserva no encontrada');e.actual_usd=cost;e.receipt=receipt.slice(0,300);e.confirmed_by=actor;e.confirmed_at=new Date().toISOString();return e})}
 async summary({offset=0,limit=250}={}){return this.transact(d=>{const day=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santo_Domingo'}),jobs={};for(const e of d.entries){if(!e.job)continue;const j=jobs[e.job]||={reserved:0,actual:0,unconfirmed:0};j.reserved+=e.reserved;j.actual+=e.actual_usd||0;if(e.actual_usd==null)j.unconfirmed++}const operations=Object.fromEntries(Object.entries(d.operations||{}).map(([id,o])=>{const entries=d.entries.filter(e=>d.job_operations?.[e.job]===id),reserved=entries.reduce((n,e)=>n+e.reserved,0);return [id,{...o,reserved,remaining:Math.max(0,o.limit-reserved),jobs:Object.entries(d.job_operations||{}).filter(([,r])=>r===id).map(([j])=>j)}]}));return {operations,day,daily_limit:this.daily,reserved_today:d.entries.filter(e=>e.day===day).reduce((n,e)=>n+e.reserved,0),note:'Reservas conservadoras; coste real solo cuando se concilia con el proveedor.',confirmed_usd:d.entries.reduce((n,e)=>n+(e.actual_usd||0),0),unconfirmed_entries:d.entries.filter(e=>e.actual_usd==null).length,total_entries:d.entries.length,jobs,entries:[...d.entries].reverse().slice(Math.max(0,offset),Math.max(0,offset)+Math.min(250,Math.max(1,limit)))}})}
}
