import {styles} from './styles.mjs'
const $=id=>document.getElementById(id);let key=null,previous='',automatic=true,brands=[];
const params=new URLSearchParams(location.search);
function styleOptions(){const chosen=$('style').value;$('style').replaceChildren();if(automatic)$('style').add(new Option('Elegir el estilo por mí','auto'));for(const [id,s]of Object.entries(styles))$('style').add(new Option(s.name,id));if([...$('style').options].some(o=>o.value===chosen))$('style').value=chosen;describe()}
function describe(){$('style-description').textContent=styles[$('style').value]?.description||'Alternaremos estructuras educativas según las piezas automáticas anteriores.'}
function mode(auto){automatic=auto;$('idea-wrap').hidden=auto;$('mode-auto').setAttribute('aria-pressed',String(auto));$('mode-idea').setAttribute('aria-pressed',String(!auto));$('mode-hint').textContent=auto?'Elegiremos un tema de los hechos comprobados de tu marca, evitando los temas automáticos más recientes.':'Cuéntanos qué quieres comunicar. Studio lo adapta a una estructura visual.';$('create').textContent=auto?'Crear por mí':'Crear desde mi idea';styleOptions();kind()}
$('mode-auto').onclick=()=>mode(true);$('mode-idea').onclick=()=>mode(false);$('style').onchange=describe;
function production(){$('export-options').hidden=$('kind').value!=='video'||$('production').value!=='produce'}
$('production').onchange=production;
function kind(){production();$('video-options').hidden=$('kind').value!=='video';$('image-options').hidden=$('kind').value==='video'||$('brand').value!=='comandpos'||automatic}
$('kind').onchange=kind;$('brand').onchange=kind;
try{const responses=await Promise.all(['/api/feed/catalog','/api/marketing'].map(async url=>{const r=await fetch(url);if(!r.ok)throw Error('No se pudo cargar el catálogo');return r.json()}));for(const t of responses[0].topics)$('topic').add(new Option(t.titulo,t.id));brands=responses[1].brands;for(const b of brands)$('brand').add(new Option(b.name,b.id));if(params.get('brand'))$('brand').value=params.get('brand');if(params.get('idea')){$('idea').value=params.get('idea');automatic=false}if(['video','imagen','carrusel','historia_social'].includes(params.get('kind')))$('kind').value=params.get('kind');mode(automatic);kind()}catch(e){$('status').textContent=e.message;$('create').disabled=true}
$('create').onclick=async()=>{const input={produce:$('production').value==='produce',aspect:$('aspect').value,allow_paid_voice:$('voice-paid').checked,brand_id:$('brand').value||'comandpos',auto:automatic,...(!automatic?{idea:$('idea').value}:{}),kind:$('kind').value,style:$('style').value,allow_paid:$('paid').checked,...(!$('image-options').hidden?{topic_id:$('topic').value}:{})};if(input.produce&&input.kind==='video'&&!input.allow_paid_voice){$('status').textContent='Autoriza el presupuesto de voz para producir el video.';return}if(!input.allow_paid){$('status').textContent='Activa la autorización de US$0.10 para generar el guion.';return}const body=JSON.stringify(input);if(body!==previous){key='idea-ui:'+crypto.randomUUID();previous=body}$('create').disabled=true;$('result').hidden=true;$('status').textContent='Preparando el tema, la narración y las escenas…';try{const r=await fetch('/api/ideas',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':key},body});const d=await r.json();if(!r.ok)throw Error(d.error);$('result').hidden=false;$('warnings').textContent=d.warnings.join(' ');$('selection').textContent=d.selection?'Tema elegido: '+d.selection.topic:'';$('result-title').textContent=d.script.titular||d.script.escenas?.[0]?.titulo||'Tu nueva pieza';$('script').textContent=JSON.stringify(d.script,null,2);$('edit').href=(d.kind==='video'?'/editor.html':d.script.layout==='brand'?'/marketing.html':'/feed-editor.html')+'?project='+encodeURIComponent(d.script.nombre);$('status').textContent='Borrador guardado con narración preparada. Abre el editor para producirlo.';if(d.job){$('status').textContent='Pieza en producción. Puedes seguir trabajando; aparecerá en Inicio para revisarla.';$('edit').href='/centro.html';$('edit').textContent='Ver producción en Inicio'}else{$('edit').textContent='Abrir y producir la pieza'}previous='';key=null}catch(e){$('status').textContent=e.message}finally{$('create').disabled=false}};
