export const templateCatalog=[
 {id:'studio-media',version:2,kinds:['video'],families:['paper','editorial'],aspects:['vertical','horizontal','square','portrait']},
 {id:'studio-commercial',version:2,kinds:['video'],families:['commercial'],aspects:['vertical','horizontal','square','portrait']},
 {id:'studio-brand-feed',version:2,kinds:['imagen','carrusel','historia_social'],families:['paper','editorial'],aspects:['portrait','vertical']}
];
export const designFields={safe_top:{min:0,max:350,default:180},safe_bottom:{min:0,max:450,default:300},caption_size:{min:28,max:72,default:46},caption_lines:{min:1,max:2,default:2},caption_gap:{min:.1,max:1.5,default:.45},caption_min_seconds:{min:.3,max:2,default:.7},caption_max_seconds:{min:1,max:6,default:3},caption_cps:{min:10,max:35,default:22}};
export function validateDesign(d={}){if(!d||typeof d!=='object'||Array.isArray(d))throw Error('Diseño inválido');for(const k of Object.keys(d))if(!['version','font','subtitle','family',...Object.keys(designFields)].includes(k))throw Error('Ajuste de diseño desconocido: '+k);if(d.font!=null&&!['Montserrat'].includes(d.font))throw Error('Fuente no disponible');if(d.version!=null&&![1,2].includes(d.version))throw Error('Versión de diseño no compatible');if(d.subtitle!=null&&!['active-word','phrase'].includes(d.subtitle))throw Error('Subtítulo inválido');if(d.family!=null&&!['paper','editorial'].includes(d.family))throw Error('Familia inválida');for(const[k,c]of Object.entries(designFields))if(d[k]!=null&&(!Number.isFinite(d[k])||d[k]<c.min||d[k]>c.max||k==='caption_lines'&&!Number.isInteger(d[k])))throw Error('Ajuste fuera de rango: '+k);if((d.caption_min_seconds??.7)>(d.caption_max_seconds??3))throw Error('La duración mínima supera la máxima');return d}
export function resolveDesign(brand={},width=1080,height=1920,override={}){const d={...brand.design,...override};validateDesign(d);const modern=d.version===2;return {modern,font:d.font||'Montserrat',subtitle:d.subtitle||'active-word',family:d.family,top:modern?(d.safe_top??180)*height/1920:height>1500?210:110,bottom:modern?(d.safe_bottom??300)*height/1920:height>1500?310:130,caption_size:d.caption_size||(height<=1350?38:46),caption_lines:d.caption_lines||2,caption_gap:d.caption_gap??.45,caption_min_seconds:d.caption_min_seconds||.7,caption_max_seconds:d.caption_max_seconds||3,caption_cps:d.caption_cps||22}}
export function validateTemplate(s){if(!s?.template)return;const t=templateCatalog.find(t=>t.id===s.template.id&&t.version===s.template.version);if(!t)throw Error('Plantilla o versión no compatible');if(!t.kinds.includes(s.tipo||'video'))throw Error('Plantilla incompatible con el formato');validateDesign(s.template.params||{});if(s.template.params?.family&&!t.families.includes(s.template.params.family))throw Error('Familia incompatible con la plantilla')}
