import sharp from 'sharp';import {readFile,writeFile} from 'node:fs/promises';import{join}from'node:path';import{createHash}from'node:crypto';import{dgiiContent}from'./dgii-content.mjs';
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validateDgii(s){if(!s.dgii)return;const p=dgiiContent(s.dgii.date);if(s.tipo!=='carrusel'||s.brand_id!=='comandpos'||JSON.stringify(p)!==JSON.stringify(s.dgii)||s.slides.length!==3)throw Error('Contenido DGII alterado o fuera de vigencia')}
export async function executeDgii(s,dir){validateDgii(s);const b=JSON.parse(await readFile(join(dir,'brand-profile.json'))),p=s.dgii,images=[],navy=b.primary,orange=b.accent;const photo=await sharp(await readFile(join(dir,'brand-photo'))).resize(880,580,{fit:'cover',position:'centre'}).png().toBuffer();const logo=await sharp(await readFile(join(dir,'brand-logo'))).resize(300,80,{fit:'inside'}).png().toBuffer();const wrap=(s,max)=>s.split(/\s+/).reduce((a,w)=>{if(a.length&&(a.at(-1)+' '+w).length<=max)a[a.length-1]+=' '+w;else a.push(w);return a},[]);function text(s,y,size=40,max=32,color=navy,weight=700){return wrap(s,max).map((l,i)=>`<text x="90" y="${y+i*(size+12)}" font-family="Montserrat" font-size="${size}" font-weight="${weight}" fill="${color}">${e(l)}</text>`).join('')}
const count=p.days_left===0?'Hoy vence el plazo':`Faltan ${p.days_left} días`;
for(let i=0;i<3;i++){let body='';if(i===0)body=text(count,235,66,24)+text(p.title,325,46,34)+`<image href="data:image/png;base64,${photo.toString('base64')}" x="100" y="485" width="880" height="580"/>`+text('15 NOVIEMBRE 2026',1110,40,40)+text(p.group,1165,25,55);
if(i===1)body=text(p.title,235,46,32)+p.points.map((point,k)=>`<circle cx="113" cy="${470+k*190}" r="28" fill="${orange}"/><text x="113" y="${479+k*190}" text-anchor="middle" font-family="Montserrat" font-size="25" fill="white" font-weight="800">${k+1}</text><g transform="translate(75,0)">${text(point,480+k*190,34,37)}</g>`).join('')+text('Preparación operativa. Consulta tus dudas',1090,25,54)+text('tributarias con tu contador.',1130,25,54);
if(i===2)body=text('Confirma tu clasificación',240,48,30)+text('15 noviembre 2026',420,57,30)+text(p.group,505,31,45)+text('Fuente: DGII · Aviso 06-26',600,27,50)+text('Consulta los requisitos y tu situación',690,29,46)+text('en los canales oficiales de la DGII.',736,29,46)+text('Organiza pedidos, mesas y cuentas',850,33,40)+text('con ComandPOS.',900,33,40)+`<rect x="90" y="980" width="900" height="90" rx="22" fill="${orange}"/>`+text('Solicita tu demo',1039,36,40,'white')+text('+1 849 540 6093 · comandpos.com',1140,27,48);
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350"><rect width="1080" height="1350" fill="white"/><rect x="70" y="40" width="360" height="100" rx="18" fill="${navy}"/><image href="data:image/png;base64,${logo.toString('base64')}" x="100" y="50" width="300" height="80"/><text x="980" y="99" text-anchor="end" font-family="Montserrat" font-size="22" font-weight="700" fill="${navy}">GUÍA DE PREPARACIÓN</text>${body}<rect x="90" y="1210" width="900" height="3" fill="${orange}"/>${text('GCODE · Contenido informativo, no comunicación oficial de DGII.',1260,20,85)}<text x="990" y="1310" text-anchor="end" font-family="Montserrat" font-size="21" fill="${navy}">${i+1}/3</text></svg>`;const bytes=await sharp(Buffer.from(svg)).jpeg({quality:95}).toBuffer(),filename='pagina-'+(i+1)+'.jpg';await writeFile(join(dir,'artifacts',filename),bytes);images.push({index:i+1,filename,width:1080,height:1350,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')})}
await writeFile(join(dir,'artifacts/manifest.json'),JSON.stringify({guion:s,caption:s.caption,images,source:p.source,review:'pending'}));return{manifest_filename:'manifest.json',images,width:1080,height:1350,caption:s.caption,content_type:'image/jpeg'}}
