(()=>{
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let library={brands:[],assets:[]};
const panel=document.createElement('details');panel.className='card';panel.innerHTML=`<summary>Diseño, recursos y sonido</summary><p id="tools-status" role="status"></p><label><input id="safe-guides" type="checkbox"> Mostrar zona segura orientativa</label><small>La interfaz de cada red puede variar. Estas guías no salen en el video.</small><h3>Texto sobre la imagen</h3><label>Texto<input id="overlay-text" maxlength="55"></label><div class="row"><label>X<input id="overlay-x" type="number" min="0" max="1000"></label><label>Y<input id="overlay-y" type="number" min="60" max="1850"></label></div><div class="row"><label>Tamaño<input id="overlay-size" type="number" min="20" max="120"></label><label>Color<input id="overlay-color" type="color"></label></div><button id="overlay-save">Aplicar texto</button><small>También puedes arrastrar este texto sobre la vista previa.</small><h3>Foto o clip propio</h3><select id="library-resource"></select><button id="insert-resource">Añadir escena</button><div class="row"><label>Inicio del clip<input id="clip-start" type="number" min="0" step=".1"></label><label>Encuadre<select id="clip-fit"><option value="cover">Llenar</option><option value="contain">Completo</option></select></label></div><label>Posición horizontal<input id="clip-focus" type="range" min="0" max="100"></label><button id="clip-apply">Aplicar encuadre</button><small>La duración se ajusta en los campos de la escena. El audio original del clip se silencia.</small><h3>Música</h3><select id="music-resource"></select><label>Volumen general<input id="music-volume" type="range" min="0" max="1" step=".01"></label><label>Volumen bajo la narración<input id="music-duck" type="range" min="0" max="1" step=".01"></label><button id="music-save">Aplicar música</button><h3>Portada</h3><button id="cover-save">Usar este momento como portada</button><p id="cover-current"></p><h3>Variación</h3><button id="variant-save">Duplicar proyecto para otra versión</button><h3>Subtítulos por palabra</h3><button id="words-load">Editar tiempos guardados</button><div id="word-editor"></div><h3>Voz de la escena</h3><canvas id="waveform" width="600" height="120"></canvas><button id="waveform-load">Ver forma de onda guardada</button>`;document.querySelector('.editor-main aside').prepend(panel);
const api=()=>window.studioEditor,msg=s=>$('tools-status').textContent=s;
async function change(fn){try{const state=api().get();fn(state.script,state);await api().set(state.script,state.selected);msg('Cambios aplicados. Guarda el proyecto para conservarlos.')}catch(e){msg(e.message)}}
function sync(){if(!api())return;const {script,selected}=api().get(),s=script.escenas[selected],o=s.overlay||{text:'',x:80,y:1250,size:48,color:'#ffffff'};for(const k of ['text','x','y','size','color'])$('overlay-'+k).value=o[k];$('clip-start').value=s.clip_start||0;$('clip-fit').value=s.fit||'cover';$('clip-focus').value=s.focus_x??50;$('music-volume').value=script.music_volume??.75;$('music-duck').value=script.music_duck??.22;$('cover-current').textContent='Momento: '+(script.cover_time??.8).toFixed(1)+' s';const resources=library.assets.filter(a=>a.brand_id===(script.brand_id||'comandpos'));$('library-resource').innerHTML=resources.filter(a=>a.type!=='audio').map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');$('music-resource').innerHTML='<option value="">Música del Studio</option>'+resources.filter(a=>a.type==='audio').map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');$('music-resource').value=script.music_resource_id||''}
$('safe-guides').onchange=()=>{document.querySelector('.safe-overlay')?.remove();if($('safe-guides').checked){const box=document.createElement('div');box.className='safe-overlay';document.querySelector('.preview').append(box)}};
$('overlay-save').onclick=()=>change((sb,{selected})=>{const text=$('overlay-text').value;if(!text){delete sb.escenas[selected].overlay;return}sb.escenas[selected].overlay={text,x:Number($('overlay-x').value),y:Number($('overlay-y').value),size:Number($('overlay-size').value),color:$('overlay-color').value}});
$('insert-resource').onclick=()=>change((sb,{selected})=>{const a=library.assets.find(a=>a.id===$('library-resource').value);if(!a)throw Error('Sube primero una foto o video desde Marketing → Recursos');sb.escenas.splice(selected+1,0,{tipo:'media',dur:a.type==='video'?Math.min(6,Math.floor(a.duration)):5,titulo:'Escribe un título',texto:'',resource_id:a.id,media_kind:a.type,clip_start:0,fit:'cover'})});
$('clip-apply').onclick=()=>change((sb,{selected})=>{const s=sb.escenas[selected];if(s.tipo!=='media')throw Error('Selecciona una escena de foto o clip propio');s.clip_start=Number($('clip-start').value);s.fit=$('clip-fit').value;s.focus_x=Number($('clip-focus').value)});
$('music-save').onclick=()=>change(sb=>{sb.music_volume=Number($('music-volume').value);sb.music_duck=Number($('music-duck').value);sb.music_resource_id=$('music-resource').value||undefined;delete sb.music_file});
$('cover-save').onclick=()=>change((sb,state)=>{sb.cover_time=state.time});
$('variant-save').onclick=async()=>{try{const s=api().get().script;s.nombre=s.nombre.slice(0,58)+'-var-'+Date.now().toString(36);const r=await fetch('/api/guardar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guion:s})});const d=await r.json();if(!r.ok)throw Error(d.error);location.href='/editor.html?project='+s.nombre}catch(e){msg(e.message)}};
$('words-load').onclick=()=>{const {script,selected}=api().get(),s=script.escenas[selected];if(!s.palabras?.length){msg('Carga primero la voz guardada o genera una previsualización con narración.');return}$('word-editor').innerHTML='<p>Palabra · inicio · final (segundos relativos al audio)</p>'+s.palabras.map((w,i)=>`<div class="word-timing"><input data-word="${i}" value="${esc(w.word)}" aria-label="Palabra ${i+1}" readonly><input data-start="${i}" type="number" min="0" step=".01" value="${w.start}" aria-label="Inicio ${i+1}"><input data-end="${i}" type="number" min="0" step=".01" value="${w.end}" aria-label="Final ${i+1}"></div>`).join('')+'<button id="words-save">Guardar tiempos</button>';$('words-save').onclick=()=>change((sb,state)=>{if(state.selected!==selected)throw Error('Vuelve a cargar los tiempos de la escena seleccionada');sb.escenas[selected].palabras=[...$('word-editor').querySelectorAll('[data-word]')].map((el,i)=>({word:el.value,start:Number($('word-editor').querySelector(`[data-start="${i}"]`).value),end:Number($('word-editor').querySelector(`[data-end="${i}"]`).value)}));sb.escenas[selected].manual_words=true})};
$('waveform-load').onclick=async()=>{try{const {script,selected}=api().get(),r=await fetch('/api/preview/audio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({script})}),d=await r.json();if(!r.ok)throw Error(d.error);const cue=d.cues.find(c=>c.scene===selected);if(!cue)throw Error('Esta escena no tiene narración');const audio=await(await fetch(cue.url)).arrayBuffer(),ctx=new AudioContext();try{const buffer=await ctx.decodeAudioData(audio),samples=buffer.getChannelData(0),canvas=$('waveform'),c=canvas.getContext('2d');c.clearRect(0,0,600,120);c.fillStyle='#dc633a';for(let x=0;x<600;x++){const from=Math.floor(x*samples.length/600),to=Math.floor((x+1)*samples.length/600);let peak=0;for(let i=from;i<to;i++)peak=Math.max(peak,Math.abs(samples[i]));c.fillRect(x,60-peak*55,1,Math.max(1,peak*110))}msg('Audio completo: '+buffer.duration.toFixed(2)+' s. Ajusta entrada, recorte y volumen en la escena.')}finally{await ctx.close()}}catch(e){msg(e.message)}};
let drag;
function attachDrag(){const doc=$('frame').contentDocument;doc.addEventListener('pointerdown',e=>{const {script,selected}=api().get(),o=script.escenas[selected].overlay;if(!o||e.target.textContent!==o.text)return;drag={x:e.clientX,y:e.clientY,overlay:{...o},selected};e.preventDefault()});doc.addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;change((sb,state)=>{if(state.selected!==d.selected)return;sb.escenas[d.selected].overlay={...d.overlay,x:Math.round(Math.max(0,Math.min(1000,d.overlay.x+e.clientX-d.x))),y:Math.round(Math.max(60,Math.min(1850,d.overlay.y+e.clientY-d.y)))}})})}
window.addEventListener('studio-change',sync);fetch('/api/marketing').then(r=>r.json()).then(d=>{library=d;sync()}).catch(e=>msg(e.message));const timer=setInterval(()=>{if(api()){clearInterval(timer);sync();attachDrag()}},200);
})();
