import fs from 'node:fs';
import {mkdir,copyFile,readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
import {renderStory} from './editorial/story-renderer.cjs';
const assets=['cocina','mesas','cuenta','cuentaxcobrar','comtabilidad','reporteBI','recursohumanos_empleados','nomina'];
export function validateEditorial(s){const p=s.editorial;if(!p)return;if(s.brand_id!=='comandpos')throw Error('El catálogo pertenece a ComandPOS');if(p.story){if(s.tipo!=='historia_social'||![13,18].includes(p.hour)||!assets.includes(p.asset)||!(p.hour===13?['question','checklist','steps']:['spotlight','detail','walkthrough']).includes(p.layout)||!Array.isArray(p.points)||p.points.length>3||p.points.some(t=>typeof t!=='string'||t.length>100))throw Error('Historia editorial inválida')}}
export async function prepareEditorial(s,dir,root){validateEditorial(s);if(!s.editorial?.story)return;await mkdir(join(dir,'editorial-assets'),{recursive:true});for(const f of ['logo.png',s.editorial.asset+'.webp'])await copyFile(join(root,'feed/brand',f),join(dir,'editorial-assets',f));}
export async function executeEditorialStory(s,dir){validateEditorial(s);const p=s.editorial,{buffer,metrics}=await renderStory({validated:true,titulo:s.titular,cuerpo:s.subtitulo,cta:s.cta,horario:p.hour,commercial:p.hour===18,asset:p.asset,points:p.points,layout:p.layout},sharp,fs,join(dir,'editorial-assets'),join(dir,'editorial-assets/logo.png'));const filename='pagina-1.jpg';await writeFile(join(dir,'artifacts',filename),buffer);const images=[{index:1,filename,width:1080,height:1920,bytes:buffer.length,sha256:createHash('sha256').update(buffer).digest('hex')}];await writeFile(join(dir,'artifacts/manifest.json'),JSON.stringify({guion:s,caption:s.caption,images,validation:{metrics,editorial_source:p.source},review:'pending'}));return {manifest_filename:'manifest.json',images,width:1080,height:1920,caption:s.caption,content_type:'image/jpeg'}}
// Reuse reviewed contextual photography; only a missing topic requires a paid photo job.
export async function prepareEditorialPhoto(script,root,photos,key){const p=script.editorial;if(p.story||p.holiday)return script;let catalog=JSON.parse(await readFile(join(root,'feed/photos.json')));let photo=catalog.find(a=>a.review?.status==='approved'&&a.review.topic_ids?.includes(p.topic));if(!photo){let j=await photos.start({topic_id:p.topic,allow_paid:true},'calendar-photo:'+p.topic,'automation');j=await photos.status(j.id);if(j.status==='creating'&&!photos.active?.has(j.id))throw Error('Fotografía con creación incierta: revisa la solicitud guardada antes de volver a comprar');if(['failed','rejected'].includes(j.status))throw Error('Fotografía requiere atención: '+(j.error||j.status));if(j.status!=='ready')throw Object.assign(Error('Esperando fotografía contextual revisada'),{code:'WAITING_RESOURCE',resource_id:j.id});catalog=JSON.parse(await readFile(join(root,'feed/photos.json')));photo=catalog.find(a=>a.id===j.photo_id);if(!photo)throw Error('Foto lista sin recurso en catálogo')}
const {brand_id,editorial,...base}=script;return {...base,editorial,tema_id:p.topic,foto_id:photo.id,layout:p.layout,captura:p.commercial&&assets.includes(p.asset)?p.asset:null};}
