import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,mkdir,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import sharp from 'sharp';
import {chooseFeed,chooseStory,editorialScript,EditorialCalendar} from './editorial-calendar.mjs';import {calendar} from './automation.mjs';import {validateFeed} from './feed.mjs';import {prepareEditorial,executeEditorialStory,prepareEditorialPhoto} from './editorial-render.mjs';
const root=new URL('.',import.meta.url).pathname,feed=JSON.parse(await readFile(new URL('./editorial/feed-catalog.json',import.meta.url))),stories=JSON.parse(await readFile(new URL('./editorial/story-catalog.json',import.meta.url)));
test('migration preserves 72 topics, weighted lines and editorial types without importing unsafe promises',()=>{assert.equal(feed.reduce((n,s)=>n+s.topics.length,0),72);assert.equal(stories.length,24);assert.deepEqual(feed.map(s=>s.weight),[60,25,15]);const history=[];for(let i=0;i<20;i++){const p=chooseFeed(feed,'2026-10-01',history);history.unshift(p)}assert.deepEqual(feed.map(s=>history.filter(p=>p.system_id===s.id).length),[12,5,3]);for(const s of feed)for(const t of s.topics){const p={date:'2026-10-01',topic:t.id,title:t.titulo,body:t.explicacion||t.consejos[0],points:t.consejos,cta:'Guarda esta guía',source:s.source,humor:t.humor};validateFeed(editorialScript(p,'imagen',t.id),'imagen')}});
test('stories are daily at 13 and 18 RD, Monday reel and Friday carousel, holiday replaces IG reel only',()=>{for(let i=1;i<=7;i++){const d='2026-10-0'+i,p=calendar(d);assert.deepEqual(p.filter(s=>s.hour).map(s=>s.targets[0].at.slice(11,16)),['17:00','22:00']);assert.ok(p.every(s=>s.targets.every(t=>t.at>s.production_at)))}const monday=calendar('2026-10-05');assert.equal(monday.find(s=>s.kind==='video').targets[0].channel,'instagram');const holiday=calendar('2026-10-05',{holidays:[{date:'2026-10-05'}]});assert.ok(holiday.find(s=>s.key==='video').targets.every(t=>t.channel!=='instagram'));assert.equal(holiday.find(s=>s.key==='feed').kind,'imagen');assert.equal(calendar('2026-10-02').find(s=>s.key==='feed').kind,'carrusel')});
test('morning and evening differ and 14-day story headlines never repeat',()=>{let history=[];for(let i=1;i<=14;i++){const day='2026-10-'+String(i).padStart(2,'0'),a=chooseStory(stories,day,13,history);history.push(a);const b=chooseStory(stories,day,18,history);assert.notEqual(a.topic,b.topic);assert.ok(!history.some(h=>h.title===b.title));history.push(b)}assert.equal(new Set(history.map(h=>h.title)).size,28)});
test('all 48 migrated story copies fit all applicable layouts, with snapshots and real 1080x1920 renders',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-story-parity-'));t.after(()=>rm(dir,{recursive:true,force:true}));await mkdir(join(dir,'artifacts'));let count=0;for(const topic of stories)for(const hour of [13,18])for(const layout of hour===13?['question','checklist','steps']:['spotlight','detail','walkthrough']){const c=topic[hour===13?'morning':'evening'],p={story:true,hour,topic:topic.id,title:c.title,body:c.body,points:c.points||[],cta:c.cta,asset:topic.asset,layout,source:'legacy',commercial:hour===18},s=editorialScript(p,'historia_social',topic.id+hour);validateFeed(s,s.tipo);await prepareEditorial(s,dir,root);const result=await executeEditorialStory(s,dir);const m=await sharp(join(dir,'artifacts/pagina-1.jpg')).metadata();assert.equal(m.width,1080);assert.equal(m.height,1920);assert.equal(result.images.length,1);count++}assert.equal(count,144)});
test('holiday outage is explicit, cached response is reused and no synthetic dates invented',async t=>{const dir=await mkdtemp(join(tmpdir(),'studio-holiday-'));t.after(()=>rm(dir,{recursive:true,force:true}));let calls=0;const c=new EditorialCalendar(dir,{fetcher:async()=>{calls++;return Response.json([{date:'2026-10-05',localName:'Prueba',countryCode:'DO'}])}});await c.holidays('2026');await c.holidays('2026');assert.equal(calls,1);c.fetcher=async()=>{throw Error('offline')};const missing=await c.holidays('2027');assert.deepEqual(missing.days,[]);assert.match(missing.warning,/offline/)});
test('photography resumes same idempotent resource and never renders a pending image',async()=>{let key;const p=chooseFeed(feed,'2026-10-01'),s=editorialScript(p,'imagen','photo-test');const fake={start:async(i,k)=>{key=k;return {id:'pending'}},status:async()=>({status:'generating',id:'pending'})};await assert.rejects(prepareEditorialPhoto(s,root,fake,'one'),e=>e.code==='WAITING_RESOURCE');assert.equal(key,'calendar-photo:'+p.topic)});

test('every migrated feed topic validates a four-page composition and unique final CTA',()=>{for(const system of feed)for(const topic of system.topics){const p={topic:topic.id,title:topic.titulo,body:topic.explicacion||topic.consejos[0],points:topic.consejos,humor:topic.humor,cta:'Guarda esta guía',source:system.source},s=editorialScript(p,'carrusel',topic.id);validateFeed(s,'carrusel');assert.equal(s.slides.length,4);assert.equal(s.slides.filter(p=>p.titulo==='Guarda esta guía').length,1)}});

test('uncertain photo creation is held for review instead of polling forever or buying again',async()=>{const s=editorialScript(chooseFeed(feed,'2026-10-01'),'imagen','unknown');let starts=0;const photos={active:new Set(),start:async()=>{starts++;return{id:'unknown'}},status:async()=>({id:'unknown',status:'creating'})};await assert.rejects(prepareEditorialPhoto(s,root,photos,'unknown'),/creación incierta/);assert.equal(starts,1)});
