// Composición secundaria: conserva la escena y añade un panel legible del producto.
(()=>{let aspect='vertical';const original=window.seek,svgNS='http://www.w3.org/2000/svg';const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.setOutputFormat=name=>{aspect=name;const stage=document.querySelector('#stage'),w=name==='horizontal'?1920:1080,h=name==='vertical'?1920:name==='portrait'?1350:1080;stage.setAttribute('viewBox',`0 0 ${w} ${h}`);stage.setAttribute('width',w);stage.setAttribute('height',h);stage.style.width=w+'px';stage.style.height=h+'px';document.body.style.width=w+'px';document.body.style.height=h+'px'};
window.seek=t=>{original(t);if(aspect==='vertical')return;if(aspect==='portrait'){const stage=document.querySelector('#stage');stage.innerHTML='<rect width="1080" height="1350" fill="#14233b"/><g transform="translate(160,0) scale(.7)">'+stage.innerHTML+'</g>';return};const stage=document.querySelector('#stage'),raw=stage.innerHTML,wide=aspect==='horizontal',scale=wide?.52:.48,x=wide?690:550,width=wide?1120:475,story=window.currentStoryboard||{},scene=(story.escenas||[]).find((s,i)=>{const start=story.escenas.slice(0,i).reduce((n,e)=>n+e.dur,0);return t>=start&&t<start+s.dur})||{},title=scene.titulo||scene.rotulo||scene.texto||scene.cta||'ComandPOS',words=String(title).split(' '),lines=[];for(const word of words){if(lines.length&&(lines.at(-1)+' '+word).length<(wide?30:18))lines[lines.length-1]+=' '+word;else lines.push(word)}
let panel=`<rect width="${wide?1920:1080}" height="1080" fill="#14233B"/><g transform="translate(40,40) scale(${scale})">${raw}</g><rect x="${x-30}" y="60" width="4" height="960" fill="#FF6B35"/><image href="assets/n8n-logo.png" x="${x}" y="65" width="${wide?390:340}" height="90"/>`;
lines.slice(0,5).forEach((line,i)=>panel+=`<text x="${x}" y="${230+i*(wide?88:57)}" fill="${i===lines.length-1?'#FF6B35':'white'}" font-family="Montserrat" font-weight="900" font-size="${wide?76:44}">${escape(line)}</text>`);
const capture=story.evidencia?.imagen||scene.imagen||scene.capturas?.[0]?.imagen;
if(capture)panel+=`<rect x="${x}" y="${wide?520:590}" width="${width}" height="${wide?325:235}" rx="18" fill="white"/><image href="${escape(capture)}" x="${x+10}" y="${wide?530:600}" width="${width-20}" height="${wide?305:215}" preserveAspectRatio="xMidYMid meet"/>`;
panel+=`<text x="${x}" y="970" fill="#B9CBDF" font-family="Montserrat" font-size="${wide?29:21}">Caso ilustrativo · comandpos.com</text>`;stage.innerHTML=panel};
const cargar=window.cargar;window.cargar=sb=>{window.currentStoryboard=sb;return cargar(sb)};
})();
