import test from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,readFile,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import sharp from 'sharp'
import {Marketing} from './marketing.mjs'
import {Budget} from './budget.mjs'
import {ImageLines,openaiImage,estimatedCost} from './image-lines.mjs'
async function fixture(t,provider){const root=await mkdtemp(join(tmpdir(),'studio-image-test-'));t.after(()=>rm(root,{recursive:true,force:true}));const marketing=await new Marketing(root).init(),bytes=await sharp({create:{width:160,height:60,channels:3,background:'orange'}}).png().toBuffer();const a=await marketing.upload({brand_id:'comandpos',filename:'ref.png',rights_confirmed:true},bytes,'test');const store=await new ImageLines(root,{marketing,budget:new Budget(join(root,'.studio-state'),{daily:5}),provider,preflight:async()=>{}}).init();const line={id:'new-line',name:'Nueva dirección',instructions:'Luz cálida',reference_asset_ids:[a.id],provider:'openai',model:'gpt-image-2.5-sunburst-2026-09-08',size:'1024x1280',quality:'high',output_format:'png'};await store.saveLine(line,'test');const input={line_id:line.id,brand_id:'comandpos',fact_index:1,logo_asset_id:a.id,headline:'Del pedido a cocina',subline:'Envía tus comandas desde ComandPOS.',brief:'Cocinero recibiendo una comanda',allow_paid:true};return {root,store,marketing,a,line,input}}
test('multipart sends exact reference bytes and pinned model',async()=>{const bytes=Buffer.from('reference bytes');const out=await openaiImage({key:'test-only',job:{line:{model:'gpt-image-2.5-sunburst-2026-09-08',size:'1024x1280',quality:'high',output_format:'png'},prompt:'visual'},inputs:[{bytes,mime:'image/png',extension:'png'}],fetcher:async(url,opt)=>{assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal(opt.body.get('model'),'gpt-image-2.5-sunburst-2026-09-08');assert.deepEqual(Buffer.from(await opt.body.getAll('image[]')[0].arrayBuffer()),bytes);return new Response(JSON.stringify({data:[{b64_json:Buffer.from('result').toString('base64')}]}),{headers:{'x-request-id':'request'}})}});assert.equal(out.request_id,'request');assert.equal(out.bytes.toString(),'result')})
test('isolated line snapshots, library output, idempotency and changed-payload rejection',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;return {bytes:await sharp({create:{width:1024,height:1280,channels:3,background:'#f3e5ca'}}).png().toBuffer(),usage:{input_tokens_details:{text_tokens:100,image_tokens:200},output_tokens:1000},request_id:'test'}});const j=await f.store.create(f.input,'test-request-123','test');await f.store.running;const done=f.store.get(j.id);assert.equal(done.status,'succeeded');assert.equal(done.reference_inputs[0].sha256,f.a.hash);assert.equal(f.marketing.asset(done.asset_id).meta.image_line_id,'new-line');assert.equal(done.review,'pending');assert.equal((await sharp(await readFile(f.marketing.asset(done.asset_id).path)).metadata()).height,1280);await f.store.saveLine({...f.line,version:1,instructions:'Cambio posterior'},'test');assert.equal(f.store.get(j.id).line.instructions,'Luz cálida');await f.store.saveLine({...f.line,id:'second-line',instructions:'Otra línea'},'test');assert.equal(f.store.lines.length,2);assert.equal((await f.store.create(f.input,'test-request-123','test')).id,j.id);assert.equal(calls,1);await assert.rejects(f.store.create({...f.input,headline:'Otro'},'test-request-123','test'),/otro contenido/)})
test('cross-brand logo, invalid config and missing explicit line rejected before payment',async t=>{const f=await fixture(t,()=>{throw Error('should not call')});await assert.rejects(f.store.create({...f.input,brand_id:'gcode'},'test-request-123','test'),/otra marca/);await assert.rejects(f.store.create({...f.input,line_id:null},'test-request-124','test'),/explícitamente/);await assert.rejects(f.store.saveLine({...f.line,model:'invented'},'test'),/no admitidos/);assert.equal(f.store.jobs.length,0)})
test('uncertain outcomes are not retried, including restart',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;throw Error('Transport interrupted')});const j=await f.store.create(f.input,'test-request-123','test');await f.store.running;assert.equal(f.store.get(j.id).status,'uncertain');await f.store.create(f.input,'test-request-123','test');const reopened=await new ImageLines(f.root,{marketing:f.marketing,budget:f.store.budget,provider:()=>{calls++},preflight:async()=>{}}).init();await reopened.running;assert.equal(calls,1);await assert.rejects(reopened.recover(j.id),/Solo se recupera/)})
test('composition recovery uses saved original without a paid retry',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;return {bytes:await sharp({create:{width:1024,height:1280,channels:3,background:'white'}}).png().toBuffer()}});const upload=f.marketing.upload.bind(f.marketing);f.marketing.upload=async()=>{throw Error('storage unavailable')};const j=await f.store.create(f.input,'test-request-123','test');await f.store.running;assert.equal(f.store.get(j.id).status,'composition_failed');f.marketing.upload=upload;assert.equal((await f.store.recover(j.id)).status,'succeeded');assert.equal(calls,1)})
test('cost is usage estimate, not billed total',()=>{assert.equal(estimatedCost({}),null);assert.equal(estimatedCost({input_tokens_details:{text_tokens:100,image_tokens:200},output_tokens:1000}).usd,.0321)})
test('safe reframe retains previous output, marks it superseded and does not repay',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;return {bytes:await sharp({create:{width:1024,height:1280,channels:3,background:'orange'}}).png().toBuffer()}});const j=await f.store.create(f.input,'test-request-123','test');f.store.jobs.find(x=>x.id===j.id).composition_version=1;await f.store.running;const original=f.store.jobs.find(x=>x.id===j.id);original.composition_version=1;const previous=original.asset_id;const fixed=await f.store.recompose(j.id,'reviewer');assert.equal(fixed.previous_outputs[0].asset_id,previous);assert.equal(fixed.composition_version,2);assert.equal(f.marketing.asset(previous).meta.superseded_by,fixed.asset_id);await f.store.recompose(j.id,'reviewer');assert.equal(f.store.get(j.id).previous_outputs.length,1);assert.equal(calls,1)})
test('stories reuse original of default line and same brand without another provider request',async t=>{let calls=0;const f=await fixture(t,async()=>{calls++;return {bytes:await sharp({create:{width:1024,height:1280,channels:3,background:'white'}}).png().toBuffer()}});const j=await f.store.create(f.input,'story-source-123','test');await f.store.running;f.marketing.data.brands.find(b=>b.id==='comandpos').logo_resource_id=f.a.id;await f.store.setDefault(f.line.id,'test');const script={brand_id:'comandpos',titular:'Pedidos claros',subtitulo:'Envía a cocina',editorial:{story:true,asset:'cocina'}};const out=await f.store.prepareStory(script);assert.equal(out.editorial.visual_line.source_generation_id,j.id);assert.equal(out.editorial.visual_line.additional_generation_cost_usd,0);assert.equal(f.marketing.asset(out.resource_id).meta.hash,f.store.get(j.id).provider_result.original_sha256);assert.equal((await f.store.prepareStory(script)).resource_id,out.resource_id);assert.equal(calls,1);await assert.rejects(f.store.prepareStory({...script,brand_id:'gcode'}),/esta marca/);await f.store.saveLine({...f.line,version:1,instructions:'Nueva versión'},'test');await assert.rejects(f.store.prepareStory(script),/necesita una fotografía/)})
