import './fontconfig.mjs'
import sharp from 'sharp'
import {mkdir,readFile,writeFile,rename,readdir} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID,createHash} from 'node:crypto'
import {storagePreflight} from './storage.mjs'
const now=()=>new Date().toISOString(),hash=x=>createHash('sha256').update(x).digest('hex'),fail=(s,m)=>Object.assign(Error(m),{status:s})
export const imageOptions={models:['gpt-image-2.5-sunburst-2026-09-08','gpt-image-2.5-flare-2026-09-08'],sizes:['1024x1280','1024x1024','1024x1536'],qualities:['medium','high'],formats:['png','jpeg','webp'],reservation_usd:.75}
const text=(x,max)=>{if(typeof x!=='string'||!x.trim()||x.length>max)throw fail(422,'Texto vacío o demasiado largo');return x.trim()}
const esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
async function save(file,data){const tmp=file+'.'+randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(data,null,2),{mode:0o600});await rename(tmp,file)}
export function estimatedCost(usage){const d=usage?.input_tokens_details;if(!Number.isFinite(d?.text_tokens)||!Number.isFinite(d?.image_tokens)||!Number.isFinite(usage?.output_tokens))return null;return {usd:(d.text_tokens*5+d.image_tokens*8+usage.output_tokens*30)/1e6,basis:'Estimación con tokens reportados; no conciliada con factura',rates_date:'2026-10-03'}}
export async function openaiImage({job,inputs,key=process.env.OPENAI_API_KEY,fetcher=fetch}){
 if(!key)throw fail(503,'Falta configurar OPENAI_API_KEY en el servidor')
 const form=new FormData();for(const [k,v]of Object.entries({model:job.line.model,prompt:job.prompt,size:job.line.size,quality:job.line.quality,output_format:job.line.output_format,n:'1'}))form.append(k,v)
 for(const [i,a]of inputs.entries())form.append('image[]',new Blob([a.bytes],{type:a.mime}),`reference-${i}.${a.extension}`)
 const response=await fetcher('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:'Bearer '+key},body:form,signal:AbortSignal.timeout(240000)})
 // Do not reflect provider payloads: they can contain input data or infrastructure details.
 if(!response.ok)throw Object.assign(Error(`OpenAI rechazó la solicitud (HTTP ${response.status}). No se reintentó.`),{definite:response.status>=400&&response.status<500})
 const out=await response.json();if(!out.data?.[0]?.b64_json)throw Error('Respuesta sin imagen; comprueba el proveedor antes de repetir')
 return {bytes:Buffer.from(out.data[0].b64_json,'base64'),usage:out.usage||null,response_model:out.model||null,request_id:response.headers.get('x-request-id'),created:out.created||null}
}
export async function composeImage(bytes,job,logo){
 const [w,h]=job.line.size.split('x').map(Number),b=job.brand,c=job.copy,primary=/^#[a-f\d]{6}$/i.test(b.primary)?b.primary:'#14233b',accent=/^#[a-f\d]{6}$/i.test(b.accent)?b.accent:'#ff6b35';
 const wrap=(s,n)=>s.split(/\s+/).reduce((a,v)=>{if(a.length&&(a.at(-1)+' '+v).length<=n)a[a.length-1]+=' '+v;else a.push(v);return a},[])
 const title=wrap(c.headline,25),sub=wrap(c.subline,48);if(title.length>2||sub.length>2)throw fail(422,'Acorta el titular o el subtítulo para dos líneas')
 const logoBytes=await sharp(logo).resize(260,72,{fit:'inside',withoutEnlargement:true}).png().toBuffer(),lm=await sharp(logoBytes).metadata();
 // Native aspect is preserved. Exact brand logo and all visible copy are composed locally.
 const yTitle=156,ySub=yTitle+title.length*64+18,footer=h-170;
 for(const [t,size]of [...title.map(x=>[x,56]),...sub.map(x=>[x,29]),[c.cta,30],[b.website||'',22]]){const m=await sharp({text:{text:esc(t),font:'Montserrat Bold '+size,rgba:true}}).metadata();if(m.width>w-112)throw fail(422,'Texto demasiado ancho para el formato')}
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><defs><linearGradient id="top" x2="0" y2="1"><stop offset="0" stop-color="white"/><stop offset=".82" stop-color="white"/><stop offset="1" stop-color="white" stop-opacity="0"/></linearGradient><linearGradient id="bottom" x2="0" y2="1"><stop stop-color="white" stop-opacity="0"/><stop offset=".28" stop-color="white"/></linearGradient></defs><rect width="${w}" height="${ySub+sub.length*38+70}" fill="url(#top)"/><rect y="${footer-65}" width="${w}" height="235" fill="url(#bottom)"/><rect x="${(w-300)/2}" y="22" width="300" height="88" rx="16" fill="${primary}"/><image href="data:image/png;base64,${logoBytes.toString('base64')}" x="${(w-lm.width)/2}" y="35" width="${lm.width}" height="${lm.height}"/>${title.map((t,i)=>`<text x="${w/2}" y="${yTitle+i*64}" text-anchor="middle" font-family="Montserrat" font-size="56" font-weight="900" fill="${primary}">${esc(t)}</text>`).join('')}${sub.map((t,i)=>`<text x="${w/2}" y="${ySub+i*38}" text-anchor="middle" font-family="Montserrat" font-size="29" fill="${primary}">${esc(t)}</text>`).join('')}<rect x="${w*.14}" y="${footer}" width="${w*.72}" height="74" rx="22" fill="${accent}"/><text x="${w/2}" y="${footer+48}" text-anchor="middle" font-family="Montserrat" font-size="30" font-weight="800" fill="white">${esc(c.cta)}</text><text x="${w/2}" y="${h-47}" text-anchor="middle" font-family="Montserrat" font-size="22" fill="${primary}">${esc((b.website||'').replace('https://',''))}</text><text x="${w/2}" y="${h-19}" text-anchor="middle" font-family="Montserrat" font-size="14" fill="${primary}">Escena ilustrativa</text></svg>`
 const meta=await sharp(bytes).metadata();if(meta.width!==w||meta.height!==h)throw Error('El proveedor devolvió dimensiones diferentes; se conserva el original para revisión')
 let base=bytes;
 if((job.composition_version||2)>=2){const scale=.75,small=await sharp(bytes).resize(Math.round(w*scale),Math.round(h*scale),{fit:'inside'}).png().toBuffer(),top=Math.min(Math.round(ySub+sub.length*38+70-140*scale+12),h-Math.round(h*scale));base=await sharp({create:{width:w,height:h,channels:3,background:'white'}}).composite([{input:small,left:Math.round(w*(1-scale)/2),top}]).png().toBuffer()}
 const image=sharp(base).composite([{input:Buffer.from(svg)}]);return job.line.output_format==='jpeg'?image.jpeg({quality:95}).toBuffer():job.line.output_format==='webp'?image.webp({quality:95}).toBuffer():image.png().toBuffer()
}
export class ImageLines{
 constructor(root,{marketing,budget,provider=openaiImage,preflight=storagePreflight}={}){this.root=root;this.dir=join(root,'.studio-state/image-lines');this.marketing=marketing;this.budget=budget;this.provider=provider;this.preflight=preflight;this.lines=[];this.settings={default_line_id:null};this.jobs=[];this.serial=Promise.resolve();this.running=null}
 async init(){await mkdir(join(this.dir,'jobs'),{recursive:true,mode:0o700});try{this.lines=JSON.parse(await readFile(join(this.dir,'lines.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}try{this.settings=JSON.parse(await readFile(join(this.dir,'settings.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}for(const id of await readdir(join(this.dir,'jobs'))){if(!/^img_[a-f0-9-]{36}$/.test(id))continue;const j=JSON.parse(await readFile(join(this.dir,'jobs',id,'job.json'),'utf8'));if(j.status==='requesting'){j.status='uncertain';j.error='Servicio interrumpido durante la solicitud. No se repetirá automáticamente.';await this.persist(j)}else if(j.status==='composing'){j.status='composition_failed';j.error='Composición interrumpida; puedes recuperar sin generar otra imagen.';await this.persist(j)}this.jobs.push(j)}this.kick();return this}
 tx(fn){const p=this.serial.then(fn);this.serial=p.catch(()=>{});return p}
 snapshot(){return structuredClone({lines:this.lines,default_line_id:this.settings.default_line_id,jobs:this.jobs.map(j=>({...j,prompt:undefined})),options:imageOptions})}
 get(id){const j=this.jobs.find(j=>j.id===id);if(!j)throw fail(404,'Generación no encontrada');return structuredClone(j)}
 asset(id){const a=this.marketing.asset(id);if(a.meta.type!=='image'||a.meta.expires_at&&Date.parse(a.meta.expires_at)<=Date.now())throw fail(422,'Referencia no disponible');return a}
 setDefault(id,actor){return this.tx(async()=>{if(!this.lines.some(l=>l.id===id))throw fail(422,'Línea no encontrada');const settings={default_line_id:id,updated_by:actor,updated_at:now()};await save(join(this.dir,'settings.json'),settings);this.settings=settings;return settings})}
 saveLine(d,actor){return this.tx(async()=>{if(!/^[a-z0-9-]{3,70}$/.test(d.id||''))throw fail(422,'Identificador de línea inválido');if(d.provider!=='openai'||!imageOptions.models.includes(d.model)||!imageOptions.sizes.includes(d.size)||!imageOptions.qualities.includes(d.quality)||!imageOptions.formats.includes(d.output_format))throw fail(422,'Modelo o configuración no admitidos');if(!Array.isArray(d.reference_asset_ids)||d.reference_asset_ids.length<1||d.reference_asset_ids.length>3||new Set(d.reference_asset_ids).size!==d.reference_asset_ids.length)throw fail(422,'Selecciona de una a tres referencias distintas');d.reference_asset_ids.forEach(id=>this.asset(id));const prior=this.lines.find(x=>x.id===d.id);if(prior&&d.version!==prior.version)throw fail(409,'La línea cambió; vuelve a cargar antes de guardar');const line={id:d.id,name:text(d.name,100),instructions:text(d.instructions,5000),reference_asset_ids:d.reference_asset_ids,provider:d.provider,model:d.model,size:d.size,quality:d.quality,output_format:d.output_format,version:(prior?.version||0)+1,created_at:prior?.created_at||now(),updated_at:now(),updated_by:actor};const next=[...this.lines.filter(x=>x.id!==line.id),line];await save(join(this.dir,'lines.json'),next);this.lines=next;return line})}
 create(input,key,actor){return this.tx(async()=>{if(!/^[\w:-]{8,120}$/.test(key||''))throw fail(422,'Falta clave de solicitud válida');const fingerprint=hash(JSON.stringify(input)),prior=this.jobs.find(j=>j.idempotency_key===key);if(prior){if(prior.fingerprint!==fingerprint)throw fail(409,'Esta solicitud ya corresponde a otro contenido');return this.get(prior.id)}if(input.allow_paid!==true)throw fail(422,'Confirma la generación de pago');const line=this.lines.find(x=>x.id===input.line_id);if(!line)throw fail(422,'Selecciona una línea explícitamente');const brand=this.marketing.brand(input.brand_id);const facts=String(brand.facts||'').split(/\.\s*/).map(x=>x.trim()).filter(Boolean);if(!Number.isInteger(input.fact_index)||!facts[input.fact_index])throw fail(422,'Selecciona contenido existente de la marca');const logo=this.asset(input.logo_asset_id||brand.logo_resource_id);if(logo.meta.brand_id!==brand.id)throw fail(422,'El logotipo pertenece a otra marca');const copy={headline:text(input.headline,48),subline:text(input.subline,90),cta:text(brand.cta,48)},brief=text(input.brief,1800);const references=line.reference_asset_ids.map(id=>this.asset(id).meta);const j={id:'img_'+randomUUID(),idempotency_key:key,fingerprint,actor,created_at:now(),updated_at:now(),status:'queued',line:structuredClone(line),brand,content:{source:'brand.facts',index:input.fact_index,text:facts[input.fact_index]},copy,brief,references,logo:logo.meta,review:'pending',composition_version:2,cost_estimate:null,reservation_usd:imageOptions.reservation_usd};
 j.prompt=`Create one premium commercial photographic background for ${brand.name}, audience ${brand.audience||''}. Target ${line.size}. Creative direction: ${line.instructions}\nAttached images are STYLE references only: study warm light, composition, photographic finish and visual hierarchy. Never copy their text, logos, brand names, claims or product UI. Use only selected brand colors ${brand.primary}, ${brand.accent}. Brand facts: ${j.content.text}. Restrictions: ${brand.restrictions||''}. Scene brief: ${brief}. Main message to illustrate (do NOT render text): ${copy.headline}. Context: ${copy.subline}. Top 30% must be bright white negative space blending naturally into photograph, bottom 20% white negative space for later typography. Put main subjects in middle 35%-78%, keep faces/hands/products away from margins. No letters, text, logos, numbers, invented UI, watermarks, certifications or badges. Do not draw a fake software screen; use devices with screen facing away if needed. Exactly one clear focal idea, polished authentic Latin American business photography, anatomy correct. Final title, genuine brand logo and CTA will be overlaid by Studio.`;
 // Validate typography before making a paid call.
 await composeImage(await sharp({create:{width:Number(line.size.split('x')[0]),height:Number(line.size.split('x')[1]),channels:3,background:'white'}}).png().toBuffer(),j,await readFile(logo.path));
 await this.preflight(this.root);await mkdir(join(this.dir,'jobs',j.id),{recursive:true,mode:0o700});await this.persist(j);this.jobs.push(j);this.kick();return this.get(j.id)})}
 persist(j){j.updated_at=now();return save(join(this.dir,'jobs',j.id,'job.json'),j)}
 kick(){if(this.running)return;this.running=Promise.resolve().then(async()=>{for(let j;(j=this.jobs.find(x=>x.status==='queued'));){await this.execute(j)}}).finally(()=>{this.running=null;if(this.jobs.some(j=>j.status==='queued'))this.kick()})}
 async execute(j){let sent=false;try{await this.preflight(this.root);const inputs=[];for(const ref of j.references){const a=this.asset(ref.id),bytes=await readFile(a.path);if(hash(bytes)!==ref.hash)throw Error('La referencia cambió');const m=await sharp(bytes).metadata();if(!['png','jpeg','webp'].includes(m.format))throw Error('Referencia no compatible');inputs.push({bytes,mime:'image/'+m.format,extension:m.format})}if(this.provider===openaiImage&&!process.env.OPENAI_API_KEY)throw Error('Falta OPENAI_API_KEY en el servidor');await this.budget.reserve(j.id,.75,'image-line',j.id,.75);j.status='requesting';j.started_at=now();j.reference_inputs=inputs.map((a,i)=>({asset_id:j.references[i].id,sha256:hash(a.bytes),bytes:a.bytes.length}));await this.persist(j);sent=true;const out=await this.provider({job:j,inputs});const dir=join(this.dir,'jobs',j.id);await writeFile(join(dir,'original.bin'),out.bytes,{mode:0o600});j.provider_result={request_id:out.request_id,response_model:out.response_model,executed_model:j.line.model,usage:out.usage,created:out.created,original_sha256:hash(out.bytes)};j.cost_estimate=estimatedCost(out.usage);j.generation_ms=Date.now()-Date.parse(j.started_at);j.status='composing';await this.persist(j);await this.budget.usage(j.id,out.usage);await this.finish(j)}catch(e){j.status=j.status==='composing'?'composition_failed':sent&&!e.definite?'uncertain':'failed';j.error=e.message;await this.persist(j)}}
 recompose(id,actor){return this.tx(async()=>{const j=this.jobs.find(j=>j.id===id);if(!j||j.status!=='succeeded')throw fail(409,'Solo se ajustan imágenes terminadas');if(j.composition_version===2)return this.get(id);j.previous_outputs||=[];j.previous_outputs.push({asset_id:j.asset_id,url:j.url,composition_version:j.composition_version||1,at:now()});j.composition_version=2;j.status='composing';j.review='pending';j.recomposed_by=actor;await this.persist(j);try{await this.finish(j)}catch(e){j.status='composition_failed';j.error=e.message;await this.persist(j)}return this.get(id)})}
 async finish(j){j.composition_version||=2;const dir=join(this.dir,'jobs',j.id),logo=await readFile(this.asset(j.logo.id).path);if(hash(logo)!==j.logo.hash)throw Error('El logotipo cambió');const bytes=await composeImage(await readFile(join(dir,'original.bin')),j,logo);const asset=await this.marketing.upload({brand_id:j.brand.id,name:j.copy.headline,filename:j.id+'.'+j.line.output_format,tags:'generación, '+j.line.name,rights_confirmed:true,rights:'Imagen generada con OpenAI; referencias propias declaradas por el usuario; revisar derechos antes de publicar.',source_url:'/images.html?job='+j.id,license:'Condiciones del proveedor; no certifica exclusividad'},bytes,j.actor);await this.marketing.tx(j.actor,'image-line.completed',()=>{const a=this.marketing.data.assets.find(a=>a.id===asset.id);a.image_generation_id=j.id;a.image_line_id=j.line.id;a.generation_model=j.line.model;for(const previous of j.previous_outputs||[]){const old=this.marketing.data.assets.find(a=>a.id===previous.asset_id);if(old&&old.id!==a.id)old.superseded_by=a.id}return a});j.asset_id=asset.id;j.url='/api/library/'+asset.id;j.status='succeeded';j.error=null;j.completed_at=now();await this.persist(j)}
 recover(id){return this.tx(async()=>{const j=this.jobs.find(j=>j.id===id);if(!j||j.status!=='composition_failed')throw fail(409,'Solo se recupera la composición con original guardado');j.status='composing';await this.persist(j);try{await this.finish(j)}catch(e){j.status='composition_failed';j.error=e.message;await this.persist(j)}return this.get(id)})}
}
