import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Budget} from './budget.mjs';import {sceneKey,visualContext} from './scene-cache.mjs';
async function temp(t){const dir=await mkdtemp(join(tmpdir(),'studio-improve-'));t.after(()=>rm(dir,{recursive:true,force:true}));return dir}
test('budget reads all job totals even when detail is paginated and old lock exists',async t=>{const dir=await temp(t);await writeFile(join(dir,'budget.lock'),'');await writeFile(join(dir,'budget.json'),JSON.stringify({entries:Array.from({length:251},(_,i)=>({id:''+i,job:'j'+i,reserved:.1,actual_usd:i===0?.02:undefined,day:'2020-01-01'}))}));const s=await new Budget(dir).summary();assert.equal(s.entries.length,250);assert.equal(s.jobs.j0.reserved,.1);assert.equal(s.jobs.j0.actual,.02);assert.equal(s.jobs.j0.unconfirmed,0);assert.equal(s.total_entries,251)});
test('visual context changes invalidate cache but campaign does not',()=>{const scene={tipo:'media',dur:3,titulo:'Datos'},story={escenas:[scene],design_family:'paper',editorial_topic:'Inventario'};const key=s=>sceneKey({scene,context:visualContext(s,scene,0,0,3)});assert.notEqual(key(story),key({...story,design_family:'editorial'}));assert.notEqual(key(story),key({...story,editorial_topic:'Ventas'}));assert.equal(key(story),key({...story,campaign_id:'otro'}))});
import {mkdir,utimes,symlink,readFile} from 'node:fs/promises';import {spawn} from 'node:child_process';import {once} from 'node:events';import {withFileLock} from './file-lock.mjs';import {captionPages,captionSVG} from './captions.mjs';import {resolveDesign,validateTemplate} from './design.mjs';import {compareVersions} from './version-diff.mjs';import {alignmentKey,validWords} from './subtitulos.mjs';import {inspectCache,cleanCache,storagePreflight} from './storage.mjs';import {capability} from './capabilities.mjs';import {Batches} from './batches.mjs';import {timelineXML,subtitleFile} from './handoff.mjs';
test('kernel lock recovers after killed owner and serializes reservations',async t=>{const dir=await temp(t),lock=join(dir,'budget.lock');const code=`import {withFileLock} from ${JSON.stringify(new URL('./file-lock.mjs',import.meta.url).href)};await withFileLock(${JSON.stringify(lock)},async()=>{console.log('ready');await new Promise(()=>{});})`;const child=spawn(process.execPath,['--input-type=module','-e',code],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill('SIGKILL'));await once(child.stdout,'data');child.kill('SIGKILL');await once(child,'exit');assert.equal(await withFileLock(lock,async()=>42,{timeout:3000}),42);const b=new Budget(dir,{daily:1});const results=await Promise.allSettled(Array.from({length:12},(_,i)=>b.reserve('r'+i,.1,'test')));assert.equal(results.filter(r=>r.status==='fulfilled').length,10);assert.ok((await b.summary()).reserved_today<=1.000001)});
test('batch ceiling aggregates all jobs and cannot be raised',async t=>{const b=new Budget(await temp(t),{daily:5});await b.group('g',.3);await b.reserve('a',.2,'test','j1',2,'g');await assert.rejects(b.reserve('b',.2,'test','j2',2,'g'),/lote/);await assert.rejects(b.group('g',1),/modifica/);assert.equal((await b.summary()).total_entries,1)});
test('captions preserve accents and times, split pauses and remain in two lines',()=>{const text='Órdenes claras. La cocina recibe el pedido sin cebolla';const words=text.split(' ').map((word,i)=>({word,start:i*.5,end:i*.5+.4}));words.at(-1).start=8;words.at(-1).end=8.4;const pages=captionPages(words,{maxWidth:16,maxLines:2});assert.deepEqual(pages.flatMap(p=>p.words),words);assert.ok(pages.every(p=>p.lines.length<=2));assert.equal(pages.at(-1).words[0].word,'cebolla');assert.match(captionSVG(words,.2,{measure:(s,size)=>s.length*size*.5}),/Órdenes/)});
test('versioned design validates parameters and detects nontext version differences',()=>{assert.throws(()=>resolveDesign({design:{safe_top:999}}),/rango/);assert.throws(()=>validateTemplate({tipo:'imagen',template:{id:'studio-media',version:2}}),/incompatible/);const d=resolveDesign({design:{version:2,safe_top:200}},1080,960);assert.equal(d.top,100);const diff=compareVersions({escenas:[{id:'b',dur:3},{id:'a',dur:4,resource_id:'new'}]}, {escenas:[{id:'a',dur:2,resource_id:'old'},{id:'b',dur:3},{id:'c',dur:1}]});assert.ok(diff.some(d=>d.type==='orden'));assert.ok(diff.some(d=>d.field==='dur'));assert.ok(diff.some(d=>d.field==='resource_id'));assert.ok(diff.some(d=>d.type==='solo_guardada'))});
test('ASR identity invalidates model changes and rejects malformed timing',()=>{assert.notEqual(alignmentKey('audio','hola',{model:'a'}),alignmentKey('audio','hola',{model:'b'}));assert.notEqual(alignmentKey('audio','hola',{aligner:'a'}),alignmentKey('audio','hola',{aligner:'b'}));assert.equal(validWords([{word:'Hola',start:1,end:2}],3),true);assert.equal(validWords([{word:'Hola',start:1,end:9}],3),false);assert.equal(validWords([],3),false)});
test('cache cleanup excludes approved keys and symlinks and rejects stale preview',async t=>{const root=await temp(t),dir=join(root,'.studio-state/scene-cache');await mkdir(dir,{recursive:true});const a='a'.repeat(64),b='b'.repeat(64),c='c'.repeat(64),old=new Date(Date.now()-40*86400000);for(const key of[a,b]){await writeFile(join(dir,key+'.mp4'),'data');await utimes(join(dir,key+'.mp4'),old,old)}await symlink(join(dir,a+'.mp4'),join(dir,c+'.mp4'));const options={protectedKeys:new Set([b])},plan=await inspectCache(root,options);assert.equal(plan.entries.length,1);await writeFile(join(dir,a+'.mp4'),'changed');await assert.rejects(cleanCache(root,plan.token,options),/cambió/);await utimes(join(dir,a+'.mp4'),old,old);const next=await inspectCache(root,options);assert.equal((await cleanCache(root,next.token,options)).removed_bytes,7);assert.equal(await readFile(join(dir,b+'.mp4'),'utf8'),'data');await assert.rejects(storagePreflight(root,{free:async()=>1}),e=>e.status===507)});
test('capabilities do not infer API permissions from a configured account',()=>{assert.equal(capability({brand_id:'comandpos',kind:'video',channel:'facebook'},[{channel:'facebook'}]).permission_status,'requiere_verificacion_en_proveedor');assert.equal(capability({brand_id:'other',kind:'video',channel:'facebook'},[{channel:'facebook'}]).supported,false);assert.equal(capability({brand_id:'comandpos',kind:'historia_social',channel:'tiktok'},[{channel:'tiktok'}]).supported,false)});
async function waitBatch(b,id,status){for(let i=0;i<100;i++){if(b.items.get(id).status===status)return;await new Promise(r=>setTimeout(r,10))}throw Error('Batch did not reach '+status)}
test('batch resumes only unfinished children and retains provider idempotency keys',async t=>{const root=await temp(t),calls=[],keys=[],jobs=new Map();let fail=true;const b=await new Batches(root,{budget:new Budget(join(root,'budget')),store:{get:id=>jobs.get(id),cancel:async id=>jobs.get(id).status='cancelled'},produce:async(input,key)=>{calls.push(input.kind);keys.push(key);if(input.kind==='imagen'&&fail){fail=false;throw Error('interrupted')}const job={id:'j-'+input.kind,status:'queued'};jobs.set(job.id,job);return {job}}}).init();const input={allow_paid:true,max_budget_usd:2.4,pieces:['video','carrusel','imagen','historia_social'].map((kind,i)=>({id:''+i,kind,brief:'Prueba',brand_id:'gcode',campaign_id:'c',concept_id:'x'}))};const first=await b.start(input,'key','admin');await waitBatch(b,first.id,'needs_review');await b.resume(first.id);await waitBatch(b,first.id,'submitted');assert.deepEqual(calls,['video','carrusel','imagen','imagen','historia_social']);assert.equal(keys[2],keys[3]);await b.start(input,'key','admin');const refreshed=await b.start(input,'new-ui-key','admin');assert.equal(refreshed.id,first.id);assert.equal(calls.length,5);await b.cancel(first.id,'admin');assert.ok([...jobs.values()].every(j=>j.status==='cancelled'))});
test('handoff retains timeline positions and subtitle word content',()=>{const xml=timelineXML({name:'A & B',fps:30,width:1080,height:1920,clips:[{file:'media/a.mp4',start:2,duration:3}]});assert.match(xml,/<name>A &amp; B<\/name>/);assert.match(xml,/<start>60<\/start>/);assert.match(xml,/<end>150<\/end>/);const srt=subtitleFile({escenas:[{dur:4,voz_inicio:.5,palabras:[{word:'Hola',start:0,end:1}]}]});assert.match(srt,/00:00:00,500 --> 00:00:01,500\nHola/)});

import {freezeEvidence} from './evidence.mjs';
test('storyboard cannot forge a human evidence review',()=>{const claim={id:'c',text:'Función',source:'Ficha',verified:true,reviewed_by:'admin'};assert.equal(freezeEvidence({evidence_claims:[claim]},{claims:[]})[0].verified,false);assert.equal(freezeEvidence({evidence_claims:[claim]},{claims:[claim]})[0].reviewed_by,'admin');assert.equal(freezeEvidence({evidence_claims:[{...claim,text:'Inventado'}]},{claims:[claim]})[0].verified,false)});
test('batch queued before a crash becomes recoverable; failed render retry relinks only its piece',async t=>{const root=await temp(t),dir=join(root,'.studio-state/batches');await mkdir(dir,{recursive:true});const id='a'.repeat(64),batch={id,status:'queued',children:[{piece_id:'p',job_id:'old',kind:'video'}]},links=[],jobs=new Map([['old',{id:'old',status:'failed'}]]);await writeFile(join(dir,id+'.json'),JSON.stringify(batch));let retries=0;const b=await new Batches(root,{budget:{},produce:async()=>{throw Error('Must not regenerate script')},store:{get:id=>jobs.get(id),retry:async()=>{retries++;const job={id:'new',status:'queued'};jobs.set(job.id,job);return {job}}},linkJob:async(...args)=>links.push(args)}).init();assert.equal(b.items.get(id).status,'interrupted');await b.retryChild(id,'p','admin');await b.retryChild(id,'p','admin');assert.equal(retries,1);assert.deepEqual(links,[['p','new','admin']]);assert.deepEqual(b.items.get(id).children[0].previous_jobs,['old']);assert.equal(b.items.get(id).children[0].job_id,'new')});
