import {test} from 'node:test'
import assert from 'node:assert/strict'
import {mkdtemp,rm} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {Marketing} from './marketing.mjs'
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'marketing-test-'));t.after(()=>rm(root,{recursive:true,force:true}));return {root,m:await new Marketing(root).init()}}
const job={id:'job-demo',brand_id:'comandpos',kind:'video',status:'succeeded',review:{status:'approved'},options:{preview:false},artifact:{duration:25}},store={get:()=>structuredClone(job)}
async function piece(m){const c=await m.saveCampaign({brand_id:'comandpos',name:'Pedidos claros',status:'active'},'admin');return m.savePiece({campaign_id:c.id,title:'Demostración',caption:'Conoce cómo funciona ComandPOS.',kind:'video',channel:'facebook',job_id:job.id,scheduled_at:new Date(Date.now()-60000).toISOString()},'admin',store)}
test('entrega requiere aprobación, no permite previews y claim concurrente es único',async t=>{const{m}=await fixture(t),p=await piece(m);await assert.rejects(m.schedule({piece_id:p.id},'admin',{get:()=>({...job,review:{status:'pending'}})}),/aprobada/);await assert.rejects(m.schedule({piece_id:p.id},'admin',{get:()=>({...job,options:{preview:true}})}),/aprobada/);const a=await m.schedule({piece_id:p.id},'admin',store),b=await m.schedule({piece_id:p.id},'admin',store);assert.equal(a.id,b.id);const claimed=await Promise.all(Array.from({length:6},()=>m.claim({channel:'facebook'},'n8n',store)));assert.equal(claimed.filter(Boolean).length,1);assert.equal(m.snapshot().deliveries[0].claim_token,undefined);await assert.rejects(m.savePiece({...p,title:'Cambio'},'admin',store),/curso/);await assert.rejects(m.result({id:a.id,claim_token:'wrong',status:'published'},'n8n'),/token/);const c=claimed.find(Boolean);await m.result({id:c.id,claim_token:c.claim_token,status:'uncertain'},'n8n');assert.equal(await m.claim({channel:'facebook'},'n8n',store),null)})
test('publicación confirmada y métricas persisten sin duplicarse',async t=>{const{root,m}=await fixture(t),p=await piece(m);await m.schedule({piece_id:p.id},'admin',store);const c=await m.claim({channel:'facebook'},'n8n',store);const result={id:c.id,claim_token:c.claim_token,status:'published',post_id:'123',url:'https://facebook.com/123'};await m.result(result,'n8n');await m.result(result,'n8n');const metric={delivery_id:c.id,at:'2026-09-30T12:00:00Z',views:100,leads:3};await m.addMetrics(metric,'n8n');await m.addMetrics(metric,'n8n');assert.equal(m.snapshot().metrics.length,1);const restored=await new Marketing(root).init();assert.equal(restored.snapshot().deliveries[0].status,'published');assert.equal(restored.snapshot().metrics[0].leads,3);await assert.rejects(m.addMetrics({...metric,views:-1},'n8n'),/inválida/);assert.equal(m.snapshot().metrics[0].views,100)})
test('campaña pausada y aprobación revocada impiden la entrega',async t=>{const{m}=await fixture(t),p=await piece(m);await m.schedule({piece_id:p.id},'admin',store);const c=m.snapshot().campaigns[0];await m.saveCampaign({...c,status:'paused'},'admin');assert.equal(await m.claim({channel:'facebook'},'n8n',store),null);await m.saveCampaign({...c,status:'active'},'admin');const claimed=await m.claim({channel:'facebook'},'n8n',{get:()=>({...job,review:{status:'rejected'}})});assert.equal(claimed.status,'blocked');assert.equal(claimed.claim_token,undefined)})
test('comentarios validan tiempo, marcas no mezclan archivos y errores no mutan estado',async t=>{const{m}=await fixture(t);await assert.rejects(m.addComment({job_id:job.id,second:30,text:'Fuera'},'editor',store),/Segundo/);assert.equal(m.snapshot().comments.length,0);const c=await m.addComment({job_id:job.id,second:4,text:'Aumentar texto'},'editor',store);await m.resolveComment({id:c.id,resolved:true},'editor');assert.equal(m.snapshot().comments[0].resolved,true);const campaign=await m.saveCampaign({brand_id:'gcode',name:'GCODE'},'admin');await assert.rejects(m.savePiece({campaign_id:campaign.id,title:'Otra marca',kind:'video',channel:'facebook',job_id:job.id},'admin',store),/marca/);assert.equal(m.snapshot().pieces.length,0)})
test('fechas de creación son inmutables y publicación usa el recibo del proveedor',async t=>{const{m}=await fixture(t),p=await piece(m);assert.ok(p.created_at);const edited=await m.savePiece({...p,title:'Título editado',created_at:'2000-01-01'},'admin',store);assert.equal(edited.created_at,p.created_at);const campaign=m.snapshot().campaigns[0];await m.saveCampaign({...campaign,name:'Campaña editada',created_at:'2000-01-01'},'admin');assert.equal(m.snapshot().campaigns[0].created_at,campaign.created_at);await m.schedule({piece_id:p.id},'admin',store);const d=await m.claim({channel:'facebook'},'n8n',store),stamp=new Date(Date.now()-45000).toISOString();const r=await m.result({id:d.id,claim_token:d.claim_token,status:'published',post_id:'receipt',url:'https://facebook.com/receipt',published_at:stamp},'n8n');assert.equal(r.published_at,stamp);assert.ok(r.confirmed_at>=r.published_at);const again=await m.result({id:d.id,claim_token:d.claim_token,status:'published',post_id:'receipt',url:r.url},'n8n');assert.equal(again.published_at,stamp);assert.equal(again.confirmed_at,r.confirmed_at)})
