import {mkdir,readFile,writeFile,rename,stat} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID,createHash} from 'node:crypto'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
const run=promisify(execFile),now=()=>new Date().toISOString(),fail=(s,m)=>Object.assign(Error(m),{status:s})
const text=(v,max=2000)=>{if(typeof v!=='string'||v.length>max)throw fail(422,'Texto inválido');return v.trim()}
const id=()=>randomUUID(),channels=['instagram','facebook','tiktok','youtube'],kinds=['video','imagen','carrusel','historia_social']
export class Marketing {
 constructor(root){this.root=root;this.dir=join(root,'.studio-state','marketing');this.serial=Promise.resolve()}
 async init(){await mkdir(join(this.dir,'assets'),{recursive:true,mode:0o700});try{this.data=JSON.parse(await readFile(join(this.dir,'state.json'),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e;this.data={brands:[{id:'comandpos',name:'ComandPOS by GCODE',audience:'Restaurantes en República Dominicana',tone:'Español dominicano, cercano y profesional',cta:'Solicita tu demo',website:'https://comandpos.com',contact:'+1 849 540 6093',primary:'#14233b',accent:'#ff6b35',facts:'Registro de pedidos y modificadores. Envío de comandas a cocina. Gestión de mesas y cuentas. Consulta de reportes.',restrictions:'No inventar testimonios ni resultados. Identificar datos ilustrativos.'},{id:'gcode',name:'GCODE Digital',audience:'Negocios de República Dominicana',tone:'Claro, cercano y profesional',cta:'Conversemos sobre tu proyecto',website:'https://gcoderd.com',contact:'+1 849 540 6093',primary:'#2e4fe0',accent:'#18c9e8',facts:'GCODE Digital gestiona el marketing y las automatizaciones de ComandPOS. ComandPOS es su producto de gestión de negocios.',restrictions:'Completar servicios y evidencia antes de generar afirmaciones.'}],campaigns:[],pieces:[],assets:[],comments:[],deliveries:[],metrics:[],audit:[]};await this.persist()}return this}
 async persist(){const tmp=join(this.dir,'state-'+id()+'.tmp');await writeFile(tmp,JSON.stringify(this.data),{mode:0o600});await rename(tmp,join(this.dir,'state.json'))}
 tx(actor,action,fn){const next=this.serial.then(async()=>{const before=structuredClone(this.data);try{const result=await fn();this.data.audit.push({at:now(),actor,action});this.data.audit=this.data.audit.slice(-2000);await this.persist();return structuredClone(result)}catch(e){this.data=before;throw e}});this.serial=next.catch(()=>{});return next}
 snapshot(){return structuredClone({...this.data,deliveries:this.data.deliveries.map(({claim_token,...d})=>d),audit:this.data.audit.slice(-60)})}
 brand(id){const b=this.data.brands.find(b=>b.id===id);if(!b)throw fail(404,'Marca no encontrada');return structuredClone(b)}
 saveBrand(d,actor){return this.tx(actor,'brand.save',()=>{if(!/^[a-z0-9-]{2,40}$/.test(d.id||''))throw fail(422,'Identificador de marca inválido');const b={id:d.id};if(d.logo_resource_id){const logo=this.data.assets.find(a=>a.id===d.logo_resource_id&&a.brand_id===d.id&&a.type==='image');if(!logo)throw fail(422,'Logo no disponible para esta marca');b.logo_resource_id=logo.id}for(const k of ['name','audience','tone','cta','website','contact','facts','restrictions'])b[k]=text(d[k]||'',k==='facts'?10000:2000);if(!b.name)throw fail(422,'Falta el nombre');if(b.website&&!/^https:\/\//.test(b.website))throw fail(422,'Usa un sitio HTTPS');for(const k of ['primary','accent']){if(!/^#[a-f0-9]{6}$/i.test(d[k]||''))throw fail(422,'Color inválido');b[k]=d[k]}const i=this.data.brands.findIndex(x=>x.id===b.id);if(i<0)this.data.brands.push(b);else this.data.brands[i]=b;return b})}
 saveCampaign(d,actor){return this.tx(actor,'campaign.save',()=>{this.brand(d.brand_id);if(!['draft','active','paused','completed'].includes(d.status||'draft'))throw fail(422,'Estado inválido');const previous=this.data.campaigns.find(x=>x.id===d.id);const c={id:d.id||id(),created_at:previous?previous.created_at||null:now(),brand_id:d.brand_id,name:text(d.name,150),objective:text(d.objective||''),audience:text(d.audience||''),offer:text(d.offer||''),status:d.status||'draft',start:text(d.start||'',10),end:text(d.end||'',10),updated_at:now()};if(!c.name)throw fail(422,'Falta el nombre de campaña');for(const k of ['start','end'])if(c[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(c[k]))throw fail(422,'Fecha inválida');if(c.start&&c.end&&c.start>c.end)throw fail(422,'Fechas invertidas');const i=this.data.campaigns.findIndex(x=>x.id===c.id);if(d.id&&i<0)throw fail(404,'Campaña no encontrada');if(i<0)this.data.campaigns.push(c);else this.data.campaigns[i]=c;return c})}
 savePiece(d,actor,store){return this.tx(actor,'piece.save',()=>{const c=this.data.campaigns.find(c=>c.id===d.campaign_id);if(!c)throw fail(404,'Campaña no encontrada');if(!kinds.includes(d.kind)||!channels.includes(d.channel))throw fail(422,'Formato o canal inválido');const previous=this.data.pieces.find(x=>x.id===d.id);if(d.id&&!previous)throw fail(404,'Pieza no encontrada');if(previous&&this.data.deliveries.some(x=>x.piece_id===previous.id&&['scheduled','claimed','published','uncertain'].includes(x.status)))throw fail(409,'La entrega está programada, en curso o publicada; cancela la programación antes de editar');const p={id:d.id||id(),created_at:previous?previous.created_at||null:now(),campaign_id:c.id,brand_id:c.brand_id,title:text(d.title,160),kind:d.kind,channel:d.channel,brief:text(d.brief||''),caption:text(d.caption||'',2200),scheduled_at:d.scheduled_at?new Date(d.scheduled_at).toISOString():null,job_id:d.job_id||null,updated_at:now()};if(!p.title)throw fail(422,'Falta el título');if(p.job_id){const j=store.get(p.job_id);if(j.brand_id!==p.brand_id||j.kind!==p.kind)throw fail(422,'El archivo no corresponde a la marca o formato')}if(previous)Object.assign(previous,p);else this.data.pieces.push(p);return p})}
 addComment(d,actor,store){return this.tx(actor,'comment.add',()=>{const j=store.get(d.job_id);if(d.second!=null&&(!Number.isFinite(d.second)||d.second<0||d.second>(j.artifact?.duration||180)))throw fail(422,'Segundo inválido');const c={id:id(),job_id:d.job_id,second:d.second??null,text:text(d.text,1500),actor,at:now(),resolved:false};if(!c.text)throw fail(422,'Escribe un comentario');this.data.comments.push(c);return c})}
 resolveComment(d,actor){return this.tx(actor,'comment.resolve',()=>{const c=this.data.comments.find(x=>x.id===d.id);if(!c)throw fail(404,'Comentario no encontrado');c.resolved=d.resolved===true;return c})}
 async upload(meta,bytes,actor){this.brand(meta.brand_id);if(!Buffer.isBuffer(bytes)||bytes.length<1||bytes.length>60*1024*1024)throw fail(413,'Archivo: máximo 60 MB');if(meta.rights_confirmed!==true)throw fail(422,'Confirma que puedes usar este recurso');const hash=createHash('sha256').update(bytes).digest('hex');const extension=String(meta.filename||'').split('.').at(-1).toLowerCase();if(!['jpg','jpeg','png','webp','mp4','mov','mp3','wav'].includes(extension))throw fail(422,'Formato no admitido');const filename=hash+'.'+extension,file=join(this.dir,'assets',filename);await writeFile(file,bytes,{mode:0o600});let info;try{info=JSON.parse((await run('ffprobe',['-v','error','-show_entries','format=duration:stream=codec_type,width,height','-of','json',file],{timeout:20000,maxBuffer:100000})).stdout)}catch{throw fail(422,'No se pudo leer el archivo multimedia')}const visual=info.streams?.find(s=>s.codec_type==='video'),audio=info.streams?.find(s=>s.codec_type==='audio'),type=['jpg','jpeg','png','webp'].includes(extension)?'image':visual?'video':audio?'audio':null;if(!type||((type==='video'||type==='audio')&&!(Number(info.format?.duration)>0)))throw fail(422,'Archivo multimedia inválido');return this.tx(actor,'asset.upload',()=>{const old=this.data.assets.find(a=>a.hash===hash&&a.brand_id===meta.brand_id);if(old)return old;const a={id:id(),brand_id:meta.brand_id,name:text(meta.name||meta.filename,160),filename,hash,type,width:visual?.width,height:visual?.height,duration:Number(info.format?.duration)||null,tags:text(meta.tags||'',300),rights:text(meta.rights||'Uso confirmado por '+actor,500),at:now()};this.data.assets.push(a);return a})}
 asset(id){const a=this.data.assets.find(a=>a.id===id);if(!a)throw fail(404,'Recurso no encontrado');return {meta:structuredClone(a),path:join(this.dir,'assets',a.filename)}}
 cancelDelivery(d,actor){return this.tx(actor,'delivery.cancel',()=>{const x=this.data.deliveries.find(x=>x.id===d.id);if(!x||!['scheduled','blocked','missed'].includes(x.status))throw fail(409,'Solo puedes cancelar entregas que no hayan comenzado');x.status='cancelled';x.updated_at=now();return x})}
 schedule(d,actor,store){return this.tx(actor,'delivery.schedule',()=>{const p=this.data.pieces.find(x=>x.id===d.piece_id);if(!p?.job_id||!p.scheduled_at)throw fail(422,'Asocia un archivo y una fecha');if(Date.parse(p.scheduled_at)<Date.now()-5*60000)throw fail(422,'Elige una fecha futura para programar');const c=this.data.campaigns.find(x=>x.id===p.campaign_id);if(c.status!=='active')throw fail(409,'Activa la campaña para programar');if(!['comandpos','gcode'].includes(p.brand_id)||p.channel==='youtube')throw fail(422,'Falta conectar una cuenta publicadora para esta marca o canal');if(p.channel==='tiktok'&&p.kind==='historia_social')throw fail(422,'Elige imagen o video de feed para TikTok');if(!p.caption.trim())throw fail(422,'Escribe el texto de publicación');const j=store.get(p.job_id);if(j.status!=='succeeded'||j.review.status!=='approved'||j.options?.preview)throw fail(409,'Se requiere una exportación final aprobada');const old=this.data.deliveries.find(x=>x.piece_id===p.id&&!['cancelled','failed'].includes(x.status));if(old)return old;if(this.data.deliveries.some(x=>x.channel===p.channel&&x.job_id===p.job_id&&!['cancelled','failed','blocked'].includes(x.status)))throw fail(409,'Este archivo ya tiene una entrega en este canal');const delivery={id:id(),piece_id:p.id,job_id:p.job_id,brand_id:p.brand_id,channel:p.channel,caption:p.caption,scheduled_at:p.scheduled_at,status:'scheduled',at:now()};this.data.deliveries.push(delivery);return delivery})}
 claim(d,actor,store){return this.tx(actor,'delivery.claim',()=>{if(!channels.includes(d.channel))throw fail(422,'Canal inválido');for(const old of this.data.deliveries)if(old.status==='scheduled'&&Date.parse(old.scheduled_at)<Date.now()-24*3600000){old.status='missed';old.error='La fecha pasó hace más de 24 horas; reprograma la pieza'}const x=this.data.deliveries.find(x=>x.channel===d.channel&&x.status==='scheduled'&&x.scheduled_at<=now()&&this.data.campaigns.find(c=>c.id===this.data.pieces.find(p=>p.id===x.piece_id)?.campaign_id)?.status==='active');if(!x)return null;const j=store.get(x.job_id);if(j.status!=='succeeded'||j.review.status!=='approved'||j.options?.preview){x.status='blocked';return {id:x.id,status:'blocked'}}x.status='claimed';x.claim_token=id();x.claimed_at=now();return {...x,job:j}})}
 result(d,actor){return this.tx(actor,'delivery.result',()=>{
  const x=this.data.deliveries.find(x=>x.id===d.id);if(!x||x.claim_token!==d.claim_token)throw fail(403,'Entrega o token inválido');
  let publishedAt=null;if(d.status==='published'&&d.published_at!=null){const stamp=Date.parse(d.published_at);if(!Number.isFinite(stamp)||stamp>Date.now()+300000)throw fail(422,'Fecha de publicación inválida');publishedAt=new Date(stamp).toISOString()}
  if(x.status==='published'){if(d.status==='published'&&d.post_id===x.post_id){if(!x.published_at&&publishedAt)x.published_at=publishedAt;return x}throw fail(409,'Entrega ya publicada')}
  if(!['claimed','uncertain'].includes(x.status)||!['published','failed','uncertain'].includes(d.status))throw fail(409,'Transición inválida');
  if(d.status==='published'&&(!d.post_id||!/^https:\/\//.test(d.url||'')))throw fail(422,'Falta el ID o enlace de la publicación');
  Object.assign(x,{...(d.status==='published'?{published_at:publishedAt,confirmed_at:now()}:{}),status:d.status,post_id:text(d.post_id||'',250),url:text(d.url||'',1000),error:text(d.error||'',1500),updated_at:now()});return x
 })}
 addMetrics(d,actor){return this.tx(actor,'metrics.record',()=>{const x=this.data.deliveries.find(x=>x.id===d.delivery_id&&x.status==='published');if(!x)throw fail(422,'Primero registra la publicación');const m={delivery_id:x.id,at:d.at?new Date(d.at).toISOString():now(),source:text(d.source||actor,100)};for(const k of ['views','reach','likes','comments','shares','saves','clicks','leads','demos','sales','watch_seconds','completion_rate'])if(d[k]!=null){if(!Number.isFinite(d[k])||d[k]<0||(k==='completion_rate'&&d[k]>1))throw fail(422,'Métrica inválida');m[k]=d[k]}const index=this.data.metrics.findIndex(v=>v.delivery_id===m.delivery_id&&v.at===m.at);if(index<0)this.data.metrics.push(m);else this.data.metrics[index]=m;return m})}
}
