// Brand composition: deterministic, responsive scenes with distinct narrative roles.
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const previousSeek=window.seek,previousPrepare=window.preparar;let story={},players=new Map();
const measure=document.createElement('canvas').getContext('2d');
function wrap(text,width,size,weight=800){measure.font=`${weight} ${size}px Montserrat`;const rows=[];let row='';for(const word of String(text||'').split(/\s+/)){if(!word)continue;if(measure.measureText(row?row+' '+word:word).width<=width){row=row?row+' '+word:word;continue}if(row)rows.push(row);row=word}if(row)rows.push(row);return rows}
function diagram(topic,x,y,w,h,accent,ink,t,paper){const subject=/cocin|comanda/i.test(topic)?'cocina':/pedido|modificador/i.test(topic)?'pedido':/reporte|venta/i.test(topic)?'reporte':/mesa|cuenta/i.test(topic)?'mesa':'marca';const fill=paper?'#ffffff':'#20354e',fade=Math.min(1,t/.8);let out=`<g opacity="${fade}" transform="translate(${x},${y+(1-fade)*24})"><rect width="${w}" height="${h}" rx="26" fill="${fill}" stroke="${accent}" stroke-opacity=".22"/>`;out+=block(subject==='marca'?'Una idea, bien explicada':subject==='reporte'?'Consulta de reportes':subject==='mesa'?'Gestión de mesas':subject==='cocina'?'Comanda a cocina':'Registro de pedidos',30,22,w-60,65,30,ink);if(subject==='mesa'){for(let i=0;i<4;i++){const px=30+(i%2)*(w-45)/2,py=110+Math.floor(i/2)*Math.max(60,(h-175)/2);out+=`<rect x="${px}" y="${py}" width="${(w-90)/2}" height="${Math.max(45,(h-220)/2)}" rx="14" fill="${accent}" opacity="${.12+.08*Math.sin(t+i)}"/>`+block('Mesa '+(i+1),px+18,py+5,(w-120)/2,55,24,ink)}}else{const labels=subject==='pedido'?['Pedido','Modificadores','Consulta']:subject==='cocina'?['Comanda','Detalle del pedido','Cocina']:subject==='reporte'?['Ventas','Canales','Información del negocio']:['Mensaje','Diseño','Revisión'];for(let i=0;i<3;i++){const py=85+i*Math.max(32,(h-140)/3);out+=`<rect x="30" y="${py}" width="${w-60}" height="${Math.max(28,(h-165)/3)}" rx="12" fill="${accent}" opacity="${.08+Math.max(0,Math.sin(t*1.7-i))*.13}"/><circle cx="55" cy="${py+17}" r="7" fill="${accent}"/>`+block(labels[i],78,py,w-115,35,22,ink)}}out+=block('ESQUEMA ILUSTRATIVO',30,h-47,w-60,35,17,ink,600);return out+'</g>'}
function block(text,x,y,width,height,size,color,weight=800){let rows;do{rows=wrap(text,width,size,weight);if(rows.length*size*1.22<=height)break;size-=2}while(size>24);return rows.map((row,i)=>`<text data-role="content" x="${x}" y="${y+size+i*size*1.22}" fill="${esc(color)}" font-family="Montserrat" font-size="${size}" font-weight="${weight}">${esc(row)}</text>`).join('')}
window.preparar=async sb=>{story=sb;await previousPrepare(sb);for(const v of players.values())v.remove();players.clear();const logo=sb.brand?.logo_url||(sb.brand?.logo_resource_id?'/api/library/'+sb.brand.logo_resource_id:null);if(logo){const img=new Image();img.src=logo;await img.decode()}
 for(const scene of sb.escenas){if(scene.tipo!=='media')continue;const url=scene.media_url||(scene.resource_id?'/api/library/'+scene.resource_id:null);if(!url)continue;if(scene.media_kind==='video'){const video=document.createElement('video');video.src=url;video.muted=true;video.preload='auto';video.playsInline=true;video.style.cssText='position:absolute;display:none;pointer-events:none;object-fit:contain;border-radius:24px';document.body.insertBefore(video,document.body.firstChild);await new Promise((ok,no)=>{video.onloadedmetadata=ok;video.onerror=()=>no(Error('No se pudo cargar el clip'));if(video.readyState>=1)ok()});players.set(url,video)}else{const img=new Image();img.src=url;await img.decode()}}
 return true};
window.seek=async t=>{previousSeek(t);let start=0,scene,index=0;for(const [i,e]of (story.escenas||[]).entries()){if(t<start+e.dur){scene=e;index=i;break}start+=e.dur}scene||=story.escenas?.at(-1);for(const video of players.values())video.style.display='none';if(!scene)return;
 const stage=document.querySelector('#stage'),W=stage.viewBox.baseVal.width,H=stage.viewBox.baseVal.height;
 if(scene.tipo==='media'){
 const brand=story.brand||{name:'ComandPOS',primary:'#14233b',accent:'#ff6b35'},wide=W>H,short=H<=1350,margin=wide?100:80,top=H>1500?210:110,bottom=H>1500?310:130;
 const elapsed=Math.max(0,t-start),enter=1-Math.pow(1-Math.min(1,elapsed/.6),3),last=scene.role==='closing'||index===story.escenas.length-1;
 const family=scene.family||story.design_family||(scene.layout==='cards'||scene.layout==='split'?'paper':'editorial');
 const paper=family==='paper',bg=paper?'#f6f0e4':brand.primary,ink=paper?'#17283d':'#ffffff',muted=paper?'#485568':'#ccd5df',accent=brand.accent;
 const url=scene.media_url||(scene.resource_id?'/api/library/'+scene.resource_id:null),video=players.get(url),hasMedia=!!url;
 const tx=margin,ty=top+65,tw=wide?W*.43:W-margin*2,th=wide?H*.34:hasMedia?H*.19:short?H*.20:H*.23;
 const visual={x:wide?W*.54:margin,y:wide?top+45:ty+th+45,w:wide?W*.40:W-margin*2,h:wide?H-top-bottom-120:Math.max(170,H-bottom-ty-th-270)};
 let html=`<rect width="${W}" height="${H}" fill="${esc(bg)}"/>`;
 if(paper)html+=`<path d="M0 ${H*.52} L${W*.35} ${H*.48} L${W} ${H*.54} V${H} H0Z" fill="#ece2d0"/><rect x="${W-110}" y="${top-25}" width="35" height="180" rx="7" fill="${esc(accent)}" transform="rotate(12 ${W-95} ${top})" opacity=".5"/>`;
 else html+=`<circle cx="${W*.85+Math.sin(elapsed*.6)*18}" cy="${H*.25}" r="${W*.42}" fill="${esc(accent)}" opacity=".09"/><path d="M0 ${H*.8} Q${W*.5} ${H*.55} ${W} ${H*.7}" fill="none" stroke="white" stroke-width="2" opacity=".07"/>`;
 const logo=brand.logo_url||(brand.logo_resource_id?'/api/library/'+brand.logo_resource_id:null);
 if(logo)html+=`<rect x="${margin-12}" y="${top-85}" width="360" height="90" rx="14" fill="${esc(brand.primary)}"/><image href="${esc(logo)}" x="${margin}" y="${top-75}" width="325" height="65" preserveAspectRatio="xMinYMid meet"/>`;
 else html+=block(brand.name,margin,top-75,W*.65,65,30,ink);
 const label=last?'CONOCE MÁS':scene.layout==='steps'?'PASO '+(scene.step||index+1):scene.layout==='question'&&index===0?'UNA PREGUNTA':scene.layout==='cards'?'IDEA '+(index+1):'PARA TU NEGOCIO';
 html+=`<rect x="${margin}" y="${top+10}" width="${Math.min(tw,360)}" height="6" rx="3" fill="${esc(accent)}"/>`+block(label,margin,top+22,tw,40,21,muted,700);
 html+=`<g opacity="${enter}" transform="translate(0 ${(1-enter)*25})">`+block(scene.titulo,tx,ty,tw,th,wide?72:short?66:80,ink,900)+'</g>';
 if(hasMedia){
 html+=`<rect x="${visual.x-10}" y="${visual.y-10}" width="${visual.w+20}" height="${visual.h+20}" rx="30" fill="${paper?'#ffffff':'#ffffff12'}" stroke="${paper?'#ded2bf':'#ffffff25'}" stroke-width="2"/>`;
 if(video){video.style.display='block';Object.assign(video.style,{left:visual.x+'px',top:visual.y+'px',width:visual.w+'px',height:visual.h+'px',objectFit:scene.fit||'contain',objectPosition:`${scene.focus_x??50}% ${scene.focus_y??50}%`});const target=Math.min((scene.clip_start||0)+elapsed,video.duration-.04);if(Math.abs(video.currentTime-target)>.005)await new Promise((ok,no)=>{const timer=setTimeout(()=>{video.removeEventListener('seeked',done);no(Error('El clip no pudo posicionarse'))},5000);function done(){clearTimeout(timer);ok()}video.addEventListener('seeked',done,{once:true});video.currentTime=target});
 // The SVG background needs an aperture over the underlying HTML video.
 html=`<defs><mask id="clip-window"><rect width="${W}" height="${H}" fill="white"/><rect x="${visual.x}" y="${visual.y}" width="${visual.w}" height="${visual.h}" rx="24" fill="black"/></mask></defs><g mask="url(#clip-window)">${html}</g>`;
 }else html+=`<image href="${esc(url)}" x="${visual.x}" y="${visual.y}" width="${visual.w}" height="${visual.h}" preserveAspectRatio="${scene.fit==='cover'?'xMidYMid slice':'xMidYMid meet'}"/>`;
 }else if(wide){html+=`<rect x="${visual.x}" y="${visual.y}" width="${visual.w}" height="${visual.h}" rx="26" fill="${paper?'#ffffff':'#ffffff09'}"/>`+block(last?(brand.cta||'Conversemos'):scene.layout==='question'&&index===0?'?':String(index+1).padStart(2,'0'),visual.x+40,visual.y+35,visual.w-80,visual.h-70,last?54:160,accent,900)}
 if(!hasMedia&&!wide&&!last){const dy=ty+th+210,dh=Math.max(200,H-bottom-150-dy);html+=diagram(story.editorial_topic||scene.titulo+' '+scene.texto,margin,dy,W-2*margin,dh,accent,ink,elapsed,paper)}
 const bodyY=wide?ty+th+45:hasMedia?visual.y+visual.h+24:ty+th+50;
 html+=block(scene.texto,margin,bodyY,wide?tw:W-2*margin,wide?155:140,wide?36:short?36:44,muted,600);
 const captionY=H-bottom-65,voiceTime=elapsed-(scene.voz_inicio??.35),words=scene.palabras||[],active=words.findIndex(w=>voiceTime>=w.start&&voiceTime<=w.end);
 if(story.subtitulos&&active>=0){const group=words.slice(Math.floor(active/4)*4,Math.floor(active/4)*4+4);let font=short?38:46;measure.font=`800 ${font}px Montserrat`;let total=group.reduce((n,w)=>n+measure.measureText(w.word+' ').width,0);while(total>W-2*margin&&font>24){font-=2;measure.font=`800 ${font}px Montserrat`;total=group.reduce((n,w)=>n+measure.measureText(w.word+' ').width,0)}let x=(W-total)/2;html+=`<rect x="${Math.max(margin-20,x-22)}" y="${captionY-font}" width="${Math.min(W-2*margin+40,total+44)}" height="${font+32}" rx="14" fill="${paper?'#e4d8c4':'#081220'}"/>`;for(const word of group){html+=`<text data-role="caption" x="${x}" y="${captionY}" fill="${voiceTime>=word.start&&voiceTime<=word.end?esc(accent):esc(ink)}" font-family="Montserrat" font-size="${font}" font-weight="800">${esc(word.word)}</text>`;x+=measure.measureText(word.word+' ').width}}
 const footerY=H-bottom+45;html+=`<rect x="${margin}" y="${footerY-40}" width="${W-2*margin}" height="2" fill="${esc(accent)}" opacity=".6"/>`+block(last?(brand.contact||scene.cta||brand.cta):(scene.cta||brand.cta),margin,footerY-20,W-2*margin,70,30,ink,700);
 html+=`<rect x="${margin}" y="${H-bottom+110}" width="${(W-2*margin)*Math.min(1,elapsed/scene.dur)}" height="4" fill="${esc(accent)}"/>`;
 stage.innerHTML=html;
 }else if(scene.design){for(const el of stage.querySelectorAll('text'))if(Number(el.getAttribute('font-size'))>=64&&Number(el.getAttribute('y'))<650)el.setAttribute('transform',`translate(${scene.design.dx||0} ${scene.design.dy||0}) scale(${scene.design.scale||1})`)}
 if(scene.overlay){const o=scene.overlay,el=document.createElementNS('http://www.w3.org/2000/svg','text');for(const [key,value]of Object.entries({x:o.x,y:o.y,fill:o.color||'#ffffff','font-size':o.size||48,'font-family':'Montserrat','font-weight':800}))el.setAttribute(key,value);el.textContent=o.text;stage.append(el)}
};
})();
