import './fontconfig.mjs'
import sharp from 'sharp'
import {readFile} from 'node:fs/promises'
import {join} from 'node:path'
const esc=x=>String(x||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
async function lines(text,size,max=920){const out=[];for(const word of String(text).split(/\s+/)){const next=out.length?out.at(-1)+' '+word:word;const m=await sharp({text:{text:esc(next),font:'Montserrat Bold '+size,rgba:true}}).metadata();if(m.width>max&&out.length)out.push(word);else if(out.length)out[out.length-1]=next;else out.push(word)}for(const line of out){const m=await sharp({text:{text:esc(line),font:'Montserrat Bold '+size,rgba:true}}).metadata();if(m.width>max)throw Error('Texto demasiado ancho para la historia')}return out}
export async function renderVisualStory(s,dir){
 const b=JSON.parse(await readFile(join(dir,'brand-profile.json'),'utf8'));
 if(b.id!==s.brand_id||!s.resource_id||!b.logo_resource_id)throw Error('Faltan recursos de la marca para esta historia');
 const primary=/^#[a-f0-9]{6}$/i.test(b.primary)?b.primary:'#14233b',accent=/^#[a-f0-9]{6}$/i.test(b.accent)?b.accent:'#ff6b35';
 const title=await lines(s.titular,62),body=await lines(s.subtitulo,32),cta=await lines(s.cta,32,820);
 if(title.length>3||body.length>3||cta.length>1)throw Error('Acorta el texto para que la historia sea legible');
 const points=[];for(const p of s.editorial.points){const wrapped=await lines(p,30,800);if(wrapped.length>2)throw Error('Acorta los puntos de la historia');points.push(wrapped)}
 const photo=await sharp(await readFile(join(dir,'brand-photo'))).resize(900,860,{fit:'contain',background:'white'}).jpeg({quality:95}).toBuffer();
 const logo=await sharp(await readFile(join(dir,'brand-logo'))).resize(310,80,{fit:'inside'}).png().toBuffer(),lm=await sharp(logo).metadata();
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="white"/><image href="data:image/jpeg;base64,${photo.toString('base64')}" x="90" y="520" width="900" height="860"/><rect x="345" y="180" width="390" height="110" rx="24" fill="${primary}"/><image href="data:image/png;base64,${logo.toString('base64')}" x="${(1080-lm.width)/2}" y="${195+(80-lm.height)/2}" width="${lm.width}" height="${lm.height}"/><text x="540" y="335" text-anchor="middle" font-family="Montserrat" font-size="20" font-weight="700" fill="${accent}">${s.editorial.hour===13?'UN CONSEJO PARA TU OPERACIÓN':'CONOCE COMANDPOS'}</text>${title.map((t,i)=>`<text x="540" y="${412+i*74}" text-anchor="middle" font-family="Montserrat" font-size="62" font-weight="900" fill="${primary}">${esc(t)}</text>`).join('')}${body.map((t,i)=>`<text x="540" y="${442+title.length*74+i*43}" text-anchor="middle" font-family="Montserrat" font-size="32" fill="${primary}">${esc(t)}</text>`).join('')}${points.map((p,i)=>`<circle cx="113" cy="${1270+i*65}" r="7" fill="${accent}"/>${p.map((t,k)=>`<text x="140" y="${1280+i*65+k*32}" font-family="Montserrat" font-size="30" font-weight="600" fill="${primary}">${esc(t)}</text>`).join('')}`).join('')}<rect x="100" y="1480" width="880" height="82" rx="24" fill="${accent}"/><text x="540" y="1534" text-anchor="middle" font-family="Montserrat" font-size="32" font-weight="800" fill="white">${esc(s.cta)}</text><text x="540" y="1610" text-anchor="middle" font-family="Montserrat" font-size="23" fill="${primary}">${esc((b.website||b.contact||'').replace('https://',''))}</text><text x="540" y="1642" text-anchor="middle" font-family="Montserrat" font-size="17" fill="${primary}">Escena ilustrativa</text></svg>`;
 return {buffer:await sharp(Buffer.from(svg)).jpeg({quality:95}).toBuffer(),metrics:{width:1080,height:1920,safe_top:180,safe_bottom:250,title_lines:title.length,body_lines:body.length,visual_line:s.editorial.visual_line,photo_fit:'contain',additional_generation_cost_usd:0}};
}
