import {statfs,lstat,readdir,readFile,unlink,mkdir} from 'node:fs/promises';import {join,dirname,resolve} from 'node:path';import {createHash} from 'node:crypto';
export async function freeDiskBytes(path,fs=statfs){let target=resolve(path);for(;;){try{const s=await fs(target);return Number(s.bavail)*Number(s.bsize)}catch(e){if(e.code!=='ENOENT'||dirname(target)===target)throw e;target=dirname(target)}}}
export async function storagePreflight(path,{seconds=0,free=freeDiskBytes}={}){const required=256*1024*1024+Math.ceil(seconds)*1024*1024,available=await free(path);if(available<required)throw Object.assign(Error('Espacio insuficiente antes de generar. Libera caché desde Operaciones.'),{status:507});return {available,required}}
export async function inspectCache(root,{days=30,protectedKeys=new Set()}={}){if(!Number.isInteger(days)||days<1)throw Error('Antigüedad inválida');const dir=join(root,'.studio-state','scene-cache');await mkdir(dir,{recursive:true});const entries=[];let total=0;for(const name of await readdir(dir)){if(!/^[a-f0-9]{64}\.(mp4|json)$/.test(name))continue;const s=await lstat(join(dir,name));if(!s.isFile()||s.isSymbolicLink())continue;total+=s.size;if(!protectedKeys.has(name.split('.')[0])&&s.mtimeMs<Date.now()-days*86400000)entries.push({name,bytes:s.size,ino:s.ino,mtime:s.mtimeMs})}entries.sort((a,b)=>a.name.localeCompare(b.name));return {total_bytes:total,available_bytes:await freeDiskBytes(dir),candidate_bytes:entries.reduce((n,e)=>n+e.bytes,0),entries,token:createHash('sha256').update(JSON.stringify(entries)).digest('hex')}}
export async function cleanCache(root,token,options){const plan=await inspectCache(root,options);if(plan.token!==token)throw Object.assign(Error('La caché cambió: revisa de nuevo el diagnóstico'),{status:409});let bytes=0;for(const e of plan.entries){const path=join(root,'.studio-state','scene-cache',e.name),s=await lstat(path);if(s.ino!==e.ino||s.mtimeMs!==e.mtime||s.size!==e.bytes||!s.isFile()||s.isSymbolicLink())continue;await unlink(path);bytes+=e.bytes}return {removed_bytes:bytes}}
export async function protectedCacheKeys(store){const keys=new Set();for(const j of store.jobs.values()){if(j.status!=='succeeded'||j.review?.status!=='approved')continue;try{const m=JSON.parse(await readFile(store.artifactPath(j.id,'manifest'),'utf8'));for(const s of m.cache?.segments||[])keys.add(s.key)}catch{}}return keys}

// Capacity of the filesystem backing Studio data, including other files on that volume.
export async function diskUsage(path,{fs=statfs,now=()=>new Date()}={}){
 const s=await fs(path),total=Number(s.blocks)*Number(s.bsize),free=Number(s.bfree)*Number(s.bsize),available=Number(s.bavail)*Number(s.bsize);
 if(![total,free,available].every(Number.isSafeInteger)||total<=0||available<0||available>free||free>total)throw Error('Capacidad del disco no disponible');
 const used=total-free,reserved=free-available,percent=used/total*100,unavailable=(total-available)/total*100;
 return {total_bytes:total,used_bytes:used,available_bytes:available,reserved_bytes:reserved,used_percent:Math.round(percent*10)/10,status:available<2*1024**3||unavailable>=95?'critical':available<5*1024**3||unavailable>=85?'warning':'ok',checked_at:now().toISOString(),scope:'studio_data_filesystem'};
}
