(()=>{
const paths={home:'M3 10l9-7 9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z',video:'M15 8l6-3v14l-6-3M3 5h12v14H3z',image:'M3 3h18v18H3zM3 16l6-6 5 5 3-3 4 4M8 7h.01',spark:'M12 3l2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z',user:'M20 21v-2a7 7 0 0 0-14 0v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',plus:'M12 5v14M5 12h14',arrow:'M9 5l7 7-7 7',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',menu:'M4 6h16M4 12h16M4 18h16'};
window.studioIcon=(name,size=18)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
const page=document.body.dataset.page||'home',names={home:'Inicio',editor:'Editor de video',feed:'Imágenes y carruseles',create:'Nueva pieza',account:'Cuenta',marketing:'Marketing',ads:'Publicidad',images:'Generación de imágenes'};
const nav=(id,url,icon,label)=>`<a class="nav-item ${page===id?'active':''}" href="${url}" ${page===id?'aria-current="page"':''}>${studioIcon(icon)}${label}</a>`;
const side=document.createElement('aside');side.className='sidebar';side.id='studio-sidebar';side.innerHTML=`<a class="brand" href="/centro.html"><span class="brand-symbol">${studioIcon('spark',21)}</span><span><strong>GCODE</strong><small>STUDIO</small></span></a><nav aria-label="Navegación principal">${nav('home','/centro.html','home','Inicio')}${nav('create','/create.html','spark','Crear una pieza')}${nav('marketing','/marketing.html','image','Marketing y recursos')}${nav('ads','/ads.html','spark','Publicidad y resultados')}<div class="nav-label">HERRAMIENTAS</div>${nav('editor','/editor.html','video','Editor de video')}${nav('feed','/feed-editor.html','image','Imágenes y carruseles')}${nav('images','/images.html','spark','Líneas de imágenes')}<div class="nav-label">TU BIBLIOTECA</div><div id="sidebar-projects"><a class="nav-item nav-project" href="/editor.html?project=comercial-n8n"><span class="project-dot">${studioIcon('video',13)}</span><span><strong>Reportes del negocio</strong><small>Video comercial</small></span></a><a class="nav-item nav-project" href="/editor.html?project=piloto-voz-selectiva"><span class="project-dot">${studioIcon('video',13)}</span><span><strong>Menos papelitos</strong><small>Historia ilustrada</small></span></a><a class="nav-item nav-project" href="/feed-editor.html?project=imagen-insumos"><span class="project-dot">${studioIcon('image',13)}</span><span><strong>Antes de comprar, revisa</strong><small>Imagen de feed</small></span></a></div></nav><div class="side-bottom">${nav('account','/account.html','user','Cuenta y acceso')}<a class="button new-piece" href="/create.html">${studioIcon('plus',15)} Nueva pieza</a><div class="private-label"><i></i> Tu espacio privado</div></div>`;
document.body.prepend(side);const overlay=document.createElement('div');overlay.className='mobile-overlay';document.body.append(overlay);
const top=document.createElement('header');top.className='topbar';top.innerHTML=`<div class="crumb"><button class="menu-toggle" aria-label="Abrir menú" aria-expanded="false" aria-controls="studio-sidebar">${studioIcon('menu')}</button><span>GCODE Studio</span><span>/</span><b>${names[page]}</b></div><div class="top-actions"><span>Hecho para tu marca</span><a class="avatar" href="/account.html" aria-label="Mi cuenta">G</a></div>`;side.after(top);
const toggle=()=>{const open=side.classList.toggle('open');overlay.classList.toggle('visible',open);top.querySelector('button').setAttribute('aria-expanded',String(open))};top.querySelector('button').onclick=toggle;overlay.onclick=toggle;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&side.classList.contains('open'))toggle()});
fetch('/auth/me').then(r=>r.ok?r.json():null).then(u=>{window.studioUser=u;if(u)top.querySelector('.avatar').textContent=u.username.slice(0,1).toUpperCase();if(u?.role==='admin')mountDiskUsage()}).catch(()=>{});
function mountDiskUsage(){
 const box=document.createElement('section');box.className='server-disk';box.setAttribute('aria-label','Espacio del servidor');box.innerHTML='<div class="server-disk-heading"><strong>Disco del servidor</strong><button type="button" aria-label="Actualizar espacio del servidor" title="Actualizar">↻</button></div><p class="server-disk-info" role="status">Consultando espacio…</p><progress max="100" aria-label="Porcentaje de disco ocupado" hidden></progress><small class="server-disk-detail"></small>';
 side.querySelector('.side-bottom').prepend(box);const info=box.querySelector('.server-disk-info'),detail=box.querySelector('.server-disk-detail'),bar=box.querySelector('progress'),btn=box.querySelector('button');let busy=false;
 const size=n=>new Intl.NumberFormat('es-DO',{maximumFractionDigits:1}).format(n/1024**3)+' GiB';
 async function refresh(){if(busy||document.hidden)return;busy=true;btn.disabled=true;try{const r=await fetch('/api/storage/usage',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('unavailable');const d=await r.json();if(!Number.isFinite(d.used_percent))throw Error('invalid');bar.value=d.used_percent;bar.hidden=false;bar.setAttribute('aria-valuetext',d.used_percent+' % ocupado; '+size(d.available_bytes)+' disponibles');box.dataset.level=d.status;info.textContent=size(d.used_bytes)+' / '+size(d.total_bytes)+' · '+d.used_percent+' %';detail.textContent=size(d.available_bytes)+' libres'+(d.status==='critical'?' · Espacio crítico':d.status==='warning'?' · Poco espacio':'');box.title='Disco donde Studio guarda sus datos. Incluye archivos de otros servicios en ese volumen. Reservado por el sistema: '+size(d.reserved_bytes)+'. Actualizado: '+new Date(d.checked_at).toLocaleTimeString('es-DO');}catch{bar.hidden=true;delete box.dataset.level;info.textContent='Espacio no disponible';detail.textContent='Pulsa actualizar para volver a consultar.'}finally{busy=false;btn.disabled=false}}
 btn.onclick=refresh;refresh();const timer=setInterval(refresh,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});
}
})();
