import {mkdir,readFile,writeFile,rename,stat,open} from 'node:fs/promises'
import {join} from 'node:path'
import {randomUUID,createHash} from 'node:crypto'
import {configuration,hash,stamp,fail,requireValue,text,digits,date,exactDecimal,sumDecimals,principalScope,canAccess,publicConnection} from './contracts.mjs'
import {MetaAds} from './meta.mjs'
import {TikTokAds} from './tiktok.mjs'
const initial=()=>({schema:1,connections:[],drafts:[],operations:[],metrics:[],syncs:[],audit:[]})
export class AdsStore{
 constructor(root,{capture,artifact,brands,provider,credentials,allowWrites=process.env.STUDIO_ADS_ENABLE_WRITES==='1'}={}){this.dir=join(root,'.studio-state','ads');this.file=join(this.dir,'state.json');this.capture=capture;this.artifact=artifact;this.brands=brands;this.providerFactory=provider;this.credentials=credentials||this.resolveCredential.bind(this);this.allowWrites=allowWrites;this.serial=Promise.resolve();this.data=initial();this.syncing=new Map()}
 async init(){await mkdir(this.dir,{recursive:true,mode:0o700});try{this.data=JSON.parse(await readFile(this.file,'utf8'));requireValue(this.data.schema===1,'Versión Ads no admitida',500)}catch(e){if(e.code!=='ENOENT')throw e}let recovered=false;for(const op of this.data.operations)if(op.status==='working'){op.status='uncertain';op.error='Servicio interrumpido: conciliar antes de repetir';recovered=true}if(recovered)await this.save();return this}
 async save(){const tmp=join(this.dir,randomUUID()+'.tmp');const file=await open(tmp,'wx',0o600);try{await file.writeFile(JSON.stringify(this.data));await file.sync()}finally{await file.close()}await rename(tmp,this.file);const directory=await open(this.dir,'r');try{await directory.sync()}finally{await directory.close()}}
 tx(fn){const result=this.serial.then(async()=>{const before=structuredClone(this.data);try{return await fn()}catch(e){try{this.data=JSON.parse(await readFile(this.file,'utf8'))}catch{this.data=before}throw e}});this.serial=result.catch(()=>{});return result}
 log(actor,action,details={}){this.data.audit.push({at:stamp(),actor:actor.username,action,...details})}
 connection(id,actor,scope='ads.read'){principalScope(actor,scope);const c=this.data.connections.find(x=>x.id===id);requireValue(c&&canAccess(c,actor),'Cuenta no autorizada',403);return c}
 snapshot(actor){principalScope(actor,'ads.read');const ids=new Set(this.data.connections.filter(c=>canAccess(c,actor)).map(c=>c.id));return structuredClone({connections:this.data.connections.filter(c=>ids.has(c.id)).map(publicConnection),drafts:this.data.drafts.filter(d=>ids.has(d.connection_id)),operations:this.data.operations.filter(d=>ids.has(d.connection_id)),metrics:this.data.metrics.filter(d=>ids.has(d.connection_id)),syncs:this.data.syncs.filter(d=>ids.has(d.connection_id)),writes_enabled:this.allowWrites,audit:actor.role==='admin'?this.data.audit.slice(-100):[]})}
 async resolveCredential(ref){requireValue(/^[A-Z][A-Z0-9_]{2,80}$/.test(ref),'Referencia de credencial inválida');let value=process.env[ref];if(!value){const file=join(this.dir,'credentials.json');try{const st=await stat(file);requireValue((st.mode&0o077)===0,'El archivo de credenciales requiere permisos 0600',503);value=JSON.parse(await readFile(file,'utf8'))[ref]}catch(e){if(e.code!=='ENOENT')throw fail(503,'No se pudo leer la configuración privada Ads')}}requireValue(typeof value==='string'&&value.length>10,'Configura la credencial Ads en el servidor',503);return value}
 async provider(c,writable=false){if(this.providerFactory)return this.providerFactory(c,writable);const token=await this.credentials(c.credential_ref);return c.platform==='meta'?new MetaAds({token,account_id:c.account_id,writable}):new TikTokAds({token,account_id:c.account_id})}
 async saveConnection(input,actor){principalScope(actor,'ads.admin');return this.tx(async()=>{
  requireValue(['meta','tiktok'].includes(input.platform),'Plataforma inválida');requireValue((input.platform==='meta'?/^act_\d+$/:/^\d+$/).test(input.account_id||''),'Cuenta publicitaria inválida');requireValue(this.brands().some(b=>b.id===input.brand_id),'Marca no encontrada');requireValue(/^[A-Z][A-Z0-9_]{2,80}$/.test(input.credential_ref||''),'Usa una referencia de credencial, nunca el token');requireValue(Array.isArray(input.allowed_users||[])&&(input.allowed_users||[]).every(x=>typeof x==='string'&&/^[a-zA-Z0-9_.@-]{1,100}$/.test(x)),'Usuarios inválidos');
  const old=input.id?this.connection(input.id,actor):null;if(old)requireValue(old.platform===input.platform&&old.account_id===input.account_id&&old.brand_id===input.brand_id,'Identidad de cuenta inmutable; registra otra conexión');requireValue(!this.data.connections.some(c=>c.id!==old?.id&&c.platform===input.platform&&c.account_id===input.account_id),'Esta cuenta ya está registrada');
  const c={id:old?.id||randomUUID(),platform:input.platform,account_id:input.account_id,brand_id:input.brand_id,credential_ref:input.credential_ref,allowed_users:[...new Set(input.allowed_users||[])],auto_sync:input.auto_sync===true,created_at:old?.created_at||stamp(),revision:(old?.revision||0)+1,status:'unverified',metadata:null};
  if(old)Object.assign(old,c);else this.data.connections.push(c);this.log(actor,'connection.saved',{connection_id:c.id});await this.save();return publicConnection(c);
 })}
 async verify(id,actor){return this.tx(async()=>{const c=this.connection(id,actor,'ads.sync');try{const p=await this.provider(c);const metadata=await p.verify();requireValue(metadata.id===c.account_id,'Cuenta remota incorrecta',502);c.metadata=metadata;c.status='verified';this.log(actor,'connection.verified',{connection_id:id});await this.save();return publicConnection(c)}catch(e){c.status='unverified';c.metadata=null;await this.save();throw e}})}
 verified(c){requireValue(c.status==='verified'&&c.metadata&&Date.now()-Date.parse(c.metadata.verified_at)<86400000,'Verifica la conexión (vigencia de comprobación: 24 h)',409)}
 async saveDraft(input,actor){return this.tx(async()=>{
  const c=this.connection(input.connection_id,actor,'ads.draft');this.verified(c);requireValue(c.platform==='meta','TikTok disponible para lectura; creación aún no habilitada',409);
  const current=input.id?this.data.drafts.find(d=>d.id===input.id):null;if(input.id)requireValue(current&&current.connection_id===c.id,'Borrador no encontrado',404);
  const snap=await this.capture(input.piece_id);requireValue(snap.brand_id===c.brand_id,'La pieza no pertenece a esta marca',403);requireValue(['video','imagen'].includes(snap.kind)&&snap.files?.length===1,'Selecciona un video o una imagen; carruseles requieren otro contrato');
  const config=configuration(input.config);requireValue(config.currency===c.metadata.currency,'La moneda debe coincidir con la cuenta');requireValue(new Date(config.end_time)>new Date(),'La campaña ya terminó');
  if(snap.kind==='video')requireValue(/^[a-f0-9]{64}$/.test(snap.cover_sha256||''),'Falta portada verificada');
  const snapshot=structuredClone(snap),fingerprint=hash({connection_id:c.id,connection_revision:c.revision,account_id:c.account_id,snapshot,config});
  if(current?.hash===fingerprint)return structuredClone(current);if(!current){const identical=this.data.drafts.find(d=>d.connection_id===c.id&&d.hash===fingerprint);if(identical)return structuredClone(identical)}
  requireValue(!current||!this.data.operations.some(o=>o.draft_id===current.id&&!['cancelled','failed'].includes(o.status)),'Crea otro borrador: existe una operación remota o incierta',409);
  const d={id:current?.id||randomUUID(),connection_id:c.id,connection_revision:c.revision,piece_id:input.piece_id,snapshot,config,hash:fingerprint,revision:(current?.revision||0)+1,created_at:current?.created_at||stamp(),updated_at:stamp(),editorial:null,authorization:null,history:[...(current?.history||[]),...(current?[{hash:current.hash,config:current.config,snapshot:current.snapshot,editorial:current.editorial,authorization:current.authorization,at:stamp()}]:[])]};
  if(current)Object.assign(current,d);else this.data.drafts.push(d);this.log(actor,'draft.saved',{draft_id:d.id,hash:d.hash});await this.save();return structuredClone(d);
 })}
 draft(id,actor,scope='ads.read'){const d=this.data.drafts.find(x=>x.id===id);requireValue(d,'Borrador no encontrado',404);this.connection(d.connection_id,actor,scope);return d}
 async current(d,actor){const c=this.connection(d.connection_id,actor);this.verified(c);requireValue(c.revision===d.connection_revision,'La conexión cambió; guarda y revisa otra versión',409);const now=await this.capture(d.piece_id);requireValue(hash(now)===hash(d.snapshot),'La pieza cambió; guarda y revisa otra versión',409);requireValue(d.config.currency===c.metadata.currency,'La moneda de la cuenta cambió',409);return c}
 async approve(input,actor){principalScope(actor,'ads.approve');return this.tx(async()=>{const d=this.draft(input.id,actor);await this.current(d,actor);requireValue(input.hash===d.hash,'El borrador cambió',409);requireValue(input.paid_rights===true&&input.no_special_category===true,'Confirma derechos publicitarios y que no pertenece a categoría especial');d.editorial={hash:d.hash,actor:actor.username,at:stamp(),paid_rights:true,no_special_category:true,note:text(input.note,1000)};d.authorization=null;this.log(actor,'draft.editorial_approved',{draft_id:d.id,hash:d.hash});await this.save();return structuredClone(d)})}
 async authorize(input,actor){principalScope(actor,'ads.authorize');return this.tx(async()=>{const d=this.draft(input.id,actor);await this.current(d,actor);requireValue(input.hash===d.hash&&d.editorial?.hash===d.hash,'Aprueba la versión editorial actual',409);requireValue(input.confirmed===true&&input.budget_minor===d.config.budget_minor&&input.currency===d.config.currency,'Confirma el presupuesto total y la moneda exactos');requireValue(Date.parse(d.config.start_time)>Date.now(),'El comienzo debe ser futuro');d.authorization={hash:d.hash,actor:actor.username,at:stamp(),budget_minor:d.config.budget_minor,currency:d.config.currency,expires_at:d.config.end_time};this.log(actor,'spend.authorized',{draft_id:d.id,hash:d.hash,budget_minor:d.config.budget_minor,currency:d.config.currency});await this.save();return structuredClone(d)})}
 async ready(d,actor){const c=await this.current(d,actor);requireValue(d.editorial?.hash===d.hash&&d.authorization?.hash===d.hash&&Date.parse(d.authorization.expires_at)>Date.now(),'Falta autorización vigente para esta configuración',409);return c}
 async execute(input,actor){principalScope(actor,'ads.execute');requireValue(this.allowWrites,'Las escrituras Ads están deshabilitadas en el servidor',403);return this.tx(async()=>{
  const d=this.draft(input.id,actor),c=await this.ready(d,actor);requireValue(input.hash===d.hash&&input.confirmed===true,'Confirma creación pausada de esta versión');
  let op=this.data.operations.find(o=>o.draft_id===d.id&&o.hash===d.hash&&o.type==='create');
  if(op){requireValue(!['uncertain','working','cancelled'].includes(op.status),'Operación incierta, activa o cancelada; revisa antes de continuar',409);if(op.status==='paused'||op.status==='active')return structuredClone(op)}
  else {op={id:randomUUID(),type:'create',draft_id:d.id,hash:d.hash,connection_id:c.id,status:'ready',ids:{},at:stamp(),events:[]};this.data.operations.push(op);await this.save()}
  const provider=await this.provider(c,true),phases=['media',...(d.snapshot.kind==='video'?['cover']:[]),'campaign','adset','creative','ad'];
  for(const phase of phases){if(op.ids[phase])continue;await this.ready(d,actor);op.status='working';op.phase=phase;op.events.push({at:stamp(),phase,state:'requesting'});await this.save();
   try{const r=await provider.create(phase,d,op.ids,this.artifact);requireValue(typeof r?.id==='string'&&/^[a-zA-Z0-9]{1,80}$/.test(r.id),'Respuesta remota sin ID; requiere conciliación',502);op.ids[phase]=r.id;op.status='ready';op.events.push({at:stamp(),phase,state:'confirmed',remote_id:r.id});await this.save()}
   catch(e){op.status=(typeof e.provider_status==='number'?e.uncertain:(!e.status||e.status>=500))?'uncertain':'failed';op.error=e.status?e.message:'Fallo de proveedor; no se repite automáticamente';op.events.push({at:stamp(),phase,state:op.status});await this.save();throw fail(409,op.error)}
  }
  try{await this.checkRemote(provider,d,op);op.status='paused';op.phase=null;op.error=null;this.log(actor,'ads.created_paused',{operation_id:op.id,hash:d.hash});await this.save();return structuredClone(op)}catch(e){op.status='uncertain';op.error='No se pudo confirmar estado remoto pausado';await this.save();throw fail(409,op.error)}
 })}
 async matches(provider,d,op,phase,id){const r=await provider.inspect(id,phase),c=d.config;
  requireValue(String(r.id)===id,'ID remoto incorrecto');
  if(['campaign','adset','ad'].includes(phase))requireValue(r.status==='PAUSED','El objeto remoto no está pausado',409);
  if(phase==='campaign')requireValue(r.objective===c.objective&&r.name===c.name+' · '+d.hash.slice(0,10)&&Array.isArray(r.special_ad_categories)&&!r.special_ad_categories.length,'Campaña remota diferente',409);
  if(phase==='adset')requireValue(Object.keys(r.targeting||{}).every(k=>['geo_locations','age_min','age_max','publisher_platforms'].includes(k))&&Object.keys(r.targeting?.geo_locations||{}).every(k=>k==='countries')&&r.campaign_id===op.ids.campaign&&r.lifetime_budget===c.budget_minor&&Date.parse(r.start_time)===Date.parse(c.start_time)&&Date.parse(r.end_time)===Date.parse(c.end_time)&&r.optimization_goal===c.optimization_goal&&r.billing_event===c.billing_event&&hash([...(r.targeting?.geo_locations?.countries||[])].sort())===hash(c.countries)&&r.targeting?.age_min===c.age_min&&r.targeting?.age_max===c.age_max&&hash([...(r.targeting?.publisher_platforms||[])].sort())===hash(c.platforms),'Conjunto remoto diferente',409);
  if(phase==='creative'){const s=r.object_story_spec,v=d.snapshot.kind==='video'?s?.video_data:s?.link_data;requireValue(s?.page_id===c.page_id&&(!c.instagram_actor_id||s.instagram_actor_id===c.instagram_actor_id)&&v?.message===c.copy&&(d.snapshot.kind==='video'?v.video_id===op.ids.media&&v.image_hash===op.ids.cover:v.image_hash===op.ids.media&&v.link===c.destination)&&v.call_to_action?.type==='LEARN_MORE'&&v.call_to_action?.value?.link===c.destination,'Creatividad remota diferente',409)}
  if(phase==='ad')requireValue(r.adset_id===op.ids.adset&&r.creative?.id===op.ids.creative,'Anuncio remoto diferente',409);return r;
 }
 async checkRemote(provider,d,op){for(const phase of ['campaign','adset','creative','ad'])await this.matches(provider,d,op,phase,op.ids[phase])}
 async reconcile(input,actor){principalScope(actor,'ads.execute');return this.tx(async()=>{const op=this.data.operations.find(x=>x.id===input.operation_id);requireValue(op&&op.type==='create'&&['uncertain','failed'].includes(op.status),'Operación no conciliable',409);const d=this.draft(op.draft_id,actor),c=await this.ready(d,actor);requireValue(op.hash===d.hash,'La versión cambió');const p=await this.provider(c);if(op.phase&& !op.ids[op.phase]){requireValue(['campaign','adset','creative','ad'].includes(op.phase),'Carga de medios incierta: revisión manual del proveedor; no reenvíes',409);const id=digits(input.remote_id);await this.matches(p,d,op,op.phase,id);op.ids[op.phase]=id}op.status='ready';op.error=null;this.log(actor,'operation.reconciled',{operation_id:op.id,ids:op.ids});await this.save();return structuredClone(op)})}
 async activate(input,actor){principalScope(actor,'ads.activate');requireValue(this.allowWrites,'Las escrituras Ads están deshabilitadas',403);return this.tx(async()=>{const op=this.data.operations.find(x=>x.id===input.operation_id);requireValue(op?.type==='create'&&op.status==='paused','Solo se activa una creación confirmada pausada',409);const d=this.draft(op.draft_id,actor),c=await this.ready(d,actor);requireValue(op.hash===d.hash,'La operación pertenece a otra versión',409);requireValue(input.hash===d.hash&&input.confirmation===`ACTIVAR ${d.config.budget_minor} ${d.config.currency}`,'Confirma explícitamente importe y moneda');requireValue(Date.parse(d.config.start_time)>Date.now(),'Actualiza fechas y revisa de nuevo: comienzo vencido',409);const p=await this.provider(c,true);await this.checkRemote(p,d,op);
  op.activation={actor:actor.username,at:stamp(),hash:d.hash};op.status='working';op.phase='activation';await this.save();
  try{for(const phase of ['ad','adset','campaign']){await p.setStatus(op.ids[phase],'ACTIVE');const r=await p.inspect(op.ids[phase],phase);requireValue(r.status==='ACTIVE','Activación sin confirmar',502)}op.status='active';op.phase=null;this.log(actor,'ads.activated',{operation_id:op.id,hash:d.hash});await this.save();return structuredClone(op)}catch{op.status='uncertain';op.error='Activación parcial o incierta. Comprueba y pausa en Ads Manager antes de continuar.';await this.save();throw fail(409,op.error)}
 })}
 async pause(input,actor){principalScope(actor,'ads.activate');requireValue(this.allowWrites,'Las escrituras Ads están deshabilitadas',403);return this.tx(async()=>{const op=this.data.operations.find(x=>x.id===input.operation_id);requireValue(op?.ids.campaign,'No hay campaña remota',409);const c=this.connection(op.connection_id,actor),p=await this.provider(c,true);const remote=await p.inspect(op.ids.campaign,'campaign');requireValue(remote.id===op.ids.campaign,'ID diferente');op.status='working';op.phase='pause';await this.save();try{await p.setStatus(op.ids.campaign,'PAUSED');const r=await p.inspect(op.ids.campaign,'campaign');requireValue(r.status==='PAUSED','Pausa incierta',502);op.status='stopped';op.phase=null;this.log(actor,'ads.paused',{operation_id:op.id});await this.save();return structuredClone(op)}catch{op.status='uncertain';op.error='No se pudo confirmar pausa; consulta Ads Manager';await this.save();throw fail(409,op.error)}})}
 async sync(input,actor){const c=this.connection(input.connection_id,actor,'ads.sync');this.verified(c);const since=date(input.since),until=date(input.until);requireValue(since<=until&&Date.parse(until)-Date.parse(since)<=31*86400000,'Rango máximo de 31 días');requireValue(!this.syncing.has(c.id),'Ya hay una lectura en curso',409);this.syncing.set(c.id,true);const revision=c.revision;
  try{const p=await this.provider(c),[metrics,inventory]=await Promise.all([p.insights(since,until),p.inventory()]);return await this.tx(async()=>{requireValue(c.revision===revision,'La conexión cambió durante la lectura',409);const run={id:randomUUID(),connection_id:c.id,since,until,at:stamp(),complete:metrics.complete&&Object.values(inventory).every(x=>x.complete),api_version:c.metadata.api_version,inventory};
   const normalized=metrics.rows.map(r=>{requireValue(!r.account_id||String(r.account_id)===c.account_id.replace(/^act_/,''),'Reporte de otra cuenta',502);requireValue(!r.account_currency||r.account_currency===c.metadata.currency,'Moneda remota diferente',502);const start=date(r.date_start),end=date(r.date_stop);requireValue(start===end&&start>=since&&end<=until,'Reporte fuera del período',502);const values={};for(const k of ['spend','impressions','clicks','reach'])values[k]=r[k]==null?null:exactDecimal(String(r[k]));const dimensions={connection_id:c.id,platform:c.platform,account_id:c.account_id,ad_id:digits(String(r.ad_id)),level:'ad',since:start,until:end,currency:c.metadata.currency,timezone:c.metadata.timezone,attribution:c.platform==='meta'?'unified_adset_setting':'provider_default',attribution_config:c.platform==='meta'?(inventory.adsets.rows.find(x=>x.id===r.adset_id)?.attribution_spec||null):null,api_version:c.metadata.api_version};return {...dimensions,key:hash(dimensions),campaign_id:r.campaign_id||null,adset_id:r.adset_id||null,values,fetched_at:run.at,sync_id:run.id,coverage:metrics.complete?'complete':'partial',maturity:start<new Intl.DateTimeFormat('en-CA',{timeZone:c.metadata.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())?'closed_day':'provisional',draft_id:this.data.operations.find(o=>o.connection_id===c.id&&o.ids.ad===String(r.ad_id))?.draft_id||null}});
   for(const row of normalized){const old=this.data.metrics.find(x=>x.key===row.key);if(old)Object.assign(old,{...row,revisions:[...(old.revisions||[]),...(hash(old.values)!==hash(row.values)?[{values:old.values,fetched_at:old.fetched_at}]:[])]});else this.data.metrics.push({...row,revisions:[]})}
   this.data.syncs.push(run);this.log(actor,'metrics.synced',{connection_id:c.id,sync_id:run.id,complete:run.complete});await this.save();return structuredClone(run);
  })}finally{this.syncing.delete(c.id)}
 }
}
export function metricTotals(rows){const groups=new Map();for(const r of rows){const key=hash([r.platform,r.account_id,r.currency,r.timezone,r.attribution,r.attribution_config,r.api_version]);const g=groups.get(key)||{currency:r.currency,timezone:r.timezone,attribution:r.attribution,api_version:r.api_version,spend:[],impressions:[],clicks:[],incomplete:false};for(const k of ['spend','impressions','clicks'])if(r.values[k]!==null)g[k].push(r.values[k]);else g.incomplete=true;if(r.coverage!=='complete')g.incomplete=true;groups.set(key,g)}return [...groups.values()].map(g=>({...g,spend:g.spend.length?sumDecimals(g.spend):null,impressions:g.impressions.length?sumDecimals(g.impressions):null,clicks:g.clicks.length?sumDecimals(g.clicks):null}))}
